// Code generated by gen; DO NOT EDIT.

package client

type APIKeyInfo struct {
	ID           *string                `json:"id,omitempty"`
	Name         *string                `json:"name,omitempty"`
	ScopeRoot    *string                `json:"scope_root,omitempty"`
	ScopeFolders []APIKeyScopeFolder    `json:"scope_folders,omitempty"`
	Tier         *string                `json:"tier,omitempty"`
	ScopeMode    *string                `json:"scope_mode,omitempty"`
	Capabilities map[string]any         `json:"capabilities,omitempty"`
	Surfaces     []string               `json:"surfaces,omitempty"`
	TokenPrefix  *string                `json:"token_prefix,omitempty"`
	LastUsedAt   *string                `json:"last_used_at,omitempty"`
	ExpiresAt    *string                `json:"expires_at,omitempty"`
	CreatedAt    *string                `json:"created_at,omitempty"`
	Workspaces   []APIKeyWorkspaceGrant `json:"workspaces,omitempty"`
}

type APIKeyScopeFolder struct {
	ID    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
}

type APIKeyWorkspaceGrant struct {
	WorkspaceID    *string             `json:"workspace_id,omitempty"`
	WorkspaceName  *string             `json:"workspace_name,omitempty"`
	WorkspaceColor *string             `json:"workspace_color,omitempty"`
	FolderTitle    *string             `json:"folder_title,omitempty"`
	Folders        []APIKeyScopeFolder `json:"folders,omitempty"`
}

type AcceptInviteLinkResult struct {
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
}

type Annotation struct {
	ID           *string `json:"id,omitempty"`
	SpaceID      *string `json:"space_id,omitempty"`
	NodeID       *string `json:"node_id,omitempty"`
	OwnerID      *string `json:"owner_id,omitempty"`
	ParentID     *string `json:"parent_id,omitempty"`
	AnchorType   *string `json:"anchor_type,omitempty"`
	AnchorQuote  *string `json:"anchor_quote,omitempty"`
	AnchorPrefix *string `json:"anchor_prefix,omitempty"`
	AnchorSuffix *string `json:"anchor_suffix,omitempty"`
	AnchorRev    *string `json:"anchor_rev,omitempty"`
	Color        *string `json:"color,omitempty"`
	Body         *string `json:"body,omitempty"`
	Resolved     *bool   `json:"resolved,omitempty"`
	CreatedAt    *string `json:"created_at,omitempty"`
	UpdatedAt    *string `json:"updated_at,omitempty"`
	DeletedAt    *string `json:"deleted_at,omitempty"`
}

type AnnotationAddParams struct {
	// Id of the node the annotation anchors to
	NodeID string `json:"node_id"`
	// Annotation text (markdown)
	Body string `json:"body"`
	// text quote-selector (default) or block media element
	AnchorType *string `json:"anchor_type,omitempty"`
	// The exact selected text — OR the media src for a block anchor
	AnchorQuote *string `json:"anchor_quote,omitempty"`
	// ~32 chars before the quote
	AnchorPrefix *string `json:"anchor_prefix,omitempty"`
	// ~32 chars after the quote
	AnchorSuffix *string `json:"anchor_suffix,omitempty"`
	// Page revision id at creation (orphan deep-link)
	AnchorRev *string `json:"anchor_rev,omitempty"`
	// pigment red/orange/amber/green/blue/violet (root note)
	Color *string `json:"color,omitempty"`
	// For a threaded reply
	ParentID *string `json:"parent_id,omitempty"`
	// Present when annotating via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationChangesParams struct {
	// RFC3339Nano cursor; empty = full
	Since *string `json:"since,omitempty"`
}

type AnnotationDeleteParams struct {
	// Id of the annotation to delete
	ID string `json:"id"`
	// Present when deleting via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationDeleted struct {
	ID *string `json:"id,omitempty"`
	Ok *bool   `json:"ok,omitempty"`
}

type AnnotationEditParams struct {
	// Id of the annotation to edit
	ID string `json:"id"`
	// Replacement annotation body (markdown)
	Body string `json:"body"`
	// Present when editing via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationFeed struct {
	Annotations []Annotation `json:"annotations,omitempty"`
	Tombstones  []string     `json:"tombstones,omitempty"`
	Cursor      *string      `json:"cursor,omitempty"`
}

type AnnotationGetParams struct {
	// Id of the annotation to fetch
	ID string `json:"id"`
	// Present when reading via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationListParams struct {
	// Node whose annotations to list
	NodeID string `json:"node_id"`
	// Present when listing via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationSetResolvedParams struct {
	// Id of the annotation to resolve or reopen
	ID string `json:"id"`
	// true to resolve; false to reopen
	Resolved *bool `json:"resolved,omitempty"`
	// Present when resolving via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationThread struct {
	Annotations []AnnotationView `json:"annotations,omitempty"`
}

type AnnotationView struct {
	ID           *string `json:"id,omitempty"`
	NodeID       *string `json:"node_id,omitempty"`
	OwnerID      *string `json:"owner_id,omitempty"`
	Author       *string `json:"author,omitempty"`
	ParentID     *string `json:"parent_id,omitempty"`
	AnchorType   *string `json:"anchor_type,omitempty"`
	AnchorQuote  *string `json:"anchor_quote,omitempty"`
	AnchorPrefix *string `json:"anchor_prefix,omitempty"`
	AnchorSuffix *string `json:"anchor_suffix,omitempty"`
	AnchorRev    *string `json:"anchor_rev,omitempty"`
	Color        *string `json:"color,omitempty"`
	Body         *string `json:"body,omitempty"`
	Resolved     *bool   `json:"resolved,omitempty"`
	CreatedAt    *string `json:"created_at,omitempty"`
	UpdatedAt    *string `json:"updated_at,omitempty"`
}

type AuditEvent struct {
	ID        *string        `json:"id,omitempty"`
	Actor     *string        `json:"actor,omitempty"`
	Action    *string        `json:"action,omitempty"`
	Target    *string        `json:"target,omitempty"`
	Meta      map[string]any `json:"meta,omitempty"`
	CreatedAt *string        `json:"created_at,omitempty"`
	Space     *string        `json:"space,omitempty"`
}

type AuditExportFile struct {
	Filename *string `json:"filename,omitempty"`
	Mime     *string `json:"mime,omitempty"`
	Content  *string `json:"content,omitempty"`
}

type BaseModel struct {
}

type BoardLayout struct {
	Order   []string       `json:"order,omitempty"`
	Columns map[string]any `json:"columns,omitempty"`
	Wip     *float64       `json:"wip,omitempty"`
	View    *string        `json:"view,omitempty"`
}

type CalFeedCreateParams struct {
	// Calendar node the subscribe feed is for
	NodeID string `json:"node_id"`
}

type CalFeedRevokeParams struct {
	// Calendar node the subscribe feed is for
	NodeID string `json:"node_id"`
}

type CalFeedStatusParams struct {
	// Calendar node the subscribe feed is for
	NodeID string `json:"node_id"`
}

type ChangesResult struct {
	Pages      []Page   `json:"pages,omitempty"`
	Tombstones []string `json:"tombstones,omitempty"`
	Cursor     *string  `json:"cursor,omitempty"`
}

type ChildrenResult struct {
	Nodes     []SharedNode `json:"nodes,omitempty"`
	Cursor    *string      `json:"cursor,omitempty"`
	More      *bool        `json:"more,omitempty"`
	Remaining *float64     `json:"remaining,omitempty"`
}

type Comment struct {
	ID        *string `json:"id,omitempty"`
	SpaceID   *string `json:"space_id,omitempty"`
	NodeID    *string `json:"node_id,omitempty"`
	OwnerID   *string `json:"owner_id,omitempty"`
	ParentID  *string `json:"parent_id,omitempty"`
	Body      *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type CommentAddParams struct {
	// Id of the node to comment on
	NodeID string `json:"node_id"`
	// Comment text (markdown)
	Body string `json:"body"`
	// For a threaded reply
	ParentID *string `json:"parent_id,omitempty"`
}

type CommentDeleteParams struct {
	// Id of the comment to delete
	ID string `json:"id"`
}

type CommentDeleted struct {
	ID *string `json:"id,omitempty"`
	Ok *bool   `json:"ok,omitempty"`
}

type CommentEditParams struct {
	// Id of the comment to edit
	ID string `json:"id"`
	// Replacement comment body (markdown)
	Body string `json:"body"`
}

type CommentListParams struct {
	// Node whose comments to list
	NodeID string `json:"node_id"`
}

type CommentThread struct {
	Comments []CommentView `json:"comments,omitempty"`
}

type CommentView struct {
	ID        *string `json:"id,omitempty"`
	NodeID    *string `json:"node_id,omitempty"`
	OwnerID   *string `json:"owner_id,omitempty"`
	Author    *string `json:"author,omitempty"`
	ParentID  *string `json:"parent_id,omitempty"`
	Body      *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type ConfigRevision struct {
	ID        *string        `json:"id,omitempty"`
	Config    map[string]any `json:"config,omitempty"`
	Actor     *string        `json:"actor,omitempty"`
	CreatedAt *string        `json:"created_at,omitempty"`
}

type CreateAPIKeyResult struct {
	ID  *string `json:"id,omitempty"`
	Key *string `json:"key,omitempty"`
}

type CreateKeyResult struct {
	ID  *string `json:"id,omitempty"`
	Key *string `json:"key,omitempty"`
}

type DashboardSnapshot struct {
	Config  map[string]any `json:"config,omitempty"`
	CanEdit *bool          `json:"can_edit,omitempty"`
	Locked  *bool          `json:"locked,omitempty"`
	CanLock *bool          `json:"can_lock,omitempty"`
}

type Event struct {
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	StartAt   *string  `json:"start_at,omitempty"`
	EndAt     *string  `json:"end_at,omitempty"`
	AllDay    *bool    `json:"all_day,omitempty"`
	Tz        *string  `json:"tz,omitempty"`
	Rrule     *string  `json:"rrule,omitempty"`
	Location  *string  `json:"location,omitempty"`
	Color     *string  `json:"color,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
	DeletedAt *string  `json:"deleted_at,omitempty"`
}

type EventChangesParams struct {
	// RFC3339Nano cursor; empty = full
	Since *string `json:"since,omitempty"`
}

type EventDeleteAck struct {
	NodeID *string `json:"node_id,omitempty"`
	Ok     *bool   `json:"ok,omitempty"`
}

type EventDeleteParams struct {
	// Id of the event page whose metadata to drop
	NodeID string `json:"node_id"`
}

type EventFeed struct {
	Events     []Event  `json:"events,omitempty"`
	Tombstones []string `json:"tombstones,omitempty"`
	Cursor     *string  `json:"cursor,omitempty"`
}

type EventGetParams struct {
	// Id of the event page
	NodeID string `json:"node_id"`
}

type EventHistoryParams struct {
	// Id of the event page
	NodeID string `json:"node_id"`
}

type EventPatchParams struct {
	// Id of the event page to patch
	NodeID string `json:"node_id"`
	// local ISO start; omit to leave untouched
	StartAt *string `json:"start_at,omitempty"`
	// local ISO end; omit to leave untouched
	EndAt *string `json:"end_at,omitempty"`
	// whole-day flag; omit to leave untouched
	AllDay *bool `json:"all_day,omitempty"`
	// IANA zone; omit to leave untouched
	Tz *string `json:"tz,omitempty"`
	// RFC-5545 RRULE; omit to leave untouched
	Rrule *string `json:"rrule,omitempty"`
	// place or address; omit to leave untouched
	Location *string `json:"location,omitempty"`
	// pigment token; omit to leave untouched
	Color *string `json:"color,omitempty"`
	// assigned user subjects; omit to leave untouched
	Assignee []string `json:"assignee,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type EventRestoreParams struct {
	// Id of the event page to restore
	NodeID string `json:"node_id"`
	// Id of the revision to restore
	RevID string `json:"rev_id"`
}

type EventRevision struct {
	ID        *string  `json:"id,omitempty"`
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	StartAt   *string  `json:"start_at,omitempty"`
	EndAt     *string  `json:"end_at,omitempty"`
	AllDay    *bool    `json:"all_day,omitempty"`
	Tz        *string  `json:"tz,omitempty"`
	Rrule     *string  `json:"rrule,omitempty"`
	Location  *string  `json:"location,omitempty"`
	Color     *string  `json:"color,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type EventSetParams struct {
	// Id of the event page to write
	NodeID string `json:"node_id"`
	// local ISO YYYY-MM-DDTHH:MM (or YYYY-MM-DD all-day)
	StartAt *string `json:"start_at,omitempty"`
	// local ISO; empty = same as start
	EndAt *string `json:"end_at,omitempty"`
	// whole-day event; ignores the time
	AllDay *bool `json:"all_day,omitempty"`
	// IANA zone e.g. America/New_York
	Tz *string `json:"tz,omitempty"`
	// RFC-5545 RRULE string
	Rrule *string `json:"rrule,omitempty"`
	// free-text place or address
	Location *string `json:"location,omitempty"`
	// pigment token (red/blue/...); empty = default
	Color *string `json:"color,omitempty"`
	// user subjects assigned (like tickets)
	Assignee []string `json:"assignee,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type ExportPageParams struct {
	// Id of the target page
	PageID string `json:"page_id"`
}

type ExportPrepareParams struct {
	// Page/folder to export as a subtree; empty = whole account
	RootID *string `json:"root_id,omitempty"`
}

type ExportPrepared struct {
	Token *string `json:"token,omitempty"`
}

type ExportResult struct {
	Markdown *string `json:"markdown,omitempty"`
}

type ExportedPage struct {
	Markdown *string `json:"markdown,omitempty"`
}

type FeedState struct {
	NodeID *string `json:"node_id,omitempty"`
	Token  *string `json:"token,omitempty"`
}

type Fields struct {
	Owner     *string  `json:"owner,omitempty"`
	Type      []string `json:"type,omitempty"`
	Component []string `json:"component,omitempty"`
	Status    *string  `json:"status,omitempty"`
	Priority  *string  `json:"priority,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	Due       *string  `json:"due,omitempty"`
	Estimate  *string  `json:"estimate,omitempty"`
}

type ForkResult struct {
	ID *string `json:"id,omitempty"`
}

type ForkStatus struct {
	IsFork            *bool    `json:"is_fork,omitempty"`
	Active            *bool    `json:"active,omitempty"`
	ForkedAt          *string  `json:"forked_at,omitempty"`
	UpstreamUpdatedAt *string  `json:"upstream_updated_at,omitempty"`
	Behind            *float64 `json:"behind,omitempty"`
}

type Header struct {
	Handle     *string  `json:"handle,omitempty"`
	Bio        *string  `json:"bio,omitempty"`
	Avatar     *string  `json:"avatar,omitempty"`
	AvatarPos  *string  `json:"avatar_pos,omitempty"`
	AvatarZoom *float64 `json:"avatar_zoom,omitempty"`
	Banner     *string  `json:"banner,omitempty"`
	BannerH    *string  `json:"banner_h,omitempty"`
	BannerPos  *string  `json:"banner_pos,omitempty"`
	BannerZoom *float64 `json:"banner_zoom,omitempty"`
	Rss        *bool    `json:"rss,omitempty"`
}

type HeadingHit struct {
	PageID  *string  `json:"page_id,omitempty"`
	Title   *string  `json:"title,omitempty"`
	Heading *string  `json:"heading,omitempty"`
	Level   *float64 `json:"level,omitempty"`
}

type HeadingsResult struct {
	Hits []HeadingHit `json:"hits,omitempty"`
}

type HistoryItem struct {
	ID        *string `json:"id,omitempty"`
	Actor     *string `json:"actor,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type HistoryListParams struct {
	// Page whose revision history to read
	PageID string `json:"page_id"`
}

type HistoryRestoreParams struct {
	// Page to roll back
	PageID string `json:"page_id"`
	// Revision to restore the page to (id from History/list)
	RevID string `json:"rev_id"`
}

type HistoryRevisionParams struct {
	// Revision to preview in full (id from History/list)
	RevID string `json:"rev_id"`
}

type Hit struct {
	ID      *string `json:"id,omitempty"`
	Title   *string `json:"title,omitempty"`
	Snippet *string `json:"snippet,omitempty"`
}

type IDsResult struct {
	Ids []string `json:"ids,omitempty"`
}

type ImportFileParam struct {
	// Used for the slug + title fallback
	Name string `json:"name"`
	// Frontmatter still attached
	Content string `json:"content"`
	// Empty for root
	ParentID *string `json:"parent_id,omitempty"`
}

type ImportItemResult struct {
	Name    *string `json:"name,omitempty"`
	Title   *string `json:"title,omitempty"`
	Action  *string `json:"action,omitempty"`
	PageID  *string `json:"page_id,omitempty"`
	Matched *bool   `json:"matched,omitempty"`
}

type ImportResult struct {
	Items []ImportItemResult `json:"items,omitempty"`
}

type Info struct {
	ID             *string        `json:"id,omitempty"`
	Name           *string        `json:"name,omitempty"`
	Kind           *string        `json:"kind,omitempty"`
	Role           *string        `json:"role,omitempty"`
	Color          *string        `json:"color,omitempty"`
	Key            *string        `json:"key,omitempty"`
	CreatedAt      *string        `json:"created_at,omitempty"`
	Grant          *MemberGrant   `json:"grant,omitempty"`
	TicketStatuses []TicketStatus `json:"ticket_statuses,omitempty"`
}

type InstantiatedPage struct {
	ID          *string     `json:"id,omitempty"`
	ParentID    *string     `json:"parent_id,omitempty"`
	OwnerID     *string     `json:"owner_id,omitempty"`
	SpaceID     *string     `json:"space_id,omitempty"`
	Kind        *string     `json:"kind,omitempty"`
	AliasID     *string     `json:"alias_id,omitempty"`
	Title       *string     `json:"title,omitempty"`
	Body        *string     `json:"body,omitempty"`
	Config      *PageConfig `json:"config,omitempty"`
	Slug        *string     `json:"slug,omitempty"`
	PrevSlug    *string     `json:"prev_slug,omitempty"`
	Num         *float64    `json:"num,omitempty"`
	Encrypted   *bool       `json:"encrypted,omitempty"`
	ClientID    *string     `json:"client_id,omitempty"`
	Position    *float64    `json:"position,omitempty"`
	CreatedAt   *string     `json:"created_at,omitempty"`
	UpdatedAt   *string     `json:"updated_at,omitempty"`
	DeletedAt   *string     `json:"deleted_at,omitempty"`
	Undeletable *bool       `json:"undeletable,omitempty"`
}

type InviteLinkPreview struct {
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	Role          *string `json:"role,omitempty"`
}

type InviteLinkResult struct {
	Token   *string  `json:"token,omitempty"`
	Url     *string  `json:"url,omitempty"`
	Role    *string  `json:"role,omitempty"`
	MaxUses *float64 `json:"max_uses,omitempty"`
}

type InviteLinkView struct {
	Token     *string  `json:"token,omitempty"`
	Url       *string  `json:"url,omitempty"`
	Role      *string  `json:"role,omitempty"`
	ExpiresAt *string  `json:"expires_at,omitempty"`
	MaxUses   *float64 `json:"max_uses,omitempty"`
	Uses      *float64 `json:"uses,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type InvitesResult struct {
	Invites []PendingInvite `json:"invites,omitempty"`
}

type KeyActivityResult struct {
	Items []Row `json:"items,omitempty"`
}

type KeyInfo struct {
	ID              *string        `json:"id,omitempty"`
	Name            *string        `json:"name,omitempty"`
	Tier            *string        `json:"tier,omitempty"`
	ScopeRoot       *string        `json:"scope_root,omitempty"`
	ScopeFolders    []ScopeFolder  `json:"scope_folders,omitempty"`
	ScopeMode       *string        `json:"scope_mode,omitempty"`
	Access          *string        `json:"access,omitempty"`
	Capabilities    map[string]any `json:"capabilities,omitempty"`
	Surfaces        []string       `json:"surfaces,omitempty"`
	TokenPrefix     *string        `json:"token_prefix,omitempty"`
	LastUsedAt      *string        `json:"last_used_at,omitempty"`
	ExpiresAt       *string        `json:"expires_at,omitempty"`
	CreatedAt       *string        `json:"created_at,omitempty"`
	CreatedBy       *string        `json:"created_by,omitempty"`
	CreatedByHandle *string        `json:"created_by_handle,omitempty"`
	Mine            *bool          `json:"mine,omitempty"`
}

type KeysResult struct {
	Keys []KeyInfo `json:"keys,omitempty"`
}

type LinkedIdentity struct {
	Provider  *string `json:"provider,omitempty"`
	Label     *string `json:"label,omitempty"`
	Email     *string `json:"email,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type ListAPIKeysResult struct {
	Keys []APIKeyInfo `json:"keys,omitempty"`
}

type ListInviteLinksResult struct {
	Links []InviteLinkView `json:"links,omitempty"`
}

type LockResult struct {
	Held             *bool    `json:"held,omitempty"`
	Holder           *string  `json:"holder,omitempty"`
	HeartbeatSeconds *float64 `json:"heartbeat_seconds,omitempty"`
}

type LockStatusInfo struct {
	Locked           *bool    `json:"locked,omitempty"`
	Holder           *string  `json:"holder,omitempty"`
	HeartbeatSeconds *float64 `json:"heartbeat_seconds,omitempty"`
}

type LoginResult struct {
	Token             *string `json:"token,omitempty"`
	RefreshToken      *string `json:"refresh_token,omitempty"`
	Subject           *string `json:"subject,omitempty"`
	ExpiresAt         *string `json:"expires_at,omitempty"`
	MfaRequired       *bool   `json:"mfa_required,omitempty"`
	MfaToken          *string `json:"mfa_token,omitempty"`
	TrustToken        *string `json:"trust_token,omitempty"`
	LinkRequired      *bool   `json:"link_required,omitempty"`
	LinkToken         *string `json:"link_token,omitempty"`
	LinkEmail         *string `json:"link_email,omitempty"`
	LinkProvider      *string `json:"link_provider,omitempty"`
	LinkProviderLabel *string `json:"link_provider_label,omitempty"`
	Connected         *bool   `json:"connected,omitempty"`
	SignupRequired    *bool   `json:"signup_required,omitempty"`
	SignupToken       *string `json:"signup_token,omitempty"`
	SuggestedHandle   *string `json:"suggested_handle,omitempty"`
}

type MeCan struct {
	Read   *bool `json:"read,omitempty"`
	Write  *bool `json:"write,omitempty"`
	Manage *bool `json:"manage,omitempty"`
}

type MeResult struct {
	Subject      *string      `json:"subject,omitempty"`
	Handle       *string      `json:"handle,omitempty"`
	Email        *string      `json:"email,omitempty"`
	CreatedAt    *string      `json:"created_at,omitempty"`
	LastSeen     *string      `json:"last_seen,omitempty"`
	PlatformRole *string      `json:"platform_role,omitempty"`
	Workspace    *MeWorkspace `json:"workspace,omitempty"`
	HasPassword  *bool        `json:"has_password,omitempty"`
	AppDomain    *string      `json:"app_domain,omitempty"`
}

type MeWorkspace struct {
	ID   *string `json:"id,omitempty"`
	Role *string `json:"role,omitempty"`
	Can  *MeCan  `json:"can,omitempty"`
}

type MediaItem struct {
	Sha        *string  `json:"sha,omitempty"`
	Ext        *string  `json:"ext,omitempty"`
	Name       *string  `json:"name,omitempty"`
	Url        *string  `json:"url,omitempty"`
	Thumb      *string  `json:"thumb,omitempty"`
	Width      *float64 `json:"width,omitempty"`
	Height     *float64 `json:"height,omitempty"`
	Bytes      *float64 `json:"bytes,omitempty"`
	UploadedBy *string  `json:"uploaded_by,omitempty"`
	CreatedAt  *string  `json:"created_at,omitempty"`
}

type MemberGrant struct {
	Default *float64       `json:"default,omitempty"`
	Caps    map[string]any `json:"caps,omitempty"`
	Manage  *bool          `json:"manage,omitempty"`
}

type MemberInfo struct {
	Subject *string `json:"subject,omitempty"`
	Handle  *string `json:"handle,omitempty"`
	Role    *string `json:"role,omitempty"`
}

type MembersResult struct {
	Members []MemberInfo `json:"members,omitempty"`
}

type Mine struct {
	HomeID     *string        `json:"home_id,omitempty"`
	Visibility *string        `json:"visibility,omitempty"`
	Rss        *bool          `json:"rss,omitempty"`
	Bio        *string        `json:"bio,omitempty"`
	Avatar     *string        `json:"avatar,omitempty"`
	Width      *string        `json:"width,omitempty"`
	Accent     *string        `json:"accent,omitempty"`
	Link       *string        `json:"link,omitempty"`
	Font       *string        `json:"font,omitempty"`
	Sidebar    *string        `json:"sidebar,omitempty"`
	AvatarPos  *string        `json:"avatar_pos,omitempty"`
	AvatarZoom *float64       `json:"avatar_zoom,omitempty"`
	Banner     *string        `json:"banner,omitempty"`
	BannerH    *string        `json:"banner_h,omitempty"`
	BannerPos  *string        `json:"banner_pos,omitempty"`
	BannerZoom *float64       `json:"banner_zoom,omitempty"`
	Density    *string        `json:"density,omitempty"`
	Blocks     map[string]any `json:"blocks,omitempty"`
}

type MineResult struct {
	Shares []SharedListing `json:"shares,omitempty"`
}

type MyInvitesResult struct {
	Invites []PendingInvite `json:"invites,omitempty"`
}

type MyWorkItem struct {
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	NodeID        *string `json:"node_id,omitempty"`
	Title         *string `json:"title,omitempty"`
	Status        *string `json:"status,omitempty"`
	Priority      *string `json:"priority,omitempty"`
	Due           *string `json:"due,omitempty"`
	TypeName      *string `json:"type_name,omitempty"`
	TypeColor     *string `json:"type_color,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
}

type MyWorkResult struct {
	Items []MyWorkItem `json:"items,omitempty"`
}

type Node struct {
	ID        *string  `json:"id,omitempty"`
	ParentID  *string  `json:"parent_id,omitempty"`
	Kind      *string  `json:"kind,omitempty"`
	AliasID   *string  `json:"alias_id,omitempty"`
	Title     *string  `json:"title,omitempty"`
	Excerpt   *string  `json:"excerpt,omitempty"`
	Templated *bool    `json:"templated,omitempty"`
	Ticket    *Fields  `json:"ticket,omitempty"`
	Event     *Fields  `json:"event,omitempty"`
	Srs       *Fields  `json:"srs,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	Path      *string  `json:"path,omitempty"`
	Num       *float64 `json:"num,omitempty"`
	Width     *string  `json:"width,omitempty"`
	Unlisted  *bool    `json:"unlisted,omitempty"`
	Position  *float64 `json:"position,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}

type NotificationListing struct {
	Items []NotificationView `json:"items,omitempty"`
}

type NotificationView struct {
	ID            *string `json:"id,omitempty"`
	Kind          *string `json:"kind,omitempty"`
	SpaceID       *string `json:"space_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	NodeID        *string `json:"node_id,omitempty"`
	Title         *string `json:"title,omitempty"`
	Actor         *string `json:"actor,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
	ReadAt        *string `json:"read_at,omitempty"`
}

type OAuthIdentitiesResult struct {
	Identities []LinkedIdentity `json:"identities,omitempty"`
}

type OAuthProvidersResult struct {
	Providers        []ProviderInfo `json:"providers,omitempty"`
	PasswordDisabled *bool          `json:"password_disabled,omitempty"`
}

type OKResult struct {
	Ok *bool `json:"ok,omitempty"`
}

type OauthStartResult struct {
	Url *string `json:"url,omitempty"`
}

type OpInfo struct {
	NodeID *string `json:"node_id,omitempty"`
	TagID  *string `json:"tag_id,omitempty"`
	Op     *string `json:"op,omitempty"`
}

type OrderInfo struct {
	NodeID   *string  `json:"node_id,omitempty"`
	TagID    *string  `json:"tag_id,omitempty"`
	Position *float64 `json:"position,omitempty"`
}

type Page struct {
	ID          *string     `json:"id,omitempty"`
	ParentID    *string     `json:"parent_id,omitempty"`
	OwnerID     *string     `json:"owner_id,omitempty"`
	SpaceID     *string     `json:"space_id,omitempty"`
	Kind        *string     `json:"kind,omitempty"`
	AliasID     *string     `json:"alias_id,omitempty"`
	Title       *string     `json:"title,omitempty"`
	Body        *string     `json:"body,omitempty"`
	Config      *PageConfig `json:"config,omitempty"`
	Slug        *string     `json:"slug,omitempty"`
	PrevSlug    *string     `json:"prev_slug,omitempty"`
	Num         *float64    `json:"num,omitempty"`
	Encrypted   *bool       `json:"encrypted,omitempty"`
	ClientID    *string     `json:"client_id,omitempty"`
	Position    *float64    `json:"position,omitempty"`
	CreatedAt   *string     `json:"created_at,omitempty"`
	UpdatedAt   *string     `json:"updated_at,omitempty"`
	DeletedAt   *string     `json:"deleted_at,omitempty"`
	Undeletable *bool       `json:"undeletable,omitempty"`
}

type PageChangesParams struct {
	// RFC3339Nano updated_at watermark; empty = full pull
	Since *string `json:"since,omitempty"`
}

type PageCloneParams struct {
	// Subtree root to deep-copy
	ID string `json:"id"`
}

type PageConfig struct {
	Width       *string      `json:"width,omitempty"`
	Visibility  *string      `json:"visibility,omitempty"`
	Unlisted    *bool        `json:"unlisted,omitempty"`
	Description *string      `json:"description,omitempty"`
	Image       *string      `json:"image,omitempty"`
	SeoTitle    *string      `json:"seo_title,omitempty"`
	Noindex     *bool        `json:"noindex,omitempty"`
	Canonical   *string      `json:"canonical,omitempty"`
	Rss         *bool        `json:"rss,omitempty"`
	Bio         *string      `json:"bio,omitempty"`
	Avatar      *string      `json:"avatar,omitempty"`
	Accent      *string      `json:"accent,omitempty"`
	Link        *string      `json:"link,omitempty"`
	Font        *string      `json:"font,omitempty"`
	Sidebar     *string      `json:"sidebar,omitempty"`
	Banner      *string      `json:"banner,omitempty"`
	BannerH     *string      `json:"banner_h,omitempty"`
	BannerPos   *string      `json:"banner_pos,omitempty"`
	BannerZoom  *float64     `json:"banner_zoom,omitempty"`
	AvatarPos   *string      `json:"avatar_pos,omitempty"`
	AvatarZoom  *float64     `json:"avatar_zoom,omitempty"`
	Density     *string      `json:"density,omitempty"`
	HideFooter  *bool        `json:"hide_footer,omitempty"`
	Dashboard   *string      `json:"dashboard,omitempty"`
	Board       *BoardLayout `json:"board,omitempty"`
}

type PageCreateParams struct {
	// Empty for a root page
	ParentID *string `json:"parent_id,omitempty"`
	// Page title
	Title *string `json:"title,omitempty"`
	// Markdown body
	Body *string `json:"body,omitempty"`
	// page or folder
	Kind *string `json:"kind,omitempty"`
	// Target id when kind=alias
	AliasID *string `json:"alias_id,omitempty"`
	// Order among siblings
	Position *float64 `json:"position,omitempty"`
	// Optional offline-minted correlation id
	ClientID *string `json:"client_id,omitempty"`
}

type PageDeleteParams struct {
	// Page to delete with its subtree
	ID string `json:"id"`
}

type PageExportParams struct {
	// Page to export as markdown
	ID string `json:"id"`
}

type PageGetParams struct {
	// Page to fetch; may be a stale client id
	ID string `json:"id"`
}

type PageImportParams struct {
	// Markdown files to ingest
	Files []ImportFileParam `json:"files"`
	// replace updates a matched page (history saved); anything else creates a copy
	Mode *string `json:"mode,omitempty"`
	// Compute the create/replace plan without writing
	DryRun *bool `json:"dry_run,omitempty"`
}

type PageListPrefixParams struct {
	// Prefix path to list under; empty = the root
	Path *string `json:"path,omitempty"`
}

type PagePathOfParams struct {
	// Page whose slash path to resolve
	ID string `json:"id"`
}

type PageRefsParams struct {
	// Page ids to resolve to title and kind
	Ids []string `json:"ids"`
}

type PageResolvePathParams struct {
	// Slash slug path to resolve to a node
	Path string `json:"path"`
}

type PageUpdateParams struct {
	// Page to update
	ID string `json:"id"`
	// New page title
	Title *string `json:"title,omitempty"`
	// New markdown body
	Body *string `json:"body,omitempty"`
	// New order among siblings
	Position *float64 `json:"position,omitempty"`
	// Empty string detaches to root
	ParentID *string `json:"parent_id,omitempty"`
	// page or folder or ticket
	Kind *string `json:"kind,omitempty"`
	// Reading width and flags
	Config *PageConfig `json:"config,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type PageUpsertParams struct {
	// Slash-separated slug path; intermediates become folders. e.g. docs/api/auth
	Path string `json:"path"`
	// Display title for the leaf page (slug stays the stable key)
	Title *string `json:"title,omitempty"`
	// Markdown body
	Body *string `json:"body,omitempty"`
}

type PagesResult struct {
	Nodes []SharedNode `json:"nodes,omitempty"`
}

type PathOfResult struct {
	Path *string `json:"path,omitempty"`
}

type PendingInvite struct {
	ID            *string `json:"id,omitempty"`
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	Role          *string `json:"role,omitempty"`
	InviterHandle *string `json:"inviter_handle,omitempty"`
	InviteeHandle *string `json:"invitee_handle,omitempty"`
}

type ProfilePageData struct {
	Body *string `json:"body,omitempty"`
}

type ProviderInfo struct {
	Name  *string `json:"name,omitempty"`
	Label *string `json:"label,omitempty"`
}

type PubOp struct {
	NodeID *string `json:"node_id,omitempty"`
	TagID  *string `json:"tag_id,omitempty"`
	Op     *string `json:"op,omitempty"`
}

type PubOrder struct {
	NodeID   *string  `json:"node_id,omitempty"`
	TagID    *string  `json:"tag_id,omitempty"`
	Position *float64 `json:"position,omitempty"`
}

type PubTag struct {
	ID       *string  `json:"id,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Color    *string  `json:"color,omitempty"`
	Category *string  `json:"category,omitempty"`
	Position *float64 `json:"position,omitempty"`
}

type QueryResult struct {
	Hits []Hit `json:"hits,omitempty"`
}

type RefInfo struct {
	ID    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Kind  *string `json:"kind,omitempty"`
}

type RefsResult struct {
	Refs []RefInfo `json:"refs,omitempty"`
}

type ReportResult struct {
	Ok *bool `json:"ok,omitempty"`
}

type ResolveKeyResult struct {
	ID *string `json:"id,omitempty"`
}

type ResolvePathResult struct {
	Nodes    []SharedNode `json:"nodes,omitempty"`
	TargetID *string      `json:"target_id,omitempty"`
	Body     *string      `json:"body,omitempty"`
	Found    *bool        `json:"found,omitempty"`
}

type RestoredPage struct {
	ID          *string     `json:"id,omitempty"`
	ParentID    *string     `json:"parent_id,omitempty"`
	OwnerID     *string     `json:"owner_id,omitempty"`
	SpaceID     *string     `json:"space_id,omitempty"`
	Kind        *string     `json:"kind,omitempty"`
	AliasID     *string     `json:"alias_id,omitempty"`
	Title       *string     `json:"title,omitempty"`
	Body        *string     `json:"body,omitempty"`
	Config      *PageConfig `json:"config,omitempty"`
	Slug        *string     `json:"slug,omitempty"`
	PrevSlug    *string     `json:"prev_slug,omitempty"`
	Num         *float64    `json:"num,omitempty"`
	Encrypted   *bool       `json:"encrypted,omitempty"`
	ClientID    *string     `json:"client_id,omitempty"`
	Position    *float64    `json:"position,omitempty"`
	CreatedAt   *string     `json:"created_at,omitempty"`
	UpdatedAt   *string     `json:"updated_at,omitempty"`
	DeletedAt   *string     `json:"deleted_at,omitempty"`
	Undeletable *bool       `json:"undeletable,omitempty"`
}

type Result struct {
	Dash    map[string]any `json:"dash,omitempty"`
	Space   *SharedSpace   `json:"space,omitempty"`
	Header  *Header        `json:"header,omitempty"`
	Private *bool          `json:"private,omitempty"`
}

type RevInfo struct {
	ID        *string `json:"id,omitempty"`
	Title     *string `json:"title,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type RevisionResult struct {
	ID        *string `json:"id,omitempty"`
	Title     *string `json:"title,omitempty"`
	Body      *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type RevisionsResult struct {
	Revisions []RevInfo `json:"revisions,omitempty"`
}

type RoleView struct {
	ID    *string      `json:"id,omitempty"`
	Scope *string      `json:"scope,omitempty"`
	Name  *string      `json:"name,omitempty"`
	Grant *MemberGrant `json:"grant,omitempty"`
}

type RolesResult struct {
	Roles []RoleView `json:"roles,omitempty"`
}

type RosterResult struct {
	Names            []string `json:"names,omitempty"`
	Count            *float64 `json:"count,omitempty"`
	HeartbeatSeconds *float64 `json:"heartbeat_seconds,omitempty"`
}

type Row struct {
	Action *string        `json:"action,omitempty"`
	Count  *float64       `json:"count,omitempty"`
	LastAt *string        `json:"last_at,omitempty"`
	Meta   map[string]any `json:"meta,omitempty"`
}

type SRS struct {
	Subject      *string  `json:"subject,omitempty"`
	NodeID       *string  `json:"node_id,omitempty"`
	SpaceID      *string  `json:"space_id,omitempty"`
	Due          *string  `json:"due,omitempty"`
	Ease         *float64 `json:"ease,omitempty"`
	Interval     *float64 `json:"interval,omitempty"`
	Reps         *float64 `json:"reps,omitempty"`
	Lapses       *float64 `json:"lapses,omitempty"`
	LastReviewed *string  `json:"last_reviewed,omitempty"`
	UpdatedAt    *string  `json:"updated_at,omitempty"`
	DeletedAt    *string  `json:"deleted_at,omitempty"`
}

type ScopeFolder struct {
	ID    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
}

type SearchQueryParams struct {
	// Full-text search over your pages
	Query *string `json:"query,omitempty"`
	// Max hits to return; defaults to 25 and caps at 100
	Limit *float64 `json:"limit,omitempty"`
	// Only these node kinds; up to 8
	Kinds []string `json:"kinds,omitempty"`
	// Folder id to search within its subtree
	ScopeRoot *string `json:"scope_root,omitempty"`
}

type SearchResult struct {
	Nodes []SharedNode `json:"nodes,omitempty"`
}

type SetNameResult struct {
	Ok *bool `json:"ok,omitempty"`
}

type SettingsSnapshot struct {
	Data map[string]any `json:"data,omitempty"`
}

type ShareCreateParams struct {
	// Page to publish as a public share
	PageID string `json:"page_id"`
	// Optional; protects the share on create
	Password *string `json:"password,omitempty"`
	// Optional; permit forking on create
	AllowFork *bool `json:"allow_fork,omitempty"`
	// Optional; expose markdown source + tree manifest on create
	AllowRaw *bool `json:"allow_raw,omitempty"`
	// Optional; let logged-in visitors annotate on create
	AllowAnnotations *bool `json:"allow_annotations,omitempty"`
}

type ShareForkInfoParams struct {
	// Forked page to check upstream drift for
	RootID string `json:"root_id"`
}

type ShareForkParams struct {
	// Public share token to fork from
	Token string `json:"token"`
	// The caller's folder to fork into; empty = root
	ParentID *string `json:"parent_id,omitempty"`
	// Required to fork a password-protected share
	Lease *string `json:"lease,omitempty"`
	// Which workspace to fork into; empty = active
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

type ShareGetParams struct {
	// Public share token to resolve
	Token string `json:"token"`
	// Lease token from Share/unlock (protected shares)
	Lease *string `json:"lease,omitempty"`
}

type ShareResult struct {
	Shared           *bool   `json:"shared,omitempty"`
	Token            *string `json:"token,omitempty"`
	AllowFork        *bool   `json:"allow_fork,omitempty"`
	AllowRaw         *bool   `json:"allow_raw,omitempty"`
	AllowAnnotations *bool   `json:"allow_annotations,omitempty"`
	AllowRss         *bool   `json:"allow_rss,omitempty"`
	ExportFormats    *string `json:"export_formats,omitempty"`
	Protected        *bool   `json:"protected,omitempty"`
}

type ShareRevokeParams struct {
	// Shared page to target
	PageID string `json:"page_id"`
}

type ShareSetAnnotationsParams struct {
	// Shared page to toggle annotations on
	PageID string `json:"page_id"`
	// Let logged-in visitors annotate
	Allow *bool `json:"allow,omitempty"`
}

type ShareSetForkableParams struct {
	// Shared page to toggle forking on
	PageID string `json:"page_id"`
	// Permit visitors to fork the share
	Allow *bool `json:"allow,omitempty"`
}

type ShareSetPasswordParams struct {
	// Shared page to protect or unprotect
	PageID string `json:"page_id"`
	// Empty removes protection
	Password *string `json:"password,omitempty"`
}

type ShareSetRSSParams struct {
	// Shared folder to toggle its RSS feed
	PageID string `json:"page_id"`
	// Publish the share RSS feed
	Allow *bool `json:"allow,omitempty"`
}

type ShareStatusParams struct {
	// Shared page to target
	PageID string `json:"page_id"`
}

type ShareUnlockParams struct {
	// Protected share token to unlock
	Token string `json:"token"`
	// Password proving access to the share
	Password string `json:"password"`
}

type SharedListing struct {
	PageID    *string `json:"page_id,omitempty"`
	Token     *string `json:"token,omitempty"`
	AllowFork *bool   `json:"allow_fork,omitempty"`
	Title     *string `json:"title,omitempty"`
	Kind      *string `json:"kind,omitempty"`
}

type SharedNode struct {
	ID          *string      `json:"id,omitempty"`
	ParentID    *string      `json:"parent_id,omitempty"`
	Kind        *string      `json:"kind,omitempty"`
	AliasID     *string      `json:"alias_id,omitempty"`
	Slug        *string      `json:"slug,omitempty"`
	PrevSlug    *string      `json:"prev_slug,omitempty"`
	Num         *float64     `json:"num,omitempty"`
	Title       *string      `json:"title,omitempty"`
	Body        *string      `json:"body,omitempty"`
	Excerpt     *string      `json:"excerpt,omitempty"`
	Config      *PageConfig  `json:"config,omitempty"`
	Tint        *string      `json:"tint,omitempty"`
	Status      *string      `json:"status,omitempty"`
	Priority    *string      `json:"priority,omitempty"`
	Due         *string      `json:"due,omitempty"`
	StartAt     *string      `json:"start_at,omitempty"`
	EndAt       *string      `json:"end_at,omitempty"`
	AllDay      *bool        `json:"all_day,omitempty"`
	Tz          *string      `json:"tz,omitempty"`
	Rrule       *string      `json:"rrule,omitempty"`
	Location    *string      `json:"location,omitempty"`
	Position    *float64     `json:"position,omitempty"`
	CreatedAt   *string      `json:"created_at,omitempty"`
	UpdatedAt   *string      `json:"updated_at,omitempty"`
	ViewMatches []SharedNode `json:"view_matches,omitempty"`
	MoreKids    *bool        `json:"more_kids,omitempty"`
	MoreCount   *float64     `json:"more_count,omitempty"`
	Path        *string      `json:"path,omitempty"`
}

type SharedSpace struct {
	RootID           *string      `json:"root_id,omitempty"`
	AllowFork        *bool        `json:"allow_fork,omitempty"`
	AllowRaw         *bool        `json:"allow_raw,omitempty"`
	AllowRss         *bool        `json:"allow_rss,omitempty"`
	AllowAnnotations *bool        `json:"allow_annotations,omitempty"`
	ExportFormats    *string      `json:"export_formats,omitempty"`
	Key              *string      `json:"key,omitempty"`
	Nodes            []SharedNode `json:"nodes,omitempty"`
	Protected        *bool        `json:"protected,omitempty"`
	RenderMode       *string      `json:"render_mode,omitempty"`
	ShowForkBadge    *bool        `json:"show_fork_badge,omitempty"`
}

type SharesResult struct {
	Shares []SharedListing `json:"shares,omitempty"`
}

type SrsDeleteAck struct {
	NodeID *string `json:"node_id,omitempty"`
	Ok     *bool   `json:"ok,omitempty"`
}

type Tag struct {
	ID       *string  `json:"id,omitempty"`
	OwnerID  *string  `json:"owner_id,omitempty"`
	SpaceID  *string  `json:"space_id,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Color    *string  `json:"color,omitempty"`
	Category *string  `json:"category,omitempty"`
	Position *float64 `json:"position,omitempty"`
}

type TagCatalogResult struct {
	Tags   []Tag       `json:"tags,omitempty"`
	Ops    []OpInfo    `json:"ops,omitempty"`
	Orders []OrderInfo `json:"orders,omitempty"`
}

type TagClearNodeParams struct {
	// Node whose override is removed
	NodeID *string `json:"node_id,omitempty"`
	// Tag to revert to inherited
	TagID string `json:"tag_id"`
}

type TagCreateParams struct {
	// New tag label
	Name string `json:"name"`
	// default|red|orange|amber|green|blue|violet
	Color *string `json:"color,omitempty"`
	// facet like type; empty = plain label
	Category *string `json:"category,omitempty"`
}

type TagDeleteParams struct {
	// Tag to delete; drops its cascade ops
	ID string `json:"id"`
}

type TagReorderGlobalParams struct {
	// Tag ids in the new global order
	TagIds []string `json:"tag_ids"`
}

type TagReorderNodeParams struct {
	// Node whose local tag order to set
	NodeID string `json:"node_id"`
	// Tag ids in local order; empty clears the override
	TagIds []string `json:"tag_ids,omitempty"`
}

type TagSetNodeParams struct {
	// Empty for the global level
	NodeID *string `json:"node_id,omitempty"`
	// Tag to add or remove at the node
	TagID string `json:"tag_id"`
	// add or remove
	Op string `json:"op"`
}

type TagSetNodeTagsParams struct {
	// Empty for the global level
	NodeID *string `json:"node_id,omitempty"`
	// Tag ids the op applies to at once
	TagIds []string `json:"tag_ids"`
	// add or remove
	Op string `json:"op"`
}

type TagState struct {
	Tags   []PubTag   `json:"tags,omitempty"`
	Ops    []PubOp    `json:"ops,omitempty"`
	Orders []PubOrder `json:"orders,omitempty"`
}

type TagUpdateParams struct {
	// Tag to rename or recolor
	ID string `json:"id"`
	// New tag label
	Name string `json:"name"`
	// New pigment; unknown falls back to default
	Color *string `json:"color,omitempty"`
}

type Template struct {
	ID        *string  `json:"id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	Name      *string  `json:"name,omitempty"`
	Body      *string  `json:"body,omitempty"`
	Meta      *string  `json:"meta,omitempty"`
	Seq       *float64 `json:"seq,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}

type TemplateCreateParams struct {
	// New template name
	Name string `json:"name"`
	// Markdown skeleton with inline {field|type} tokens
	Body *string `json:"body,omitempty"`
	// JSON meta such as ticket defaults
	Meta *string `json:"meta,omitempty"`
}

type TemplateDeleteParams struct {
	// Template to delete
	ID string `json:"id"`
}

type TemplateDeleted struct {
	ID *string `json:"id,omitempty"`
	Ok *bool   `json:"ok,omitempty"`
}

type TemplateGetParams struct {
	// Template to fetch
	ID string `json:"id"`
}

type TemplateInstantiateParams struct {
	// Template to instantiate
	TemplateID string `json:"template_id"`
	// Folder to create the page under; empty = root
	ParentID *string `json:"parent_id,omitempty"`
	// page or ticket (default page)
	Kind *string `json:"kind,omitempty"`
	// Title for the new page
	Title *string `json:"title,omitempty"`
	// Values filling the {field|type} tokens by name
	Values map[string]any `json:"values,omitempty"`
}

type TemplateList struct {
	Templates []Template `json:"templates,omitempty"`
}

type TemplatePreview struct {
	Name          *string  `json:"name,omitempty"`
	StructureOnly *bool    `json:"structure_only,omitempty"`
	NodeCount     *float64 `json:"node_count,omitempty"`
	Outline       []string `json:"outline,omitempty"`
}

type TemplateUpdateParams struct {
	// Template to edit
	ID string `json:"id"`
	// New template name
	Name string `json:"name"`
	// Markdown skeleton with inline {field|type} tokens
	Body *string `json:"body,omitempty"`
	// JSON meta such as ticket defaults
	Meta *string `json:"meta,omitempty"`
}

type Ticket struct {
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	Owner     *string  `json:"owner,omitempty"`
	Type      []string `json:"type,omitempty"`
	Component []string `json:"component,omitempty"`
	Status    *string  `json:"status,omitempty"`
	Priority  *string  `json:"priority,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	Due       *string  `json:"due,omitempty"`
	Estimate  *string  `json:"estimate,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
	DeletedAt *string  `json:"deleted_at,omitempty"`
}

type TicketChangesParams struct {
	// RFC3339Nano cursor; empty = full
	Since *string `json:"since,omitempty"`
}

type TicketDeleteAck struct {
	NodeID *string `json:"node_id,omitempty"`
	Ok     *bool   `json:"ok,omitempty"`
}

type TicketDeleteParams struct {
	// id of the target ticket page
	NodeID string `json:"node_id"`
}

type TicketFeed struct {
	Tickets    []Ticket `json:"tickets,omitempty"`
	Tombstones []string `json:"tombstones,omitempty"`
	Cursor     *string  `json:"cursor,omitempty"`
}

type TicketGetParams struct {
	// id of the target ticket page
	NodeID string `json:"node_id"`
}

type TicketHistoryParams struct {
	// id of the target ticket page
	NodeID string `json:"node_id"`
}

type TicketPatchParams struct {
	// id of the target ticket page
	NodeID string `json:"node_id"`
	// single responsible user id
	Owner *string `json:"owner,omitempty"`
	// tag ids (category type)
	Type []string `json:"type,omitempty"`
	// tag ids (category component)
	Component []string `json:"component,omitempty"`
	// todo | doing | review | done | cancelled
	Status *string `json:"status,omitempty"`
	// low | med | high
	Priority *string `json:"priority,omitempty"`
	// user ids (a ticket can have many)
	Assignee []string `json:"assignee,omitempty"`
	// ISO date
	Due *string `json:"due,omitempty"`
	// free-text effort/size estimate
	Estimate *string `json:"estimate,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type TicketRestoreParams struct {
	// id of the target ticket page
	NodeID string `json:"node_id"`
	// id of the revision to restore
	RevID string `json:"rev_id"`
}

type TicketResult struct {
	Ticket *string  `json:"ticket,omitempty"`
	Url    *string  `json:"url,omitempty"`
	Ttl    *float64 `json:"ttl,omitempty"`
}

type TicketRevision struct {
	ID        *string  `json:"id,omitempty"`
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	Owner     *string  `json:"owner,omitempty"`
	Type      []string `json:"type,omitempty"`
	Component []string `json:"component,omitempty"`
	Status    *string  `json:"status,omitempty"`
	Priority  *string  `json:"priority,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	Due       *string  `json:"due,omitempty"`
	Estimate  *string  `json:"estimate,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type TicketSetParams struct {
	// id of the target ticket page
	NodeID string `json:"node_id"`
	// single responsible user id
	Owner *string `json:"owner,omitempty"`
	// tag ids (category type)
	Type []string `json:"type,omitempty"`
	// tag ids (category component)
	Component []string `json:"component,omitempty"`
	// todo | doing | review | done | cancelled
	Status *string `json:"status,omitempty"`
	// low med or high
	Priority *string `json:"priority,omitempty"`
	// user ids (a ticket can have many)
	Assignee []string `json:"assignee,omitempty"`
	// ISO date
	Due *string `json:"due,omitempty"`
	// free-text effort/size estimate
	Estimate *string `json:"estimate,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type TicketStatus struct {
	ID    *string `json:"id,omitempty"`
	Name  *string `json:"name,omitempty"`
	Color *string `json:"color,omitempty"`
}

type TicketStatusParam struct {
	// stable status slug (lowercase)
	ID string `json:"id"`
	// display name for the column
	Name string `json:"name"`
	// pigment name (red|orange|amber|green|blue|violet); empty = default
	Color *string `json:"color,omitempty"`
}

type TocResult struct {
	Nodes []SharedNode `json:"nodes,omitempty"`
}

type TopTagsResult struct {
	Counts map[string]any `json:"counts,omitempty"`
}

type TreeResult struct {
	Pages []Node `json:"pages,omitempty"`
}

type UnlockResult struct {
	Lease     *string `json:"lease,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

type UploadDeleteAck struct {
	Ok *bool `json:"ok,omitempty"`
}

type UploadListing struct {
	Items []MediaItem `json:"items,omitempty"`
}

type UploadPrepared struct {
	Ticket *string `json:"ticket,omitempty"`
	Url    *string `json:"url,omitempty"`
}

type UploadStatusInfo struct {
	Enabled  *bool    `json:"enabled,omitempty"`
	MaxBytes *float64 `json:"max_bytes,omitempty"`
	MaxDim   *float64 `json:"max_dim,omitempty"`
}

type UsageKind struct {
	Kind  *string  `json:"kind,omitempty"`
	Count *float64 `json:"count,omitempty"`
}

type UsageResult struct {
	Used      *float64    `json:"used,omitempty"`
	Limit     *float64    `json:"limit,omitempty"`
	Unlimited *bool       `json:"unlimited,omitempty"`
	Folders   *float64    `json:"folders,omitempty"`
	Kinds     []UsageKind `json:"kinds,omitempty"`
}

type WorkspaceCreateParams struct {
	// Display name for the new space
	Name string `json:"name"`
	// Optional workspace template to scaffold from
	Template *string `json:"template,omitempty"`
	// Optional shared-template token to scaffold from
	TemplateToken *string `json:"template_token,omitempty"`
}

type WorkspaceListing struct {
	Workspaces []Info  `json:"workspaces,omitempty"`
	Current    *string `json:"current,omitempty"`
}

type WorkspaceRenameParams struct {
	// Workspace to rename
	ID string `json:"id"`
	// New display name for the space
	Name string `json:"name"`
}

type WorkspaceSetColorParams struct {
	// Workspace to tint
	ID string `json:"id"`
	// red|orange|amber|green|blue|violet; empty = default
	Color *string `json:"color,omitempty"`
}

type WorkspaceTemplate struct {
	ID            *string        `json:"id,omitempty"`
	Name          *string        `json:"name,omitempty"`
	Blueprint     map[string]any `json:"blueprint,omitempty"`
	StructureOnly *bool          `json:"structure_only,omitempty"`
	ShareToken    *string        `json:"share_token,omitempty"`
	CreatedAt     *string        `json:"created_at,omitempty"`
	UpdatedAt     *string        `json:"updated_at,omitempty"`
	Builtin       *bool          `json:"builtin,omitempty"`
}

type WorkspaceTemplateDeleteParams struct {
	// Template to delete
	ID string `json:"id"`
}

type WorkspaceTemplateSaveParams struct {
	// Display name for the saved blueprint
	Name string `json:"name"`
	// Copy the tree + layout but drop bodies
	StructureOnly *bool `json:"structure_only,omitempty"`
	// Snapshot this space instead of the active one
	Workspace *string `json:"workspace,omitempty"`
}
