// Code generated by cmdgen; DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"

	"github.com/dakolli/mininote-cli/client"

	"github.com/spf13/cobra"
)

// registerServiceCommands attaches one cobra command per RPC service to root,
// with one subcommand per RPC method. getClient is invoked inside each RunE so
// the resolved base URL and token are always read fresh from the root flags
// and config file on every invocation.
func registerServiceCommands(root *cobra.Command, getClient func() (*client.Client, error)) {
	{
		service := &cobra.Command{
			Use:     "annotation",
			GroupID: "services",
			Short:   "Annotation service",
		}
		service.AddCommand(cmdAnnotationAdd(getClient))
		service.AddCommand(cmdAnnotationChanges(getClient))
		service.AddCommand(cmdAnnotationDelete(getClient))
		service.AddCommand(cmdAnnotationEdit(getClient))
		service.AddCommand(cmdAnnotationGet(getClient))
		service.AddCommand(cmdAnnotationList(getClient))
		service.AddCommand(cmdAnnotationSetResolved(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "calFeed",
			GroupID: "services",
			Short:   "Cal Feed service",
		}
		service.AddCommand(cmdCalFeedCreate(getClient))
		service.AddCommand(cmdCalFeedRevoke(getClient))
		service.AddCommand(cmdCalFeedStatus(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "comment",
			GroupID: "services",
			Short:   "Comment service",
		}
		service.AddCommand(cmdCommentAdd(getClient))
		service.AddCommand(cmdCommentDelete(getClient))
		service.AddCommand(cmdCommentEdit(getClient))
		service.AddCommand(cmdCommentList(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "event",
			GroupID: "services",
			Short:   "Event service",
		}
		service.AddCommand(cmdEventChanges(getClient))
		service.AddCommand(cmdEventDelete(getClient))
		service.AddCommand(cmdEventGet(getClient))
		service.AddCommand(cmdEventHistory(getClient))
		service.AddCommand(cmdEventPatch(getClient))
		service.AddCommand(cmdEventRestore(getClient))
		service.AddCommand(cmdEventSet(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "export",
			GroupID: "services",
			Short:   "Export service",
		}
		service.AddCommand(cmdExportPage(getClient))
		service.AddCommand(cmdExportPrepare(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "history",
			GroupID: "services",
			Short:   "History service",
		}
		service.AddCommand(cmdHistoryList(getClient))
		service.AddCommand(cmdHistoryRestore(getClient))
		service.AddCommand(cmdHistoryRevision(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "page",
			GroupID: "services",
			Short:   "Page service",
		}
		service.AddCommand(cmdPageChanges(getClient))
		service.AddCommand(cmdPageClone(getClient))
		service.AddCommand(cmdPageCreate(getClient))
		service.AddCommand(cmdPageDelete(getClient))
		service.AddCommand(cmdPageExport(getClient))
		service.AddCommand(cmdPageExportAll(getClient))
		service.AddCommand(cmdPageGet(getClient))
		service.AddCommand(cmdPageImport(getClient))
		service.AddCommand(cmdPageListPrefix(getClient))
		service.AddCommand(cmdPagePathOf(getClient))
		service.AddCommand(cmdPageRefs(getClient))
		service.AddCommand(cmdPageResolvePath(getClient))
		service.AddCommand(cmdPageTree(getClient))
		service.AddCommand(cmdPageUpdate(getClient))
		service.AddCommand(cmdPageUpsert(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "search",
			GroupID: "services",
			Short:   "Search service",
		}
		service.AddCommand(cmdSearchQuery(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "share",
			GroupID: "services",
			Short:   "Share service",
		}
		service.AddCommand(cmdShareApiDocs(getClient))
		service.AddCommand(cmdShareCreate(getClient))
		service.AddCommand(cmdShareFork(getClient))
		service.AddCommand(cmdShareForkInfo(getClient))
		service.AddCommand(cmdShareGet(getClient))
		service.AddCommand(cmdShareHomepage(getClient))
		service.AddCommand(cmdShareMine(getClient))
		service.AddCommand(cmdShareRevoke(getClient))
		service.AddCommand(cmdShareSetAnnotations(getClient))
		service.AddCommand(cmdShareSetForkable(getClient))
		service.AddCommand(cmdShareSetPassword(getClient))
		service.AddCommand(cmdShareSetRSS(getClient))
		service.AddCommand(cmdShareStatus(getClient))
		service.AddCommand(cmdShareUnlock(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "tag",
			GroupID: "services",
			Short:   "Tag service",
		}
		service.AddCommand(cmdTagClearNode(getClient))
		service.AddCommand(cmdTagCreate(getClient))
		service.AddCommand(cmdTagDelete(getClient))
		service.AddCommand(cmdTagList(getClient))
		service.AddCommand(cmdTagReorderGlobal(getClient))
		service.AddCommand(cmdTagReorderNode(getClient))
		service.AddCommand(cmdTagSetNode(getClient))
		service.AddCommand(cmdTagSetNodeTags(getClient))
		service.AddCommand(cmdTagUpdate(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "template",
			GroupID: "services",
			Short:   "Template service",
		}
		service.AddCommand(cmdTemplateInstantiate(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "ticket",
			GroupID: "services",
			Short:   "Ticket service",
		}
		service.AddCommand(cmdTicketChanges(getClient))
		service.AddCommand(cmdTicketDelete(getClient))
		service.AddCommand(cmdTicketGet(getClient))
		service.AddCommand(cmdTicketHistory(getClient))
		service.AddCommand(cmdTicketPatch(getClient))
		service.AddCommand(cmdTicketRestore(getClient))
		service.AddCommand(cmdTicketSet(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "workspace",
			GroupID: "services",
			Short:   "Workspace service",
		}
		service.AddCommand(cmdWorkspaceForKey(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:     "workspaceTemplate",
			GroupID: "services",
			Short:   "Workspace Template service",
		}
		service.AddCommand(cmdWorkspaceTemplateDelete(getClient))
		service.AddCommand(cmdWorkspaceTemplateList(getClient))
		service.AddCommand(cmdWorkspaceTemplateSave(getClient))
		root.AddCommand(service)
	}
}

// cmdAnnotationAdd builds the cobra command for the AnnotationAdd RPC.
func cmdAnnotationAdd(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pBody string
	var pAnchorType string
	var pAnchorQuote string
	var pAnchorPrefix string
	var pAnchorSuffix string
	var pAnchorRev string
	var pColor string
	var pParentID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "add",
		Short: "Add",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("body") {
				pBody = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("body") && pBody == "" {
				return fmt.Errorf("required flag --body (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationAddParams
			req.NodeID = pNodeID
			req.Body = pBody
			if cmd.Flags().Changed("anchor_type") || pAnchorType != "" {
				req.AnchorType = &pAnchorType
			}
			if cmd.Flags().Changed("anchor_quote") || pAnchorQuote != "" {
				req.AnchorQuote = &pAnchorQuote
			}
			if cmd.Flags().Changed("anchor_prefix") || pAnchorPrefix != "" {
				req.AnchorPrefix = &pAnchorPrefix
			}
			if cmd.Flags().Changed("anchor_suffix") || pAnchorSuffix != "" {
				req.AnchorSuffix = &pAnchorSuffix
			}
			if cmd.Flags().Changed("anchor_rev") || pAnchorRev != "" {
				req.AnchorRev = &pAnchorRev
			}
			if cmd.Flags().Changed("color") || pColor != "" {
				req.Color = &pColor
			}
			if cmd.Flags().Changed("parent_id") || pParentID != "" {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("token") || pToken != "" {
				req.Token = &pToken
			}
			resp, err := c.AnnotationAdd(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the node the annotation anchors to")
	flags.StringVarP(&pBody, "body", "b", "", "Annotation text (markdown)")
	flags.StringVarP(&pAnchorType, "anchor_type", "a", "", "text quote-selector (default) or block media element")
	flags.StringVarP(&pAnchorQuote, "anchor_quote", "c", "", "The exact selected text — OR the media src for a block anchor")
	flags.StringVarP(&pAnchorPrefix, "anchor_prefix", "o", "", "~32 chars before the quote")
	flags.StringVarP(&pAnchorSuffix, "anchor_suffix", "r", "", "~32 chars after the quote")
	flags.StringVarP(&pAnchorRev, "anchor_rev", "e", "", "Page revision id at creation (orphan deep-link)")
	flags.StringVarP(&pColor, "color", "l", "", "pigment red/orange/amber/green/blue/violet (root note)")
	flags.StringVarP(&pParentID, "parent_id", "p", "", "For a threaded reply")
	flags.StringVar(&pToken, "token", "", "Present when annotating via a share (visitor path)")
	return cmd
}

// cmdAnnotationChanges builds the cobra command for the AnnotationChanges RPC.
func cmdAnnotationChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("since") {
				pSince = args[0]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationChangesParams
			if cmd.Flags().Changed("since") || pSince != "" {
				req.Since = &pSince
			}
			resp, err := c.AnnotationChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pSince, "since", "s", "", "RFC3339Nano cursor; empty = full")
	return cmd
}

// cmdAnnotationDelete builds the cobra command for the AnnotationDelete RPC.
func cmdAnnotationDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("token") {
				pToken = args[1]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationDeleteParams
			req.ID = pID
			if cmd.Flags().Changed("token") || pToken != "" {
				req.Token = &pToken
			}
			resp, err := c.AnnotationDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Id of the annotation to delete")
	flags.StringVarP(&pToken, "token", "o", "", "Present when deleting via a share (visitor path)")
	return cmd
}

// cmdAnnotationEdit builds the cobra command for the AnnotationEdit RPC.
func cmdAnnotationEdit(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pBody string
	var pToken string
	cmd := &cobra.Command{
		Use:   "edit",
		Short: "Edit",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("body") {
				pBody = args[1]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("body") && pBody == "" {
				return fmt.Errorf("required flag --body (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationEditParams
			req.ID = pID
			req.Body = pBody
			if cmd.Flags().Changed("token") || pToken != "" {
				req.Token = &pToken
			}
			resp, err := c.AnnotationEdit(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Id of the annotation to edit")
	flags.StringVarP(&pBody, "body", "b", "", "Replacement annotation body (markdown)")
	flags.StringVarP(&pToken, "token", "o", "", "Present when editing via a share (visitor path)")
	return cmd
}

// cmdAnnotationGet builds the cobra command for the AnnotationGet RPC.
func cmdAnnotationGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("token") {
				pToken = args[1]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationGetParams
			req.ID = pID
			if cmd.Flags().Changed("token") || pToken != "" {
				req.Token = &pToken
			}
			resp, err := c.AnnotationGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Id of the annotation to fetch")
	flags.StringVarP(&pToken, "token", "o", "", "Present when reading via a share (visitor path)")
	return cmd
}

// cmdAnnotationList builds the cobra command for the AnnotationList RPC.
func cmdAnnotationList(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("token") {
				pToken = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationListParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("token") || pToken != "" {
				req.Token = &pToken
			}
			resp, err := c.AnnotationList(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Node whose annotations to list")
	flags.StringVarP(&pToken, "token", "o", "", "Present when listing via a share (visitor path)")
	return cmd
}

// cmdAnnotationSetResolved builds the cobra command for the AnnotationSetResolved RPC.
func cmdAnnotationSetResolved(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pResolved bool
	var pToken string
	cmd := &cobra.Command{
		Use:   "setResolved",
		Short: "Set resolved",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("token") {
				pToken = args[1]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationSetResolvedParams
			req.ID = pID
			if cmd.Flags().Changed("resolved") {
				req.Resolved = &pResolved
			}
			if cmd.Flags().Changed("token") || pToken != "" {
				req.Token = &pToken
			}
			resp, err := c.AnnotationSetResolved(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Id of the annotation to resolve or reopen")
	flags.BoolVarP(&pResolved, "resolved", "r", false, "true to resolve; false to reopen")
	flags.StringVarP(&pToken, "token", "o", "", "Present when resolving via a share (visitor path)")
	return cmd
}

// cmdCalFeedCreate builds the cobra command for the CalFeedCreate RPC.
func cmdCalFeedCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CalFeedCreateParams
			req.NodeID = pNodeID
			resp, err := c.CalFeedCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Calendar node the subscribe feed is for")
	return cmd
}

// cmdCalFeedRevoke builds the cobra command for the CalFeedRevoke RPC.
func cmdCalFeedRevoke(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "revoke",
		Short: "Revoke",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CalFeedRevokeParams
			req.NodeID = pNodeID
			resp, err := c.CalFeedRevoke(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Calendar node the subscribe feed is for")
	return cmd
}

// cmdCalFeedStatus builds the cobra command for the CalFeedStatus RPC.
func cmdCalFeedStatus(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Status",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CalFeedStatusParams
			req.NodeID = pNodeID
			resp, err := c.CalFeedStatus(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Calendar node the subscribe feed is for")
	return cmd
}

// cmdCommentAdd builds the cobra command for the CommentAdd RPC.
func cmdCommentAdd(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pBody string
	var pParentID string
	cmd := &cobra.Command{
		Use:   "add",
		Short: "Add",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("body") {
				pBody = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("body") && pBody == "" {
				return fmt.Errorf("required flag --body (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentAddParams
			req.NodeID = pNodeID
			req.Body = pBody
			if cmd.Flags().Changed("parent_id") || pParentID != "" {
				req.ParentID = &pParentID
			}
			resp, err := c.CommentAdd(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the node to comment on")
	flags.StringVarP(&pBody, "body", "b", "", "Comment text (markdown)")
	flags.StringVarP(&pParentID, "parent_id", "p", "", "For a threaded reply")
	return cmd
}

// cmdCommentDelete builds the cobra command for the CommentDelete RPC.
func cmdCommentDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentDeleteParams
			req.ID = pID
			resp, err := c.CommentDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Id of the comment to delete")
	return cmd
}

// cmdCommentEdit builds the cobra command for the CommentEdit RPC.
func cmdCommentEdit(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pBody string
	cmd := &cobra.Command{
		Use:   "edit",
		Short: "Edit",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("body") {
				pBody = args[1]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("body") && pBody == "" {
				return fmt.Errorf("required flag --body (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentEditParams
			req.ID = pID
			req.Body = pBody
			resp, err := c.CommentEdit(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Id of the comment to edit")
	flags.StringVarP(&pBody, "body", "b", "", "Replacement comment body (markdown)")
	return cmd
}

// cmdCommentList builds the cobra command for the CommentList RPC.
func cmdCommentList(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentListParams
			req.NodeID = pNodeID
			resp, err := c.CommentList(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Node whose comments to list")
	return cmd
}

// cmdEventChanges builds the cobra command for the EventChanges RPC.
func cmdEventChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("since") {
				pSince = args[0]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventChangesParams
			if cmd.Flags().Changed("since") || pSince != "" {
				req.Since = &pSince
			}
			resp, err := c.EventChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pSince, "since", "s", "", "RFC3339Nano cursor; empty = full")
	return cmd
}

// cmdEventDelete builds the cobra command for the EventDelete RPC.
func cmdEventDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventDeleteParams
			req.NodeID = pNodeID
			resp, err := c.EventDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the event page whose metadata to drop")
	return cmd
}

// cmdEventGet builds the cobra command for the EventGet RPC.
func cmdEventGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventGetParams
			req.NodeID = pNodeID
			resp, err := c.EventGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the event page")
	return cmd
}

// cmdEventHistory builds the cobra command for the EventHistory RPC.
func cmdEventHistory(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "history",
		Short: "History",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventHistoryParams
			req.NodeID = pNodeID
			resp, err := c.EventHistory(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the event page")
	return cmd
}

// cmdEventPatch builds the cobra command for the EventPatch RPC.
func cmdEventPatch(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pStartAt string
	var pEndAt string
	var pAllDay bool
	var pTz string
	var pRrule string
	var pLocation string
	var pColor string
	var pAssignee []string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "patch",
		Short: "Patch",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("start_at") {
				pStartAt = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventPatchParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("start_at") || pStartAt != "" {
				req.StartAt = &pStartAt
			}
			if cmd.Flags().Changed("end_at") || pEndAt != "" {
				req.EndAt = &pEndAt
			}
			if cmd.Flags().Changed("all_day") {
				req.AllDay = &pAllDay
			}
			if cmd.Flags().Changed("tz") || pTz != "" {
				req.Tz = &pTz
			}
			if cmd.Flags().Changed("rrule") || pRrule != "" {
				req.Rrule = &pRrule
			}
			if cmd.Flags().Changed("location") || pLocation != "" {
				req.Location = &pLocation
			}
			if cmd.Flags().Changed("color") || pColor != "" {
				req.Color = &pColor
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("base_updated_at") || pBaseUpdatedAt != "" {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.EventPatch(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the event page to patch")
	flags.StringVarP(&pStartAt, "start_at", "s", "", "local ISO start; omit to leave untouched")
	flags.StringVarP(&pEndAt, "end_at", "e", "", "local ISO end; omit to leave untouched")
	flags.BoolVarP(&pAllDay, "all_day", "a", false, "whole-day flag; omit to leave untouched")
	flags.StringVarP(&pTz, "tz", "z", "", "IANA zone; omit to leave untouched")
	flags.StringVarP(&pRrule, "rrule", "r", "", "RFC-5545 RRULE; omit to leave untouched")
	flags.StringVarP(&pLocation, "location", "l", "", "place or address; omit to leave untouched")
	flags.StringVarP(&pColor, "color", "c", "", "pigment token; omit to leave untouched")
	flags.StringSliceVarP(&pAssignee, "assignee", "i", nil, "assigned user subjects; omit to leave untouched")
	flags.StringVarP(&pBaseUpdatedAt, "base_updated_at", "b", "", "Optimistic-concurrency token")
	return cmd
}

// cmdEventRestore builds the cobra command for the EventRestore RPC.
func cmdEventRestore(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pRevID string
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("rev_id") {
				pRevID = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("rev_id") && pRevID == "" {
				return fmt.Errorf("required flag --rev_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventRestoreParams
			req.NodeID = pNodeID
			req.RevID = pRevID
			resp, err := c.EventRestore(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the event page to restore")
	flags.StringVarP(&pRevID, "rev_id", "r", "", "Id of the revision to restore")
	return cmd
}

// cmdEventSet builds the cobra command for the EventSet RPC.
func cmdEventSet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pStartAt string
	var pEndAt string
	var pAllDay bool
	var pTz string
	var pRrule string
	var pLocation string
	var pColor string
	var pAssignee []string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "set",
		Short: "Set",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("start_at") {
				pStartAt = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventSetParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("start_at") || pStartAt != "" {
				req.StartAt = &pStartAt
			}
			if cmd.Flags().Changed("end_at") || pEndAt != "" {
				req.EndAt = &pEndAt
			}
			if cmd.Flags().Changed("all_day") {
				req.AllDay = &pAllDay
			}
			if cmd.Flags().Changed("tz") || pTz != "" {
				req.Tz = &pTz
			}
			if cmd.Flags().Changed("rrule") || pRrule != "" {
				req.Rrule = &pRrule
			}
			if cmd.Flags().Changed("location") || pLocation != "" {
				req.Location = &pLocation
			}
			if cmd.Flags().Changed("color") || pColor != "" {
				req.Color = &pColor
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("base_updated_at") || pBaseUpdatedAt != "" {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.EventSet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Id of the event page to write")
	flags.StringVarP(&pStartAt, "start_at", "s", "", "local ISO YYYY-MM-DDTHH:MM (or YYYY-MM-DD all-day)")
	flags.StringVarP(&pEndAt, "end_at", "e", "", "local ISO; empty = same as start")
	flags.BoolVarP(&pAllDay, "all_day", "a", false, "whole-day event; ignores the time")
	flags.StringVarP(&pTz, "tz", "z", "", "IANA zone e.g. America/New_York")
	flags.StringVarP(&pRrule, "rrule", "r", "", "RFC-5545 RRULE string")
	flags.StringVarP(&pLocation, "location", "l", "", "free-text place or address")
	flags.StringVarP(&pColor, "color", "c", "", "pigment token (red/blue/...); empty = default")
	flags.StringSliceVarP(&pAssignee, "assignee", "i", nil, "user subjects assigned (like tickets)")
	flags.StringVarP(&pBaseUpdatedAt, "base_updated_at", "b", "", "Optimistic-concurrency token")
	return cmd
}

// cmdExportPage builds the cobra command for the ExportPage RPC.
func cmdExportPage(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "page",
		Short: "Page",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ExportPageParams
			req.PageID = pPageID
			resp, err := c.ExportPage(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Id of the target page")
	return cmd
}

// cmdExportPrepare builds the cobra command for the ExportPrepare RPC.
func cmdExportPrepare(getClient func() (*client.Client, error)) *cobra.Command {
	var pRootID string
	cmd := &cobra.Command{
		Use:   "prepare",
		Short: "Prepare",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("root_id") {
				pRootID = args[0]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ExportPrepareParams
			if cmd.Flags().Changed("root_id") || pRootID != "" {
				req.RootID = &pRootID
			}
			resp, err := c.ExportPrepare(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pRootID, "root_id", "r", "", "Page/folder to export as a subtree; empty = whole account")
	return cmd
}

// cmdHistoryList builds the cobra command for the HistoryList RPC.
func cmdHistoryList(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.HistoryListParams
			req.PageID = pPageID
			resp, err := c.HistoryList(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Page whose revision history to read")
	return cmd
}

// cmdHistoryRestore builds the cobra command for the HistoryRestore RPC.
func cmdHistoryRestore(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pRevID string
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("rev_id") {
				pRevID = args[1]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("rev_id") && pRevID == "" {
				return fmt.Errorf("required flag --rev_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.HistoryRestoreParams
			req.PageID = pPageID
			req.RevID = pRevID
			resp, err := c.HistoryRestore(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Page to roll back")
	flags.StringVarP(&pRevID, "rev_id", "r", "", "Revision to restore the page to (id from History/list)")
	return cmd
}

// cmdHistoryRevision builds the cobra command for the HistoryRevision RPC.
func cmdHistoryRevision(getClient func() (*client.Client, error)) *cobra.Command {
	var pRevID string
	cmd := &cobra.Command{
		Use:   "revision",
		Short: "Revision",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("rev_id") {
				pRevID = args[0]
			}
			if !cmd.Flags().Changed("rev_id") && pRevID == "" {
				return fmt.Errorf("required flag --rev_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.HistoryRevisionParams
			req.RevID = pRevID
			resp, err := c.HistoryRevision(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pRevID, "rev_id", "r", "", "Revision to preview in full (id from History/list)")
	return cmd
}

// cmdPageChanges builds the cobra command for the PageChanges RPC.
func cmdPageChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("since") {
				pSince = args[0]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageChangesParams
			if cmd.Flags().Changed("since") || pSince != "" {
				req.Since = &pSince
			}
			resp, err := c.PageChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pSince, "since", "s", "", "RFC3339Nano updated_at watermark; empty = full pull")
	return cmd
}

// cmdPageClone builds the cobra command for the PageClone RPC.
func cmdPageClone(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "clone",
		Short: "Clone",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageCloneParams
			req.ID = pID
			resp, err := c.PageClone(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Subtree root to deep-copy")
	return cmd
}

// cmdPageCreate builds the cobra command for the PageCreate RPC.
func cmdPageCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pParentID string
	var pTitle string
	var pBody string
	var pKind string
	var pAliasID string
	var pPosition float64
	var pClientID string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("parent_id") {
				pParentID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("title") {
				pTitle = args[1]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageCreateParams
			if cmd.Flags().Changed("parent_id") || pParentID != "" {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("title") || pTitle != "" {
				req.Title = &pTitle
			}
			if cmd.Flags().Changed("body") || pBody != "" {
				req.Body = &pBody
			}
			if cmd.Flags().Changed("kind") || pKind != "" {
				req.Kind = &pKind
			}
			if cmd.Flags().Changed("alias_id") || pAliasID != "" {
				req.AliasID = &pAliasID
			}
			if cmd.Flags().Changed("position") {
				req.Position = &pPosition
			}
			if cmd.Flags().Changed("client_id") || pClientID != "" {
				req.ClientID = &pClientID
			}
			resp, err := c.PageCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pParentID, "parent_id", "p", "", "Empty for a root page")
	flags.StringVarP(&pTitle, "title", "i", "", "Page title")
	flags.StringVarP(&pBody, "body", "b", "", "Markdown body")
	flags.StringVarP(&pKind, "kind", "n", "", "page or folder; example: page")
	flags.StringVarP(&pAliasID, "alias_id", "a", "", "Target id when kind=alias")
	flags.Float64VarP(&pPosition, "position", "o", 0, "Order among siblings")
	flags.StringVarP(&pClientID, "client_id", "c", "", "Optional offline-minted correlation id")
	return cmd
}

// cmdPageDelete builds the cobra command for the PageDelete RPC.
func cmdPageDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageDeleteParams
			req.ID = pID
			resp, err := c.PageDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Page to delete with its subtree")
	return cmd
}

// cmdPageExport builds the cobra command for the PageExport RPC.
func cmdPageExport(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "export",
		Short: "Export",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageExportParams
			req.ID = pID
			resp, err := c.PageExport(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Page to export as markdown")
	return cmd
}

// cmdPageExportAll builds the cobra command for the PageExportAll RPC.
func cmdPageExportAll(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "exportAll",
		Short: "Export all",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.PageExportAll(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdPageGet builds the cobra command for the PageGet RPC.
func cmdPageGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageGetParams
			req.ID = pID
			resp, err := c.PageGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Page to fetch; may be a stale client id")
	return cmd
}

// cmdPageImport builds the cobra command for the PageImport RPC.
func cmdPageImport(getClient func() (*client.Client, error)) *cobra.Command {
	var pFiles string
	var pMode string
	var pDryRun bool
	cmd := &cobra.Command{
		Use:   "import",
		Short: "Import",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("files") {
				pFiles = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("mode") {
				pMode = args[1]
			}
			if !cmd.Flags().Changed("files") && pFiles == "" {
				return fmt.Errorf("required flag --files (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageImportParams
			if err := json.Unmarshal([]byte(pFiles), &req.Files); err != nil {
				return fmt.Errorf("files: invalid JSON: %w", err)
			}
			if cmd.Flags().Changed("mode") || pMode != "" {
				req.Mode = &pMode
			}
			if cmd.Flags().Changed("dry_run") {
				req.DryRun = &pDryRun
			}
			resp, err := c.PageImport(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pFiles, "files", "f", "", "Markdown files to ingest; JSON")
	flags.StringVarP(&pMode, "mode", "m", "", "replace updates a matched page (history saved); anything else creates a copy")
	flags.BoolVarP(&pDryRun, "dry_run", "d", false, "Compute the create/replace plan without writing")
	return cmd
}

// cmdPageListPrefix builds the cobra command for the PageListPrefix RPC.
func cmdPageListPrefix(getClient func() (*client.Client, error)) *cobra.Command {
	var pPath string
	cmd := &cobra.Command{
		Use:   "listPrefix",
		Short: "List prefix",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("path") {
				pPath = args[0]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageListPrefixParams
			if cmd.Flags().Changed("path") || pPath != "" {
				req.Path = &pPath
			}
			resp, err := c.PageListPrefix(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPath, "path", "p", "", "Prefix path to list under; empty = the root; example: docs/api")
	return cmd
}

// cmdPagePathOf builds the cobra command for the PagePathOf RPC.
func cmdPagePathOf(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "pathOf",
		Short: "Path of",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PagePathOfParams
			req.ID = pID
			resp, err := c.PagePathOf(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Page whose slash path to resolve")
	return cmd
}

// cmdPageRefs builds the cobra command for the PageRefs RPC.
func cmdPageRefs(getClient func() (*client.Client, error)) *cobra.Command {
	var pIds []string
	cmd := &cobra.Command{
		Use:   "refs",
		Short: "Refs",
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("ids") {
				return fmt.Errorf("required flag --ids is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageRefsParams
			req.Ids = pIds
			resp, err := c.PageRefs(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringSliceVarP(&pIds, "ids", "i", nil, "Page ids to resolve to title and kind")
	return cmd
}

// cmdPageResolvePath builds the cobra command for the PageResolvePath RPC.
func cmdPageResolvePath(getClient func() (*client.Client, error)) *cobra.Command {
	var pPath string
	cmd := &cobra.Command{
		Use:   "resolvePath",
		Short: "Resolve path",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("path") {
				pPath = args[0]
			}
			if !cmd.Flags().Changed("path") && pPath == "" {
				return fmt.Errorf("required flag --path (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageResolvePathParams
			req.Path = pPath
			resp, err := c.PageResolvePath(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPath, "path", "p", "", "Slash slug path to resolve to a node; example: docs/api/auth")
	return cmd
}

// cmdPageTree builds the cobra command for the PageTree RPC.
func cmdPageTree(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tree",
		Short: "Tree",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.PageTree(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdPageUpdate builds the cobra command for the PageUpdate RPC.
func cmdPageUpdate(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pTitle string
	var pBody string
	var pPosition float64
	var pParentID string
	var pKind string
	var pConfig string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("title") {
				pTitle = args[1]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageUpdateParams
			req.ID = pID
			if cmd.Flags().Changed("title") || pTitle != "" {
				req.Title = &pTitle
			}
			if cmd.Flags().Changed("body") || pBody != "" {
				req.Body = &pBody
			}
			if cmd.Flags().Changed("position") {
				req.Position = &pPosition
			}
			if cmd.Flags().Changed("parent_id") || pParentID != "" {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("kind") || pKind != "" {
				req.Kind = &pKind
			}
			if cmd.Flags().Changed("config") || pConfig != "" {
				if err := json.Unmarshal([]byte(pConfig), &req.Config); err != nil {
					return fmt.Errorf("config: invalid JSON: %w", err)
				}
			}
			if cmd.Flags().Changed("base_updated_at") || pBaseUpdatedAt != "" {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.PageUpdate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Page to update")
	flags.StringVarP(&pTitle, "title", "l", "", "New page title")
	flags.StringVarP(&pBody, "body", "b", "", "New markdown body")
	flags.Float64VarP(&pPosition, "position", "p", 0, "New order among siblings")
	flags.StringVarP(&pParentID, "parent_id", "a", "", "Empty string detaches to root")
	flags.StringVarP(&pKind, "kind", "n", "", "page or folder or ticket")
	flags.StringVarP(&pConfig, "config", "c", "", "Reading width and flags; JSON")
	flags.StringVarP(&pBaseUpdatedAt, "base_updated_at", "s", "", "Optimistic-concurrency token")
	return cmd
}

// cmdPageUpsert builds the cobra command for the PageUpsert RPC.
func cmdPageUpsert(getClient func() (*client.Client, error)) *cobra.Command {
	var pPath string
	var pTitle string
	var pBody string
	cmd := &cobra.Command{
		Use:   "upsert",
		Short: "Upsert",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("path") {
				pPath = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("title") {
				pTitle = args[1]
			}
			if !cmd.Flags().Changed("path") && pPath == "" {
				return fmt.Errorf("required flag --path (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageUpsertParams
			req.Path = pPath
			if cmd.Flags().Changed("title") || pTitle != "" {
				req.Title = &pTitle
			}
			if cmd.Flags().Changed("body") || pBody != "" {
				req.Body = &pBody
			}
			resp, err := c.PageUpsert(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPath, "path", "p", "", "Slash-separated slug path; intermediates become folders. e.g. docs/api/auth; example: docs/api/auth")
	flags.StringVarP(&pTitle, "title", "i", "", "Display title for the leaf page (slug stays the stable key)")
	flags.StringVarP(&pBody, "body", "b", "", "Markdown body")
	return cmd
}

// cmdSearchQuery builds the cobra command for the SearchQuery RPC.
func cmdSearchQuery(getClient func() (*client.Client, error)) *cobra.Command {
	var pQuery string
	var pLimit float64
	var pKinds []string
	var pScopeRoot string
	cmd := &cobra.Command{
		Use:   "query",
		Short: "Query",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("query") {
				pQuery = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("scope_root") {
				pScopeRoot = args[1]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.SearchQueryParams
			if cmd.Flags().Changed("query") || pQuery != "" {
				req.Query = &pQuery
			}
			if cmd.Flags().Changed("limit") {
				req.Limit = &pLimit
			}
			req.Kinds = pKinds
			if cmd.Flags().Changed("scope_root") || pScopeRoot != "" {
				req.ScopeRoot = &pScopeRoot
			}
			resp, err := c.SearchQuery(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pQuery, "query", "q", "", "Full-text search over your pages")
	flags.Float64VarP(&pLimit, "limit", "l", 0, "Max hits to return; defaults to 25 and caps at 100")
	flags.StringSliceVarP(&pKinds, "kinds", "i", nil, "Only these node kinds; up to 8")
	flags.StringVarP(&pScopeRoot, "scope_root", "s", "", "Folder id to search within its subtree")
	return cmd
}

// cmdShareApiDocs builds the cobra command for the ShareApiDocs RPC.
func cmdShareApiDocs(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "apiDocs",
		Short: "Api docs",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.ShareApiDocs(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdShareCreate builds the cobra command for the ShareCreate RPC.
func cmdShareCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pPassword string
	var pAllowFork bool
	var pAllowRaw bool
	var pAllowAnnotations bool
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("password") {
				pPassword = args[1]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareCreateParams
			req.PageID = pPageID
			if cmd.Flags().Changed("password") || pPassword != "" {
				req.Password = &pPassword
			}
			if cmd.Flags().Changed("allow_fork") {
				req.AllowFork = &pAllowFork
			}
			if cmd.Flags().Changed("allow_raw") {
				req.AllowRaw = &pAllowRaw
			}
			if cmd.Flags().Changed("allow_annotations") {
				req.AllowAnnotations = &pAllowAnnotations
			}
			resp, err := c.ShareCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Page to publish as a public share")
	flags.StringVarP(&pPassword, "password", "a", "", "Optional; protects the share on create")
	flags.BoolVarP(&pAllowFork, "allow_fork", "l", false, "Optional; permit forking on create")
	flags.BoolVarP(&pAllowRaw, "allow_raw", "o", false, "Optional; expose markdown source + tree manifest on create")
	flags.BoolVarP(&pAllowAnnotations, "allow_annotations", "w", false, "Optional; let logged-in visitors annotate on create")
	return cmd
}

// cmdShareFork builds the cobra command for the ShareFork RPC.
func cmdShareFork(getClient func() (*client.Client, error)) *cobra.Command {
	var pToken string
	var pParentID string
	var pLease string
	var pWorkspaceID string
	cmd := &cobra.Command{
		Use:   "fork",
		Short: "Fork",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("token") {
				pToken = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("parent_id") {
				pParentID = args[1]
			}
			if !cmd.Flags().Changed("token") && pToken == "" {
				return fmt.Errorf("required flag --token (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareForkParams
			req.Token = pToken
			if cmd.Flags().Changed("parent_id") || pParentID != "" {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("lease") || pLease != "" {
				req.Lease = &pLease
			}
			if cmd.Flags().Changed("workspace_id") || pWorkspaceID != "" {
				req.WorkspaceID = &pWorkspaceID
			}
			resp, err := c.ShareFork(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pToken, "token", "o", "", "Public share token to fork from")
	flags.StringVarP(&pParentID, "parent_id", "p", "", "The caller's folder to fork into; empty = root")
	flags.StringVarP(&pLease, "lease", "l", "", "Required to fork a password-protected share")
	flags.StringVarP(&pWorkspaceID, "workspace_id", "w", "", "Which workspace to fork into; empty = active")
	return cmd
}

// cmdShareForkInfo builds the cobra command for the ShareForkInfo RPC.
func cmdShareForkInfo(getClient func() (*client.Client, error)) *cobra.Command {
	var pRootID string
	cmd := &cobra.Command{
		Use:   "forkInfo",
		Short: "Fork info",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("root_id") {
				pRootID = args[0]
			}
			if !cmd.Flags().Changed("root_id") && pRootID == "" {
				return fmt.Errorf("required flag --root_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareForkInfoParams
			req.RootID = pRootID
			resp, err := c.ShareForkInfo(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pRootID, "root_id", "r", "", "Forked page to check upstream drift for")
	return cmd
}

// cmdShareGet builds the cobra command for the ShareGet RPC.
func cmdShareGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pToken string
	var pLease string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("token") {
				pToken = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("lease") {
				pLease = args[1]
			}
			if !cmd.Flags().Changed("token") && pToken == "" {
				return fmt.Errorf("required flag --token (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareGetParams
			req.Token = pToken
			if cmd.Flags().Changed("lease") || pLease != "" {
				req.Lease = &pLease
			}
			resp, err := c.ShareGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pToken, "token", "o", "", "Public share token to resolve")
	flags.StringVarP(&pLease, "lease", "l", "", "Lease token from Share/unlock (protected shares)")
	return cmd
}

// cmdShareHomepage builds the cobra command for the ShareHomepage RPC.
func cmdShareHomepage(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "homepage",
		Short: "Homepage",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.ShareHomepage(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdShareMine builds the cobra command for the ShareMine RPC.
func cmdShareMine(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "mine",
		Short: "Mine",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.ShareMine(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdShareRevoke builds the cobra command for the ShareRevoke RPC.
func cmdShareRevoke(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "revoke",
		Short: "Revoke",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareRevokeParams
			req.PageID = pPageID
			resp, err := c.ShareRevoke(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Shared page to target")
	return cmd
}

// cmdShareSetAnnotations builds the cobra command for the ShareSetAnnotations RPC.
func cmdShareSetAnnotations(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pAllow bool
	cmd := &cobra.Command{
		Use:   "setAnnotations",
		Short: "Set annotations",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetAnnotationsParams
			req.PageID = pPageID
			if cmd.Flags().Changed("allow") {
				req.Allow = &pAllow
			}
			resp, err := c.ShareSetAnnotations(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Shared page to toggle annotations on")
	flags.BoolVarP(&pAllow, "allow", "a", false, "Let logged-in visitors annotate")
	return cmd
}

// cmdShareSetForkable builds the cobra command for the ShareSetForkable RPC.
func cmdShareSetForkable(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pAllow bool
	cmd := &cobra.Command{
		Use:   "setForkable",
		Short: "Set forkable",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetForkableParams
			req.PageID = pPageID
			if cmd.Flags().Changed("allow") {
				req.Allow = &pAllow
			}
			resp, err := c.ShareSetForkable(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Shared page to toggle forking on")
	flags.BoolVarP(&pAllow, "allow", "a", false, "Permit visitors to fork the share")
	return cmd
}

// cmdShareSetPassword builds the cobra command for the ShareSetPassword RPC.
func cmdShareSetPassword(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pPassword string
	cmd := &cobra.Command{
		Use:   "setPassword",
		Short: "Set password",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("password") {
				pPassword = args[1]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetPasswordParams
			req.PageID = pPageID
			if cmd.Flags().Changed("password") || pPassword != "" {
				req.Password = &pPassword
			}
			resp, err := c.ShareSetPassword(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Shared page to protect or unprotect")
	flags.StringVarP(&pPassword, "password", "a", "", "Empty removes protection")
	return cmd
}

// cmdShareSetRSS builds the cobra command for the ShareSetRSS RPC.
func cmdShareSetRSS(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pAllow bool
	cmd := &cobra.Command{
		Use:   "setRSS",
		Short: "Set RSS",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetRSSParams
			req.PageID = pPageID
			if cmd.Flags().Changed("allow") {
				req.Allow = &pAllow
			}
			resp, err := c.ShareSetRSS(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Shared folder to toggle its RSS feed")
	flags.BoolVarP(&pAllow, "allow", "a", false, "Publish the share RSS feed")
	return cmd
}

// cmdShareStatus builds the cobra command for the ShareStatus RPC.
func cmdShareStatus(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Status",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("page_id") {
				pPageID = args[0]
			}
			if !cmd.Flags().Changed("page_id") && pPageID == "" {
				return fmt.Errorf("required flag --page_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareStatusParams
			req.PageID = pPageID
			resp, err := c.ShareStatus(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pPageID, "page_id", "p", "", "Shared page to target")
	return cmd
}

// cmdShareUnlock builds the cobra command for the ShareUnlock RPC.
func cmdShareUnlock(getClient func() (*client.Client, error)) *cobra.Command {
	var pToken string
	var pPassword string
	cmd := &cobra.Command{
		Use:   "unlock",
		Short: "Unlock",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("token") {
				pToken = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("password") {
				pPassword = args[1]
			}
			if !cmd.Flags().Changed("token") && pToken == "" {
				return fmt.Errorf("required flag --token (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("password") && pPassword == "" {
				return fmt.Errorf("required flag --password (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareUnlockParams
			req.Token = pToken
			req.Password = pPassword
			resp, err := c.ShareUnlock(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pToken, "token", "o", "", "Protected share token to unlock")
	flags.StringVarP(&pPassword, "password", "p", "", "Password proving access to the share")
	return cmd
}

// cmdTagClearNode builds the cobra command for the TagClearNode RPC.
func cmdTagClearNode(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagID string
	cmd := &cobra.Command{
		Use:   "clearNode",
		Short: "Clear node",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("tag_id") {
				pTagID = args[1]
			}
			if !cmd.Flags().Changed("tag_id") && pTagID == "" {
				return fmt.Errorf("required flag --tag_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagClearNodeParams
			if cmd.Flags().Changed("node_id") || pNodeID != "" {
				req.NodeID = &pNodeID
			}
			req.TagID = pTagID
			resp, err := c.TagClearNode(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Node whose override is removed")
	flags.StringVarP(&pTagID, "tag_id", "a", "", "Tag to revert to inherited")
	return cmd
}

// cmdTagCreate builds the cobra command for the TagCreate RPC.
func cmdTagCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pName string
	var pColor string
	var pCategory string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("name") {
				pName = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("color") {
				pColor = args[1]
			}
			if !cmd.Flags().Changed("name") && pName == "" {
				return fmt.Errorf("required flag --name (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagCreateParams
			req.Name = pName
			if cmd.Flags().Changed("color") || pColor != "" {
				req.Color = &pColor
			}
			if cmd.Flags().Changed("category") || pCategory != "" {
				req.Category = &pCategory
			}
			resp, err := c.TagCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pName, "name", "n", "", "New tag label")
	flags.StringVarP(&pColor, "color", "c", "", "default|red|orange|amber|green|blue|violet")
	flags.StringVarP(&pCategory, "category", "a", "", "facet like type; empty = plain label")
	return cmd
}

// cmdTagDelete builds the cobra command for the TagDelete RPC.
func cmdTagDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagDeleteParams
			req.ID = pID
			resp, err := c.TagDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Tag to delete; drops its cascade ops")
	return cmd
}

// cmdTagList builds the cobra command for the TagList RPC.
func cmdTagList(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.TagList(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdTagReorderGlobal builds the cobra command for the TagReorderGlobal RPC.
func cmdTagReorderGlobal(getClient func() (*client.Client, error)) *cobra.Command {
	var pTagIds []string
	cmd := &cobra.Command{
		Use:   "reorderGlobal",
		Short: "Reorder global",
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("tag_ids") {
				return fmt.Errorf("required flag --tag_ids is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagReorderGlobalParams
			req.TagIds = pTagIds
			resp, err := c.TagReorderGlobal(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringSliceVarP(&pTagIds, "tag_ids", "a", nil, "Tag ids in the new global order")
	return cmd
}

// cmdTagReorderNode builds the cobra command for the TagReorderNode RPC.
func cmdTagReorderNode(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagIds []string
	cmd := &cobra.Command{
		Use:   "reorderNode",
		Short: "Reorder node",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagReorderNodeParams
			req.NodeID = pNodeID
			req.TagIds = pTagIds
			resp, err := c.TagReorderNode(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Node whose local tag order to set")
	flags.StringSliceVarP(&pTagIds, "tag_ids", "a", nil, "Tag ids in local order; empty clears the override")
	return cmd
}

// cmdTagSetNode builds the cobra command for the TagSetNode RPC.
func cmdTagSetNode(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagID string
	var pOp string
	cmd := &cobra.Command{
		Use:   "setNode",
		Short: "Set node",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("tag_id") {
				pTagID = args[1]
			}
			if !cmd.Flags().Changed("tag_id") && pTagID == "" {
				return fmt.Errorf("required flag --tag_id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("op") && pOp == "" {
				return fmt.Errorf("required flag --op (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagSetNodeParams
			if cmd.Flags().Changed("node_id") || pNodeID != "" {
				req.NodeID = &pNodeID
			}
			req.TagID = pTagID
			req.Op = pOp
			resp, err := c.TagSetNode(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Empty for the global level")
	flags.StringVarP(&pTagID, "tag_id", "a", "", "Tag to add or remove at the node")
	flags.StringVarP(&pOp, "op", "o", "", "add or remove")
	return cmd
}

// cmdTagSetNodeTags builds the cobra command for the TagSetNodeTags RPC.
func cmdTagSetNodeTags(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagIds []string
	var pOp string
	cmd := &cobra.Command{
		Use:   "setNodeTags",
		Short: "Set node tags",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("op") {
				pOp = args[1]
			}
			if !cmd.Flags().Changed("tag_ids") {
				return fmt.Errorf("required flag --tag_ids is missing")
			}
			if !cmd.Flags().Changed("op") && pOp == "" {
				return fmt.Errorf("required flag --op (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagSetNodeTagsParams
			if cmd.Flags().Changed("node_id") || pNodeID != "" {
				req.NodeID = &pNodeID
			}
			req.TagIds = pTagIds
			req.Op = pOp
			resp, err := c.TagSetNodeTags(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "Empty for the global level")
	flags.StringSliceVarP(&pTagIds, "tag_ids", "a", nil, "Tag ids the op applies to at once")
	flags.StringVarP(&pOp, "op", "o", "", "add or remove")
	return cmd
}

// cmdTagUpdate builds the cobra command for the TagUpdate RPC.
func cmdTagUpdate(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pName string
	var pColor string
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("name") {
				pName = args[1]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("name") && pName == "" {
				return fmt.Errorf("required flag --name (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagUpdateParams
			req.ID = pID
			req.Name = pName
			if cmd.Flags().Changed("color") || pColor != "" {
				req.Color = &pColor
			}
			resp, err := c.TagUpdate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Tag to rename or recolor")
	flags.StringVarP(&pName, "name", "n", "", "New tag label")
	flags.StringVarP(&pColor, "color", "c", "", "New pigment; unknown falls back to default")
	return cmd
}

// cmdTemplateInstantiate builds the cobra command for the TemplateInstantiate RPC.
func cmdTemplateInstantiate(getClient func() (*client.Client, error)) *cobra.Command {
	var pTemplateID string
	var pParentID string
	var pKind string
	var pTitle string
	var pValues string
	cmd := &cobra.Command{
		Use:   "instantiate",
		Short: "Instantiate",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("template_id") {
				pTemplateID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("parent_id") {
				pParentID = args[1]
			}
			if !cmd.Flags().Changed("template_id") && pTemplateID == "" {
				return fmt.Errorf("required flag --template_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TemplateInstantiateParams
			req.TemplateID = pTemplateID
			if cmd.Flags().Changed("parent_id") || pParentID != "" {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("kind") || pKind != "" {
				req.Kind = &pKind
			}
			if cmd.Flags().Changed("title") || pTitle != "" {
				req.Title = &pTitle
			}
			if err := json.Unmarshal([]byte(pValues), &req.Values); err != nil {
				return fmt.Errorf("values: invalid JSON: %w", err)
			}
			resp, err := c.TemplateInstantiate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pTemplateID, "template_id", "e", "", "Template to instantiate")
	flags.StringVarP(&pParentID, "parent_id", "p", "", "Folder to create the page under; empty = root")
	flags.StringVarP(&pKind, "kind", "i", "", "page or ticket (default page)")
	flags.StringVarP(&pTitle, "title", "l", "", "Title for the new page")
	flags.StringVarP(&pValues, "values", "v", "", "Values filling the {field|type} tokens by name; JSON")
	return cmd
}

// cmdTicketChanges builds the cobra command for the TicketChanges RPC.
func cmdTicketChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("since") {
				pSince = args[0]
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketChangesParams
			if cmd.Flags().Changed("since") || pSince != "" {
				req.Since = &pSince
			}
			resp, err := c.TicketChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pSince, "since", "s", "", "RFC3339Nano cursor; empty = full")
	return cmd
}

// cmdTicketDelete builds the cobra command for the TicketDelete RPC.
func cmdTicketDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketDeleteParams
			req.NodeID = pNodeID
			resp, err := c.TicketDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "id of the target ticket page")
	return cmd
}

// cmdTicketGet builds the cobra command for the TicketGet RPC.
func cmdTicketGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketGetParams
			req.NodeID = pNodeID
			resp, err := c.TicketGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "id of the target ticket page")
	return cmd
}

// cmdTicketHistory builds the cobra command for the TicketHistory RPC.
func cmdTicketHistory(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "history",
		Short: "History",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketHistoryParams
			req.NodeID = pNodeID
			resp, err := c.TicketHistory(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "id of the target ticket page")
	return cmd
}

// cmdTicketPatch builds the cobra command for the TicketPatch RPC.
func cmdTicketPatch(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pOwner string
	var pType []string
	var pComponent []string
	var pStatus string
	var pPriority string
	var pAssignee []string
	var pDue string
	var pEstimate string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "patch",
		Short: "Patch",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("owner") {
				pOwner = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketPatchParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("owner") || pOwner != "" {
				req.Owner = &pOwner
			}
			req.Type = pType
			req.Component = pComponent
			if cmd.Flags().Changed("status") || pStatus != "" {
				req.Status = &pStatus
			}
			if cmd.Flags().Changed("priority") || pPriority != "" {
				req.Priority = &pPriority
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("due") || pDue != "" {
				req.Due = &pDue
			}
			if cmd.Flags().Changed("estimate") || pEstimate != "" {
				req.Estimate = &pEstimate
			}
			if cmd.Flags().Changed("base_updated_at") || pBaseUpdatedAt != "" {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.TicketPatch(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "id of the target ticket page")
	flags.StringVarP(&pOwner, "owner", "o", "", "single responsible user id")
	flags.StringSliceVarP(&pType, "type", "y", nil, "tag ids (category type)")
	flags.StringSliceVarP(&pComponent, "component", "c", nil, "tag ids (category component)")
	flags.StringVarP(&pStatus, "status", "s", "", "todo | doing | review | done | cancelled")
	flags.StringVarP(&pPriority, "priority", "p", "", "low | med | high")
	flags.StringSliceVarP(&pAssignee, "assignee", "a", nil, "user ids (a ticket can have many)")
	flags.StringVarP(&pDue, "due", "d", "", "ISO date")
	flags.StringVarP(&pEstimate, "estimate", "e", "", "free-text effort/size estimate")
	flags.StringVarP(&pBaseUpdatedAt, "base_updated_at", "b", "", "Optimistic-concurrency token")
	return cmd
}

// cmdTicketRestore builds the cobra command for the TicketRestore RPC.
func cmdTicketRestore(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pRevID string
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("rev_id") {
				pRevID = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			if !cmd.Flags().Changed("rev_id") && pRevID == "" {
				return fmt.Errorf("required flag --rev_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketRestoreParams
			req.NodeID = pNodeID
			req.RevID = pRevID
			resp, err := c.TicketRestore(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "id of the target ticket page")
	flags.StringVarP(&pRevID, "rev_id", "r", "", "id of the revision to restore")
	return cmd
}

// cmdTicketSet builds the cobra command for the TicketSet RPC.
func cmdTicketSet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pOwner string
	var pType []string
	var pComponent []string
	var pStatus string
	var pPriority string
	var pAssignee []string
	var pDue string
	var pEstimate string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "set",
		Short: "Set",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("node_id") {
				pNodeID = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("owner") {
				pOwner = args[1]
			}
			if !cmd.Flags().Changed("node_id") && pNodeID == "" {
				return fmt.Errorf("required flag --node_id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketSetParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("owner") || pOwner != "" {
				req.Owner = &pOwner
			}
			req.Type = pType
			req.Component = pComponent
			if cmd.Flags().Changed("status") || pStatus != "" {
				req.Status = &pStatus
			}
			if cmd.Flags().Changed("priority") || pPriority != "" {
				req.Priority = &pPriority
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("due") || pDue != "" {
				req.Due = &pDue
			}
			if cmd.Flags().Changed("estimate") || pEstimate != "" {
				req.Estimate = &pEstimate
			}
			if cmd.Flags().Changed("base_updated_at") || pBaseUpdatedAt != "" {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.TicketSet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pNodeID, "node_id", "n", "", "id of the target ticket page")
	flags.StringVarP(&pOwner, "owner", "o", "", "single responsible user id")
	flags.StringSliceVarP(&pType, "type", "y", nil, "tag ids (category type)")
	flags.StringSliceVarP(&pComponent, "component", "c", nil, "tag ids (category component)")
	flags.StringVarP(&pStatus, "status", "s", "", "todo | doing | review | done | cancelled")
	flags.StringVarP(&pPriority, "priority", "p", "", "low med or high")
	flags.StringSliceVarP(&pAssignee, "assignee", "a", nil, "user ids (a ticket can have many)")
	flags.StringVarP(&pDue, "due", "d", "", "ISO date")
	flags.StringVarP(&pEstimate, "estimate", "e", "", "free-text effort/size estimate")
	flags.StringVarP(&pBaseUpdatedAt, "base_updated_at", "b", "", "Optimistic-concurrency token")
	return cmd
}

// cmdWorkspaceForKey builds the cobra command for the WorkspaceForKey RPC.
func cmdWorkspaceForKey(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "forKey",
		Short: "For key",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.WorkspaceForKey(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdWorkspaceTemplateDelete builds the cobra command for the WorkspaceTemplateDelete RPC.
func cmdWorkspaceTemplateDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("id") {
				pID = args[0]
			}
			if !cmd.Flags().Changed("id") && pID == "" {
				return fmt.Errorf("required flag --id (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.WorkspaceTemplateDeleteParams
			req.ID = pID
			resp, err := c.WorkspaceTemplateDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pID, "id", "i", "", "Template to delete")
	return cmd
}

// cmdWorkspaceTemplateList builds the cobra command for the WorkspaceTemplateList RPC.
func cmdWorkspaceTemplateList(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.WorkspaceTemplateList(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdWorkspaceTemplateSave builds the cobra command for the WorkspaceTemplateSave RPC.
func cmdWorkspaceTemplateSave(getClient func() (*client.Client, error)) *cobra.Command {
	var pName string
	var pStructureOnly bool
	var pWorkspace string
	cmd := &cobra.Command{
		Use:   "save",
		Short: "Save",
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 && !cmd.Flags().Changed("name") {
				pName = args[0]
			}
			if len(args) > 1 && !cmd.Flags().Changed("workspace") {
				pWorkspace = args[1]
			}
			if !cmd.Flags().Changed("name") && pName == "" {
				return fmt.Errorf("required flag --name (or positional argument) is missing")
			}
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.WorkspaceTemplateSaveParams
			req.Name = pName
			if cmd.Flags().Changed("structure_only") {
				req.StructureOnly = &pStructureOnly
			}
			if cmd.Flags().Changed("workspace") || pWorkspace != "" {
				req.Workspace = &pWorkspace
			}
			resp, err := c.WorkspaceTemplateSave(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVarP(&pName, "name", "n", "", "Display name for the saved blueprint")
	flags.BoolVarP(&pStructureOnly, "structure_only", "s", false, "Copy the tree + layout but drop bodies")
	flags.StringVarP(&pWorkspace, "workspace", "w", "", "Snapshot this space instead of the active one")
	return cmd
}
