// Code generated by cmdgen; DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"

	"github.com/dakolli/mininote-cli/client"

	"github.com/spf13/cobra"
)

// registerServiceCommands attaches one cobra command per RPC service to root,
// with one subcommand per RPC method. getClient is invoked inside each RunE so
// the resolved base URL and token are always read fresh from the root flags
// and config file on every invocation.
func registerServiceCommands(root *cobra.Command, getClient func() (*client.Client, error)) {
	{
		service := &cobra.Command{
			Use:   "annotation",
			Short: "Annotation service",
		}
		service.AddCommand(cmdAnnotationAdd(getClient))
		service.AddCommand(cmdAnnotationChanges(getClient))
		service.AddCommand(cmdAnnotationDelete(getClient))
		service.AddCommand(cmdAnnotationEdit(getClient))
		service.AddCommand(cmdAnnotationGet(getClient))
		service.AddCommand(cmdAnnotationList(getClient))
		service.AddCommand(cmdAnnotationSetResolved(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "calFeed",
			Short: "Cal Feed service",
		}
		service.AddCommand(cmdCalFeedCreate(getClient))
		service.AddCommand(cmdCalFeedRevoke(getClient))
		service.AddCommand(cmdCalFeedStatus(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "comment",
			Short: "Comment service",
		}
		service.AddCommand(cmdCommentAdd(getClient))
		service.AddCommand(cmdCommentDelete(getClient))
		service.AddCommand(cmdCommentEdit(getClient))
		service.AddCommand(cmdCommentList(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "event",
			Short: "Event service",
		}
		service.AddCommand(cmdEventChanges(getClient))
		service.AddCommand(cmdEventDelete(getClient))
		service.AddCommand(cmdEventGet(getClient))
		service.AddCommand(cmdEventHistory(getClient))
		service.AddCommand(cmdEventPatch(getClient))
		service.AddCommand(cmdEventRestore(getClient))
		service.AddCommand(cmdEventSet(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "export",
			Short: "Export service",
		}
		service.AddCommand(cmdExportPage(getClient))
		service.AddCommand(cmdExportPrepare(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "history",
			Short: "History service",
		}
		service.AddCommand(cmdHistoryList(getClient))
		service.AddCommand(cmdHistoryRestore(getClient))
		service.AddCommand(cmdHistoryRevision(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "page",
			Short: "Page service",
		}
		service.AddCommand(cmdPageChanges(getClient))
		service.AddCommand(cmdPageClone(getClient))
		service.AddCommand(cmdPageCreate(getClient))
		service.AddCommand(cmdPageDelete(getClient))
		service.AddCommand(cmdPageExport(getClient))
		service.AddCommand(cmdPageExportAll(getClient))
		service.AddCommand(cmdPageGet(getClient))
		service.AddCommand(cmdPageImport(getClient))
		service.AddCommand(cmdPageListPrefix(getClient))
		service.AddCommand(cmdPagePathOf(getClient))
		service.AddCommand(cmdPageRefs(getClient))
		service.AddCommand(cmdPageResolvePath(getClient))
		service.AddCommand(cmdPageTree(getClient))
		service.AddCommand(cmdPageUpdate(getClient))
		service.AddCommand(cmdPageUpsert(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "search",
			Short: "Search service",
		}
		service.AddCommand(cmdSearchQuery(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "share",
			Short: "Share service",
		}
		service.AddCommand(cmdShareApiDocs(getClient))
		service.AddCommand(cmdShareCreate(getClient))
		service.AddCommand(cmdShareFork(getClient))
		service.AddCommand(cmdShareForkInfo(getClient))
		service.AddCommand(cmdShareGet(getClient))
		service.AddCommand(cmdShareHomepage(getClient))
		service.AddCommand(cmdShareMine(getClient))
		service.AddCommand(cmdShareRevoke(getClient))
		service.AddCommand(cmdShareSetAnnotations(getClient))
		service.AddCommand(cmdShareSetForkable(getClient))
		service.AddCommand(cmdShareSetPassword(getClient))
		service.AddCommand(cmdShareSetRSS(getClient))
		service.AddCommand(cmdShareStatus(getClient))
		service.AddCommand(cmdShareUnlock(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "tag",
			Short: "Tag service",
		}
		service.AddCommand(cmdTagClearNode(getClient))
		service.AddCommand(cmdTagCreate(getClient))
		service.AddCommand(cmdTagDelete(getClient))
		service.AddCommand(cmdTagList(getClient))
		service.AddCommand(cmdTagReorderGlobal(getClient))
		service.AddCommand(cmdTagReorderNode(getClient))
		service.AddCommand(cmdTagSetNode(getClient))
		service.AddCommand(cmdTagSetNodeTags(getClient))
		service.AddCommand(cmdTagUpdate(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "template",
			Short: "Template service",
		}
		service.AddCommand(cmdTemplateInstantiate(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "ticket",
			Short: "Ticket service",
		}
		service.AddCommand(cmdTicketChanges(getClient))
		service.AddCommand(cmdTicketDelete(getClient))
		service.AddCommand(cmdTicketGet(getClient))
		service.AddCommand(cmdTicketHistory(getClient))
		service.AddCommand(cmdTicketPatch(getClient))
		service.AddCommand(cmdTicketRestore(getClient))
		service.AddCommand(cmdTicketSet(getClient))
		root.AddCommand(service)
	}
	{
		service := &cobra.Command{
			Use:   "workspace",
			Short: "Workspace service",
		}
		service.AddCommand(cmdWorkspaceForKey(getClient))
		service.AddCommand(cmdWorkspaceRoleDelete(getClient))
		service.AddCommand(cmdWorkspaceRoleUpsert(getClient))
		service.AddCommand(cmdWorkspaceRoles(getClient))
		root.AddCommand(service)
	}
}

// cmdAnnotationAdd builds the cobra command for the AnnotationAdd RPC.
func cmdAnnotationAdd(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pBody string
	var pAnchorType string
	var pAnchorQuote string
	var pAnchorPrefix string
	var pAnchorSuffix string
	var pAnchorRev string
	var pColor string
	var pParentID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "add",
		Short: "Add",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationAddParams
			req.NodeID = pNodeID
			req.Body = pBody
			if cmd.Flags().Changed("anchor_type") {
				req.AnchorType = &pAnchorType
			}
			if cmd.Flags().Changed("anchor_quote") {
				req.AnchorQuote = &pAnchorQuote
			}
			if cmd.Flags().Changed("anchor_prefix") {
				req.AnchorPrefix = &pAnchorPrefix
			}
			if cmd.Flags().Changed("anchor_suffix") {
				req.AnchorSuffix = &pAnchorSuffix
			}
			if cmd.Flags().Changed("anchor_rev") {
				req.AnchorRev = &pAnchorRev
			}
			if cmd.Flags().Changed("color") {
				req.Color = &pColor
			}
			if cmd.Flags().Changed("parent_id") {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("token") {
				req.Token = &pToken
			}
			resp, err := c.AnnotationAdd(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pBody, "body", "", "Body")
	_ = cmd.MarkFlagRequired("body")
	flags.StringVar(&pAnchorType, "anchor_type", "", "text quote-selector (default) or block media element")
	flags.StringVar(&pAnchorQuote, "anchor_quote", "", "The exact selected text — OR the media src for a block anchor")
	flags.StringVar(&pAnchorPrefix, "anchor_prefix", "", "~32 chars before the quote")
	flags.StringVar(&pAnchorSuffix, "anchor_suffix", "", "~32 chars after the quote")
	flags.StringVar(&pAnchorRev, "anchor_rev", "", "Page revision id at creation (orphan deep-link)")
	flags.StringVar(&pColor, "color", "", "pigment red/orange/amber/green/blue/violet (root note)")
	flags.StringVar(&pParentID, "parent_id", "", "For a threaded reply")
	flags.StringVar(&pToken, "token", "", "Present when annotating via a share (visitor path)")
	return cmd
}

// cmdAnnotationChanges builds the cobra command for the AnnotationChanges RPC.
func cmdAnnotationChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationChangesParams
			if cmd.Flags().Changed("since") {
				req.Since = &pSince
			}
			resp, err := c.AnnotationChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pSince, "since", "", "RFC3339Nano cursor; empty = full")
	return cmd
}

// cmdAnnotationDelete builds the cobra command for the AnnotationDelete RPC.
func cmdAnnotationDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationDeleteParams
			req.ID = pID
			if cmd.Flags().Changed("token") {
				req.Token = &pToken
			}
			resp, err := c.AnnotationDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Annotation id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pToken, "token", "", "Present when deleting via a share (visitor path)")
	return cmd
}

// cmdAnnotationEdit builds the cobra command for the AnnotationEdit RPC.
func cmdAnnotationEdit(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pBody string
	var pToken string
	cmd := &cobra.Command{
		Use:   "edit",
		Short: "Edit",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationEditParams
			req.ID = pID
			req.Body = pBody
			if cmd.Flags().Changed("token") {
				req.Token = &pToken
			}
			resp, err := c.AnnotationEdit(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Annotation id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pBody, "body", "", "Body")
	_ = cmd.MarkFlagRequired("body")
	flags.StringVar(&pToken, "token", "", "Present when editing via a share (visitor path)")
	return cmd
}

// cmdAnnotationGet builds the cobra command for the AnnotationGet RPC.
func cmdAnnotationGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationGetParams
			req.ID = pID
			if cmd.Flags().Changed("token") {
				req.Token = &pToken
			}
			resp, err := c.AnnotationGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Annotation id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pToken, "token", "", "Present when reading via a share (visitor path)")
	return cmd
}

// cmdAnnotationList builds the cobra command for the AnnotationList RPC.
func cmdAnnotationList(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pToken string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationListParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("token") {
				req.Token = &pToken
			}
			resp, err := c.AnnotationList(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pToken, "token", "", "Present when listing via a share (visitor path)")
	return cmd
}

// cmdAnnotationSetResolved builds the cobra command for the AnnotationSetResolved RPC.
func cmdAnnotationSetResolved(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pResolved bool
	var pToken string
	cmd := &cobra.Command{
		Use:   "setResolved",
		Short: "Set resolved",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.AnnotationSetResolvedParams
			req.ID = pID
			if cmd.Flags().Changed("resolved") {
				req.Resolved = &pResolved
			}
			if cmd.Flags().Changed("token") {
				req.Token = &pToken
			}
			resp, err := c.AnnotationSetResolved(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Annotation id")
	_ = cmd.MarkFlagRequired("id")
	flags.BoolVar(&pResolved, "resolved", false, "true to resolve; false to reopen")
	flags.StringVar(&pToken, "token", "", "Present when resolving via a share (visitor path)")
	return cmd
}

// cmdCalFeedCreate builds the cobra command for the CalFeedCreate RPC.
func cmdCalFeedCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CalFeedCreateParams
			req.NodeID = pNodeID
			resp, err := c.CalFeedCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdCalFeedRevoke builds the cobra command for the CalFeedRevoke RPC.
func cmdCalFeedRevoke(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "revoke",
		Short: "Revoke",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CalFeedRevokeParams
			req.NodeID = pNodeID
			resp, err := c.CalFeedRevoke(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdCalFeedStatus builds the cobra command for the CalFeedStatus RPC.
func cmdCalFeedStatus(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Status",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CalFeedStatusParams
			req.NodeID = pNodeID
			resp, err := c.CalFeedStatus(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdCommentAdd builds the cobra command for the CommentAdd RPC.
func cmdCommentAdd(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pBody string
	var pParentID string
	cmd := &cobra.Command{
		Use:   "add",
		Short: "Add",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentAddParams
			req.NodeID = pNodeID
			req.Body = pBody
			if cmd.Flags().Changed("parent_id") {
				req.ParentID = &pParentID
			}
			resp, err := c.CommentAdd(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pBody, "body", "", "Body")
	_ = cmd.MarkFlagRequired("body")
	flags.StringVar(&pParentID, "parent_id", "", "For a threaded reply")
	return cmd
}

// cmdCommentDelete builds the cobra command for the CommentDelete RPC.
func cmdCommentDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentDeleteParams
			req.ID = pID
			resp, err := c.CommentDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Comment id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}

// cmdCommentEdit builds the cobra command for the CommentEdit RPC.
func cmdCommentEdit(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pBody string
	cmd := &cobra.Command{
		Use:   "edit",
		Short: "Edit",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentEditParams
			req.ID = pID
			req.Body = pBody
			resp, err := c.CommentEdit(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Comment id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pBody, "body", "", "Body")
	_ = cmd.MarkFlagRequired("body")
	return cmd
}

// cmdCommentList builds the cobra command for the CommentList RPC.
func cmdCommentList(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.CommentListParams
			req.NodeID = pNodeID
			resp, err := c.CommentList(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdEventChanges builds the cobra command for the EventChanges RPC.
func cmdEventChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventChangesParams
			if cmd.Flags().Changed("since") {
				req.Since = &pSince
			}
			resp, err := c.EventChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pSince, "since", "", "RFC3339Nano cursor; empty = full")
	return cmd
}

// cmdEventDelete builds the cobra command for the EventDelete RPC.
func cmdEventDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventDeleteParams
			req.NodeID = pNodeID
			resp, err := c.EventDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdEventGet builds the cobra command for the EventGet RPC.
func cmdEventGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventGetParams
			req.NodeID = pNodeID
			resp, err := c.EventGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdEventHistory builds the cobra command for the EventHistory RPC.
func cmdEventHistory(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "history",
		Short: "History",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventHistoryParams
			req.NodeID = pNodeID
			resp, err := c.EventHistory(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdEventPatch builds the cobra command for the EventPatch RPC.
func cmdEventPatch(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pStartAt string
	var pEndAt string
	var pAllDay bool
	var pTz string
	var pRrule string
	var pLocation string
	var pColor string
	var pAssignee []string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "patch",
		Short: "Patch",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventPatchParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("start_at") {
				req.StartAt = &pStartAt
			}
			if cmd.Flags().Changed("end_at") {
				req.EndAt = &pEndAt
			}
			if cmd.Flags().Changed("all_day") {
				req.AllDay = &pAllDay
			}
			if cmd.Flags().Changed("tz") {
				req.Tz = &pTz
			}
			if cmd.Flags().Changed("rrule") {
				req.Rrule = &pRrule
			}
			if cmd.Flags().Changed("location") {
				req.Location = &pLocation
			}
			if cmd.Flags().Changed("color") {
				req.Color = &pColor
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("base_updated_at") {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.EventPatch(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pStartAt, "start_at", "", "Start")
	flags.StringVar(&pEndAt, "end_at", "", "End")
	flags.BoolVar(&pAllDay, "all_day", false, "All day")
	flags.StringVar(&pTz, "tz", "", "Timezone")
	flags.StringVar(&pRrule, "rrule", "", "Recurrence")
	flags.StringVar(&pLocation, "location", "", "Location")
	flags.StringVar(&pColor, "color", "", "Color")
	flags.StringSliceVar(&pAssignee, "assignee", nil, "Assignee")
	flags.StringVar(&pBaseUpdatedAt, "base_updated_at", "", "Base updated_at")
	return cmd
}

// cmdEventRestore builds the cobra command for the EventRestore RPC.
func cmdEventRestore(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pRevID string
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventRestoreParams
			req.NodeID = pNodeID
			req.RevID = pRevID
			resp, err := c.EventRestore(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pRevID, "rev_id", "", "Revision id")
	_ = cmd.MarkFlagRequired("rev_id")
	return cmd
}

// cmdEventSet builds the cobra command for the EventSet RPC.
func cmdEventSet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pStartAt string
	var pEndAt string
	var pAllDay bool
	var pTz string
	var pRrule string
	var pLocation string
	var pColor string
	var pAssignee []string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "set",
		Short: "Set",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.EventSetParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("start_at") {
				req.StartAt = &pStartAt
			}
			if cmd.Flags().Changed("end_at") {
				req.EndAt = &pEndAt
			}
			if cmd.Flags().Changed("all_day") {
				req.AllDay = &pAllDay
			}
			if cmd.Flags().Changed("tz") {
				req.Tz = &pTz
			}
			if cmd.Flags().Changed("rrule") {
				req.Rrule = &pRrule
			}
			if cmd.Flags().Changed("location") {
				req.Location = &pLocation
			}
			if cmd.Flags().Changed("color") {
				req.Color = &pColor
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("base_updated_at") {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.EventSet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pStartAt, "start_at", "", "local ISO YYYY-MM-DDTHH:MM (or YYYY-MM-DD all-day)")
	flags.StringVar(&pEndAt, "end_at", "", "local ISO; empty = same as start")
	flags.BoolVar(&pAllDay, "all_day", false, "All day")
	flags.StringVar(&pTz, "tz", "", "IANA zone e.g. America/New_York")
	flags.StringVar(&pRrule, "rrule", "", "RFC-5545 RRULE string")
	flags.StringVar(&pLocation, "location", "", "Location")
	flags.StringVar(&pColor, "color", "", "pigment token (red/blue/...); empty = default")
	flags.StringSliceVar(&pAssignee, "assignee", nil, "user subjects assigned (like tickets)")
	flags.StringVar(&pBaseUpdatedAt, "base_updated_at", "", "Optimistic-concurrency token")
	return cmd
}

// cmdExportPage builds the cobra command for the ExportPage RPC.
func cmdExportPage(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "page",
		Short: "Page",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ExportPageParams
			req.PageID = pPageID
			resp, err := c.ExportPage(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	return cmd
}

// cmdExportPrepare builds the cobra command for the ExportPrepare RPC.
func cmdExportPrepare(getClient func() (*client.Client, error)) *cobra.Command {
	var pRootID string
	cmd := &cobra.Command{
		Use:   "prepare",
		Short: "Prepare",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ExportPrepareParams
			if cmd.Flags().Changed("root_id") {
				req.RootID = &pRootID
			}
			resp, err := c.ExportPrepare(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pRootID, "root_id", "", "Root id")
	return cmd
}

// cmdHistoryList builds the cobra command for the HistoryList RPC.
func cmdHistoryList(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.HistoryListParams
			req.PageID = pPageID
			resp, err := c.HistoryList(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	return cmd
}

// cmdHistoryRestore builds the cobra command for the HistoryRestore RPC.
func cmdHistoryRestore(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pRevID string
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.HistoryRestoreParams
			req.PageID = pPageID
			req.RevID = pRevID
			resp, err := c.HistoryRestore(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	flags.StringVar(&pRevID, "rev_id", "", "Revision id")
	_ = cmd.MarkFlagRequired("rev_id")
	return cmd
}

// cmdHistoryRevision builds the cobra command for the HistoryRevision RPC.
func cmdHistoryRevision(getClient func() (*client.Client, error)) *cobra.Command {
	var pRevID string
	cmd := &cobra.Command{
		Use:   "revision",
		Short: "Revision",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.HistoryRevisionParams
			req.RevID = pRevID
			resp, err := c.HistoryRevision(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pRevID, "rev_id", "", "Revision id")
	_ = cmd.MarkFlagRequired("rev_id")
	return cmd
}

// cmdPageChanges builds the cobra command for the PageChanges RPC.
func cmdPageChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageChangesParams
			if cmd.Flags().Changed("since") {
				req.Since = &pSince
			}
			resp, err := c.PageChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pSince, "since", "", "RFC3339Nano updated_at watermark; empty = full pull")
	return cmd
}

// cmdPageClone builds the cobra command for the PageClone RPC.
func cmdPageClone(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "clone",
		Short: "Clone",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageCloneParams
			req.ID = pID
			resp, err := c.PageClone(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Page id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}

// cmdPageCreate builds the cobra command for the PageCreate RPC.
func cmdPageCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pParentID string
	var pTitle string
	var pBody string
	var pKind string
	var pAliasID string
	var pPosition float64
	var pClientID string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageCreateParams
			if cmd.Flags().Changed("parent_id") {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("title") {
				req.Title = &pTitle
			}
			if cmd.Flags().Changed("body") {
				req.Body = &pBody
			}
			if cmd.Flags().Changed("kind") {
				req.Kind = &pKind
			}
			if cmd.Flags().Changed("alias_id") {
				req.AliasID = &pAliasID
			}
			if cmd.Flags().Changed("position") {
				req.Position = &pPosition
			}
			if cmd.Flags().Changed("client_id") {
				req.ClientID = &pClientID
			}
			resp, err := c.PageCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pParentID, "parent_id", "", "Empty for a root page")
	flags.StringVar(&pTitle, "title", "", "Title")
	flags.StringVar(&pBody, "body", "", "Body")
	flags.StringVar(&pKind, "kind", "", "page or folder; example: page")
	flags.StringVar(&pAliasID, "alias_id", "", "Target id when kind=alias")
	flags.Float64Var(&pPosition, "position", 0, "Position")
	flags.StringVar(&pClientID, "client_id", "", "Optional offline-minted correlation id")
	return cmd
}

// cmdPageDelete builds the cobra command for the PageDelete RPC.
func cmdPageDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageDeleteParams
			req.ID = pID
			resp, err := c.PageDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Page id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}

// cmdPageExport builds the cobra command for the PageExport RPC.
func cmdPageExport(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "export",
		Short: "Export",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageExportParams
			req.ID = pID
			resp, err := c.PageExport(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Page id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}

// cmdPageExportAll builds the cobra command for the PageExportAll RPC.
func cmdPageExportAll(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "exportAll",
		Short: "Export all",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.PageExportAll(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdPageGet builds the cobra command for the PageGet RPC.
func cmdPageGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageGetParams
			req.ID = pID
			resp, err := c.PageGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Page id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}

// cmdPageImport builds the cobra command for the PageImport RPC.
func cmdPageImport(getClient func() (*client.Client, error)) *cobra.Command {
	var pFiles string
	var pMode string
	var pDryRun bool
	cmd := &cobra.Command{
		Use:   "import",
		Short: "Import",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageImportParams
			if err := json.Unmarshal([]byte(pFiles), &req.Files); err != nil {
				return fmt.Errorf("files: invalid JSON: %w", err)
			}
			if cmd.Flags().Changed("mode") {
				req.Mode = &pMode
			}
			if cmd.Flags().Changed("dry_run") {
				req.DryRun = &pDryRun
			}
			resp, err := c.PageImport(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pFiles, "files", "", "Files; JSON")
	_ = cmd.MarkFlagRequired("files")
	flags.StringVar(&pMode, "mode", "", "replace updates a matched page (history saved); anything else creates a copy")
	flags.BoolVar(&pDryRun, "dry_run", false, "Compute the create/replace plan without writing")
	return cmd
}

// cmdPageListPrefix builds the cobra command for the PageListPrefix RPC.
func cmdPageListPrefix(getClient func() (*client.Client, error)) *cobra.Command {
	var pPath string
	cmd := &cobra.Command{
		Use:   "listPrefix",
		Short: "List prefix",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageListPrefixParams
			if cmd.Flags().Changed("path") {
				req.Path = &pPath
			}
			resp, err := c.PageListPrefix(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPath, "path", "", "Prefix path to list under; empty = the root; example: docs/api")
	return cmd
}

// cmdPagePathOf builds the cobra command for the PagePathOf RPC.
func cmdPagePathOf(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "pathOf",
		Short: "Path of",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PagePathOfParams
			req.ID = pID
			resp, err := c.PagePathOf(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Page id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}

// cmdPageRefs builds the cobra command for the PageRefs RPC.
func cmdPageRefs(getClient func() (*client.Client, error)) *cobra.Command {
	var pIds []string
	cmd := &cobra.Command{
		Use:   "refs",
		Short: "Refs",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageRefsParams
			req.Ids = pIds
			resp, err := c.PageRefs(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringSliceVar(&pIds, "ids", nil, "Page ids")
	_ = cmd.MarkFlagRequired("ids")
	return cmd
}

// cmdPageResolvePath builds the cobra command for the PageResolvePath RPC.
func cmdPageResolvePath(getClient func() (*client.Client, error)) *cobra.Command {
	var pPath string
	cmd := &cobra.Command{
		Use:   "resolvePath",
		Short: "Resolve path",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageResolvePathParams
			req.Path = pPath
			resp, err := c.PageResolvePath(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPath, "path", "", "Slash slug path to resolve to a node; example: docs/api/auth")
	_ = cmd.MarkFlagRequired("path")
	return cmd
}

// cmdPageTree builds the cobra command for the PageTree RPC.
func cmdPageTree(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tree",
		Short: "Tree",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.PageTree(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdPageUpdate builds the cobra command for the PageUpdate RPC.
func cmdPageUpdate(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pTitle string
	var pBody string
	var pPosition float64
	var pParentID string
	var pKind string
	var pConfig string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageUpdateParams
			req.ID = pID
			if cmd.Flags().Changed("title") {
				req.Title = &pTitle
			}
			if cmd.Flags().Changed("body") {
				req.Body = &pBody
			}
			if cmd.Flags().Changed("position") {
				req.Position = &pPosition
			}
			if cmd.Flags().Changed("parent_id") {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("kind") {
				req.Kind = &pKind
			}
			if cmd.Flags().Changed("config") {
				if err := json.Unmarshal([]byte(pConfig), &req.Config); err != nil {
					return fmt.Errorf("config: invalid JSON: %w", err)
				}
			}
			if cmd.Flags().Changed("base_updated_at") {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.PageUpdate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Page id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pTitle, "title", "", "Title")
	flags.StringVar(&pBody, "body", "", "Body")
	flags.Float64Var(&pPosition, "position", 0, "Position")
	flags.StringVar(&pParentID, "parent_id", "", "Empty string detaches to root")
	flags.StringVar(&pKind, "kind", "", "page or folder or ticket")
	flags.StringVar(&pConfig, "config", "", "Reading width and flags; JSON")
	flags.StringVar(&pBaseUpdatedAt, "base_updated_at", "", "Optimistic-concurrency token")
	return cmd
}

// cmdPageUpsert builds the cobra command for the PageUpsert RPC.
func cmdPageUpsert(getClient func() (*client.Client, error)) *cobra.Command {
	var pPath string
	var pTitle string
	var pBody string
	cmd := &cobra.Command{
		Use:   "upsert",
		Short: "Upsert",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.PageUpsertParams
			req.Path = pPath
			if cmd.Flags().Changed("title") {
				req.Title = &pTitle
			}
			if cmd.Flags().Changed("body") {
				req.Body = &pBody
			}
			resp, err := c.PageUpsert(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPath, "path", "", "Slash-separated slug path; intermediates become folders. e.g. docs/api/auth; example: docs/api/auth")
	_ = cmd.MarkFlagRequired("path")
	flags.StringVar(&pTitle, "title", "", "Display title for the leaf page (slug stays the stable key)")
	flags.StringVar(&pBody, "body", "", "Markdown body")
	return cmd
}

// cmdSearchQuery builds the cobra command for the SearchQuery RPC.
func cmdSearchQuery(getClient func() (*client.Client, error)) *cobra.Command {
	var pQuery string
	var pLimit float64
	var pKinds []string
	var pScopeRoot string
	cmd := &cobra.Command{
		Use:   "query",
		Short: "Query",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.SearchQueryParams
			if cmd.Flags().Changed("query") {
				req.Query = &pQuery
			}
			if cmd.Flags().Changed("limit") {
				req.Limit = &pLimit
			}
			req.Kinds = pKinds
			if cmd.Flags().Changed("scope_root") {
				req.ScopeRoot = &pScopeRoot
			}
			resp, err := c.SearchQuery(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pQuery, "query", "", "Full-text search over your pages")
	flags.Float64Var(&pLimit, "limit", 0, "Max results")
	flags.StringSliceVar(&pKinds, "kinds", nil, "Filter by node kind")
	flags.StringVar(&pScopeRoot, "scope_root", "", "Restrict to a folder's subtree")
	return cmd
}

// cmdShareApiDocs builds the cobra command for the ShareApiDocs RPC.
func cmdShareApiDocs(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "apiDocs",
		Short: "Api docs",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.ShareApiDocs(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdShareCreate builds the cobra command for the ShareCreate RPC.
func cmdShareCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pPassword string
	var pAllowFork bool
	var pAllowRaw bool
	var pAllowAnnotations bool
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareCreateParams
			req.PageID = pPageID
			if cmd.Flags().Changed("password") {
				req.Password = &pPassword
			}
			if cmd.Flags().Changed("allow_fork") {
				req.AllowFork = &pAllowFork
			}
			if cmd.Flags().Changed("allow_raw") {
				req.AllowRaw = &pAllowRaw
			}
			if cmd.Flags().Changed("allow_annotations") {
				req.AllowAnnotations = &pAllowAnnotations
			}
			resp, err := c.ShareCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	flags.StringVar(&pPassword, "password", "", "Optional; protects the share on create")
	flags.BoolVar(&pAllowFork, "allow_fork", false, "Optional; permit forking on create")
	flags.BoolVar(&pAllowRaw, "allow_raw", false, "Optional; expose markdown source + tree manifest on create")
	flags.BoolVar(&pAllowAnnotations, "allow_annotations", false, "Optional; let logged-in visitors annotate on create")
	return cmd
}

// cmdShareFork builds the cobra command for the ShareFork RPC.
func cmdShareFork(getClient func() (*client.Client, error)) *cobra.Command {
	var pToken string
	var pParentID string
	var pLease string
	var pWorkspaceID string
	cmd := &cobra.Command{
		Use:   "fork",
		Short: "Fork",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareForkParams
			req.Token = pToken
			if cmd.Flags().Changed("parent_id") {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("lease") {
				req.Lease = &pLease
			}
			if cmd.Flags().Changed("workspace_id") {
				req.WorkspaceID = &pWorkspaceID
			}
			resp, err := c.ShareFork(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pToken, "token", "", "Share token")
	_ = cmd.MarkFlagRequired("token")
	flags.StringVar(&pParentID, "parent_id", "", "The caller's folder to fork into; empty = root")
	flags.StringVar(&pLease, "lease", "", "Required to fork a password-protected share")
	flags.StringVar(&pWorkspaceID, "workspace_id", "", "Which workspace to fork into; empty = active")
	return cmd
}

// cmdShareForkInfo builds the cobra command for the ShareForkInfo RPC.
func cmdShareForkInfo(getClient func() (*client.Client, error)) *cobra.Command {
	var pRootID string
	cmd := &cobra.Command{
		Use:   "forkInfo",
		Short: "Fork info",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareForkInfoParams
			req.RootID = pRootID
			resp, err := c.ShareForkInfo(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pRootID, "root_id", "", "Fork root page id")
	_ = cmd.MarkFlagRequired("root_id")
	return cmd
}

// cmdShareGet builds the cobra command for the ShareGet RPC.
func cmdShareGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pToken string
	var pLease string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareGetParams
			req.Token = pToken
			if cmd.Flags().Changed("lease") {
				req.Lease = &pLease
			}
			resp, err := c.ShareGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pToken, "token", "", "Share token")
	_ = cmd.MarkFlagRequired("token")
	flags.StringVar(&pLease, "lease", "", "Lease token from Share/unlock (protected shares)")
	return cmd
}

// cmdShareHomepage builds the cobra command for the ShareHomepage RPC.
func cmdShareHomepage(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "homepage",
		Short: "Homepage",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.ShareHomepage(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdShareMine builds the cobra command for the ShareMine RPC.
func cmdShareMine(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "mine",
		Short: "Mine",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.ShareMine(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdShareRevoke builds the cobra command for the ShareRevoke RPC.
func cmdShareRevoke(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "revoke",
		Short: "Revoke",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareRevokeParams
			req.PageID = pPageID
			resp, err := c.ShareRevoke(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	return cmd
}

// cmdShareSetAnnotations builds the cobra command for the ShareSetAnnotations RPC.
func cmdShareSetAnnotations(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pAllow bool
	cmd := &cobra.Command{
		Use:   "setAnnotations",
		Short: "Set annotations",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetAnnotationsParams
			req.PageID = pPageID
			if cmd.Flags().Changed("allow") {
				req.Allow = &pAllow
			}
			resp, err := c.ShareSetAnnotations(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	flags.BoolVar(&pAllow, "allow", false, "Allow annotations")
	return cmd
}

// cmdShareSetForkable builds the cobra command for the ShareSetForkable RPC.
func cmdShareSetForkable(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pAllow bool
	cmd := &cobra.Command{
		Use:   "setForkable",
		Short: "Set forkable",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetForkableParams
			req.PageID = pPageID
			if cmd.Flags().Changed("allow") {
				req.Allow = &pAllow
			}
			resp, err := c.ShareSetForkable(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	flags.BoolVar(&pAllow, "allow", false, "Allow forking")
	return cmd
}

// cmdShareSetPassword builds the cobra command for the ShareSetPassword RPC.
func cmdShareSetPassword(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pPassword string
	cmd := &cobra.Command{
		Use:   "setPassword",
		Short: "Set password",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetPasswordParams
			req.PageID = pPageID
			if cmd.Flags().Changed("password") {
				req.Password = &pPassword
			}
			resp, err := c.ShareSetPassword(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	flags.StringVar(&pPassword, "password", "", "Empty removes protection")
	return cmd
}

// cmdShareSetRSS builds the cobra command for the ShareSetRSS RPC.
func cmdShareSetRSS(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	var pAllow bool
	cmd := &cobra.Command{
		Use:   "setRSS",
		Short: "Set RSS",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareSetRSSParams
			req.PageID = pPageID
			if cmd.Flags().Changed("allow") {
				req.Allow = &pAllow
			}
			resp, err := c.ShareSetRSS(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	flags.BoolVar(&pAllow, "allow", false, "Allow RSS feed")
	return cmd
}

// cmdShareStatus builds the cobra command for the ShareStatus RPC.
func cmdShareStatus(getClient func() (*client.Client, error)) *cobra.Command {
	var pPageID string
	cmd := &cobra.Command{
		Use:   "status",
		Short: "Status",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareStatusParams
			req.PageID = pPageID
			resp, err := c.ShareStatus(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pPageID, "page_id", "", "Page id")
	_ = cmd.MarkFlagRequired("page_id")
	return cmd
}

// cmdShareUnlock builds the cobra command for the ShareUnlock RPC.
func cmdShareUnlock(getClient func() (*client.Client, error)) *cobra.Command {
	var pToken string
	var pPassword string
	cmd := &cobra.Command{
		Use:   "unlock",
		Short: "Unlock",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.ShareUnlockParams
			req.Token = pToken
			req.Password = pPassword
			resp, err := c.ShareUnlock(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pToken, "token", "", "Share token")
	_ = cmd.MarkFlagRequired("token")
	flags.StringVar(&pPassword, "password", "", "Password")
	_ = cmd.MarkFlagRequired("password")
	return cmd
}

// cmdTagClearNode builds the cobra command for the TagClearNode RPC.
func cmdTagClearNode(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagID string
	cmd := &cobra.Command{
		Use:   "clearNode",
		Short: "Clear node",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagClearNodeParams
			if cmd.Flags().Changed("node_id") {
				req.NodeID = &pNodeID
			}
			req.TagID = pTagID
			resp, err := c.TagClearNode(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	flags.StringVar(&pTagID, "tag_id", "", "Tag id")
	_ = cmd.MarkFlagRequired("tag_id")
	return cmd
}

// cmdTagCreate builds the cobra command for the TagCreate RPC.
func cmdTagCreate(getClient func() (*client.Client, error)) *cobra.Command {
	var pName string
	var pColor string
	var pCategory string
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagCreateParams
			req.Name = pName
			if cmd.Flags().Changed("color") {
				req.Color = &pColor
			}
			if cmd.Flags().Changed("category") {
				req.Category = &pCategory
			}
			resp, err := c.TagCreate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pName, "name", "", "Tag name")
	_ = cmd.MarkFlagRequired("name")
	flags.StringVar(&pColor, "color", "", "default|red|orange|amber|green|blue|violet")
	flags.StringVar(&pCategory, "category", "", "facet like type; empty = plain label")
	return cmd
}

// cmdTagDelete builds the cobra command for the TagDelete RPC.
func cmdTagDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagDeleteParams
			req.ID = pID
			resp, err := c.TagDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Tag id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}

// cmdTagList builds the cobra command for the TagList RPC.
func cmdTagList(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.TagList(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdTagReorderGlobal builds the cobra command for the TagReorderGlobal RPC.
func cmdTagReorderGlobal(getClient func() (*client.Client, error)) *cobra.Command {
	var pTagIds []string
	cmd := &cobra.Command{
		Use:   "reorderGlobal",
		Short: "Reorder global",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagReorderGlobalParams
			req.TagIds = pTagIds
			resp, err := c.TagReorderGlobal(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringSliceVar(&pTagIds, "tag_ids", nil, "Tag ids in order")
	_ = cmd.MarkFlagRequired("tag_ids")
	return cmd
}

// cmdTagReorderNode builds the cobra command for the TagReorderNode RPC.
func cmdTagReorderNode(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagIds []string
	cmd := &cobra.Command{
		Use:   "reorderNode",
		Short: "Reorder node",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagReorderNodeParams
			req.NodeID = pNodeID
			req.TagIds = pTagIds
			resp, err := c.TagReorderNode(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringSliceVar(&pTagIds, "tag_ids", nil, "Tag ids in order (empty clears the override)")
	return cmd
}

// cmdTagSetNode builds the cobra command for the TagSetNode RPC.
func cmdTagSetNode(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagID string
	var pOp string
	cmd := &cobra.Command{
		Use:   "setNode",
		Short: "Set node",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagSetNodeParams
			if cmd.Flags().Changed("node_id") {
				req.NodeID = &pNodeID
			}
			req.TagID = pTagID
			req.Op = pOp
			resp, err := c.TagSetNode(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Empty for the global level")
	flags.StringVar(&pTagID, "tag_id", "", "Tag id")
	_ = cmd.MarkFlagRequired("tag_id")
	flags.StringVar(&pOp, "op", "", "add or remove")
	_ = cmd.MarkFlagRequired("op")
	return cmd
}

// cmdTagSetNodeTags builds the cobra command for the TagSetNodeTags RPC.
func cmdTagSetNodeTags(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pTagIds []string
	var pOp string
	cmd := &cobra.Command{
		Use:   "setNodeTags",
		Short: "Set node tags",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagSetNodeTagsParams
			if cmd.Flags().Changed("node_id") {
				req.NodeID = &pNodeID
			}
			req.TagIds = pTagIds
			req.Op = pOp
			resp, err := c.TagSetNodeTags(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Empty for the global level")
	flags.StringSliceVar(&pTagIds, "tag_ids", nil, "Tag ids")
	_ = cmd.MarkFlagRequired("tag_ids")
	flags.StringVar(&pOp, "op", "", "add or remove")
	_ = cmd.MarkFlagRequired("op")
	return cmd
}

// cmdTagUpdate builds the cobra command for the TagUpdate RPC.
func cmdTagUpdate(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pName string
	var pColor string
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TagUpdateParams
			req.ID = pID
			req.Name = pName
			if cmd.Flags().Changed("color") {
				req.Color = &pColor
			}
			resp, err := c.TagUpdate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Tag id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pName, "name", "", "Tag name")
	_ = cmd.MarkFlagRequired("name")
	flags.StringVar(&pColor, "color", "", "Pigment")
	return cmd
}

// cmdTemplateInstantiate builds the cobra command for the TemplateInstantiate RPC.
func cmdTemplateInstantiate(getClient func() (*client.Client, error)) *cobra.Command {
	var pTemplateID string
	var pParentID string
	var pKind string
	var pTitle string
	var pValues string
	cmd := &cobra.Command{
		Use:   "instantiate",
		Short: "Instantiate",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TemplateInstantiateParams
			req.TemplateID = pTemplateID
			if cmd.Flags().Changed("parent_id") {
				req.ParentID = &pParentID
			}
			if cmd.Flags().Changed("kind") {
				req.Kind = &pKind
			}
			if cmd.Flags().Changed("title") {
				req.Title = &pTitle
			}
			if err := json.Unmarshal([]byte(pValues), &req.Values); err != nil {
				return fmt.Errorf("values: invalid JSON: %w", err)
			}
			resp, err := c.TemplateInstantiate(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pTemplateID, "template_id", "", "Template id")
	_ = cmd.MarkFlagRequired("template_id")
	flags.StringVar(&pParentID, "parent_id", "", "Parent folder id (empty = root)")
	flags.StringVar(&pKind, "kind", "", "page or ticket (default page)")
	flags.StringVar(&pTitle, "title", "", "Title")
	flags.StringVar(&pValues, "values", "", "Field values by name; JSON")
	return cmd
}

// cmdTicketChanges builds the cobra command for the TicketChanges RPC.
func cmdTicketChanges(getClient func() (*client.Client, error)) *cobra.Command {
	var pSince string
	cmd := &cobra.Command{
		Use:   "changes",
		Short: "Changes",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketChangesParams
			if cmd.Flags().Changed("since") {
				req.Since = &pSince
			}
			resp, err := c.TicketChanges(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pSince, "since", "", "RFC3339Nano cursor; empty = full")
	return cmd
}

// cmdTicketDelete builds the cobra command for the TicketDelete RPC.
func cmdTicketDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketDeleteParams
			req.NodeID = pNodeID
			resp, err := c.TicketDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdTicketGet builds the cobra command for the TicketGet RPC.
func cmdTicketGet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "get",
		Short: "Get",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketGetParams
			req.NodeID = pNodeID
			resp, err := c.TicketGet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdTicketHistory builds the cobra command for the TicketHistory RPC.
func cmdTicketHistory(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	cmd := &cobra.Command{
		Use:   "history",
		Short: "History",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketHistoryParams
			req.NodeID = pNodeID
			resp, err := c.TicketHistory(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	return cmd
}

// cmdTicketPatch builds the cobra command for the TicketPatch RPC.
func cmdTicketPatch(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pOwner string
	var pType []string
	var pStatus string
	var pPriority string
	var pAssignee []string
	var pDue string
	var pEstimate string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "patch",
		Short: "Patch",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketPatchParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("owner") {
				req.Owner = &pOwner
			}
			req.Type = pType
			if cmd.Flags().Changed("status") {
				req.Status = &pStatus
			}
			if cmd.Flags().Changed("priority") {
				req.Priority = &pPriority
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("due") {
				req.Due = &pDue
			}
			if cmd.Flags().Changed("estimate") {
				req.Estimate = &pEstimate
			}
			if cmd.Flags().Changed("base_updated_at") {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.TicketPatch(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pOwner, "owner", "", "Owner")
	flags.StringSliceVar(&pType, "type", nil, "Type")
	flags.StringVar(&pStatus, "status", "", "Status")
	flags.StringVar(&pPriority, "priority", "", "Priority")
	flags.StringSliceVar(&pAssignee, "assignee", nil, "Assignee")
	flags.StringVar(&pDue, "due", "", "Due")
	flags.StringVar(&pEstimate, "estimate", "", "Estimate")
	flags.StringVar(&pBaseUpdatedAt, "base_updated_at", "", "Base updated_at")
	return cmd
}

// cmdTicketRestore builds the cobra command for the TicketRestore RPC.
func cmdTicketRestore(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pRevID string
	cmd := &cobra.Command{
		Use:   "restore",
		Short: "Restore",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketRestoreParams
			req.NodeID = pNodeID
			req.RevID = pRevID
			resp, err := c.TicketRestore(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pRevID, "rev_id", "", "Revision id")
	_ = cmd.MarkFlagRequired("rev_id")
	return cmd
}

// cmdTicketSet builds the cobra command for the TicketSet RPC.
func cmdTicketSet(getClient func() (*client.Client, error)) *cobra.Command {
	var pNodeID string
	var pOwner string
	var pType []string
	var pStatus string
	var pPriority string
	var pAssignee []string
	var pDue string
	var pEstimate string
	var pBaseUpdatedAt string
	cmd := &cobra.Command{
		Use:   "set",
		Short: "Set",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.TicketSetParams
			req.NodeID = pNodeID
			if cmd.Flags().Changed("owner") {
				req.Owner = &pOwner
			}
			req.Type = pType
			if cmd.Flags().Changed("status") {
				req.Status = &pStatus
			}
			if cmd.Flags().Changed("priority") {
				req.Priority = &pPriority
			}
			req.Assignee = pAssignee
			if cmd.Flags().Changed("due") {
				req.Due = &pDue
			}
			if cmd.Flags().Changed("estimate") {
				req.Estimate = &pEstimate
			}
			if cmd.Flags().Changed("base_updated_at") {
				req.BaseUpdatedAt = &pBaseUpdatedAt
			}
			resp, err := c.TicketSet(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pNodeID, "node_id", "", "Node id")
	_ = cmd.MarkFlagRequired("node_id")
	flags.StringVar(&pOwner, "owner", "", "single responsible user id")
	flags.StringSliceVar(&pType, "type", nil, "tag ids (category type)")
	flags.StringVar(&pStatus, "status", "", "todo doing or done")
	flags.StringVar(&pPriority, "priority", "", "low med or high")
	flags.StringSliceVar(&pAssignee, "assignee", nil, "user ids (a ticket can have many)")
	flags.StringVar(&pDue, "due", "", "ISO date")
	flags.StringVar(&pEstimate, "estimate", "", "Estimate")
	flags.StringVar(&pBaseUpdatedAt, "base_updated_at", "", "Optimistic-concurrency token")
	return cmd
}

// cmdWorkspaceForKey builds the cobra command for the WorkspaceForKey RPC.
func cmdWorkspaceForKey(getClient func() (*client.Client, error)) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "forKey",
		Short: "For key",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			resp, err := c.WorkspaceForKey(cmd.Context())
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	return cmd
}

// cmdWorkspaceRoleDelete builds the cobra command for the WorkspaceRoleDelete RPC.
func cmdWorkspaceRoleDelete(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pRoleID string
	cmd := &cobra.Command{
		Use:   "roleDelete",
		Short: "Role delete",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.WorkspaceRoleDeleteParams
			req.ID = pID
			req.RoleID = pRoleID
			resp, err := c.WorkspaceRoleDelete(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Workspace id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pRoleID, "role_id", "", "Role id")
	_ = cmd.MarkFlagRequired("role_id")
	return cmd
}

// cmdWorkspaceRoleUpsert builds the cobra command for the WorkspaceRoleUpsert RPC.
func cmdWorkspaceRoleUpsert(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	var pRoleID string
	var pScope string
	var pName string
	var pDefault string
	var pCaps string
	var pManage bool
	cmd := &cobra.Command{
		Use:   "roleUpsert",
		Short: "Role upsert",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.WorkspaceRoleUpsertParams
			req.ID = pID
			if cmd.Flags().Changed("role_id") {
				req.RoleID = &pRoleID
			}
			if cmd.Flags().Changed("scope") {
				req.Scope = &pScope
			}
			req.Name = pName
			if cmd.Flags().Changed("default") {
				req.Default = &pDefault
			}
			if err := json.Unmarshal([]byte(pCaps), &req.Caps); err != nil {
				return fmt.Errorf("caps: invalid JSON: %w", err)
			}
			if cmd.Flags().Changed("manage") {
				req.Manage = &pManage
			}
			resp, err := c.WorkspaceRoleUpsert(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Workspace id")
	_ = cmd.MarkFlagRequired("id")
	flags.StringVar(&pRoleID, "role_id", "", "empty to create")
	flags.StringVar(&pScope, "scope", "", "owner or workspace (create only)")
	flags.StringVar(&pName, "name", "", "Role name")
	_ = cmd.MarkFlagRequired("name")
	flags.StringVar(&pDefault, "default", "", "off|read|write")
	flags.StringVar(&pCaps, "caps", "", "feature to read|write; JSON")
	flags.BoolVar(&pManage, "manage", false, "Can manage the workspace")
	return cmd
}

// cmdWorkspaceRoles builds the cobra command for the WorkspaceRoles RPC.
func cmdWorkspaceRoles(getClient func() (*client.Client, error)) *cobra.Command {
	var pID string
	cmd := &cobra.Command{
		Use:   "roles",
		Short: "Roles",
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := getClient()
			if err != nil {
				return err
			}
			var req client.WorkspaceRolesParams
			req.ID = pID
			resp, err := c.WorkspaceRoles(cmd.Context(), req)
			if err != nil {
				return rpcErr(err)
			}
			return printResult(cmd, resp)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&pID, "id", "", "Workspace id")
	_ = cmd.MarkFlagRequired("id")
	return cmd
}
