// Package client is a generated, typed HTTP client for the mininote RPC API.
//
// The typed request/response structs and per-RPC methods are generated by
// gen (see gen/); this file contains the hand-written runtime they build on.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

//go:generate go run mininote.dev/cli/gen -in ../../intro.json

// Client talks to a single mininote server over HTTP JSON-RPC.
type Client struct {
	baseURL string
	http    *http.Client
	token   string
	apiKey  bool
	headers http.Header
}

// sessionOnly are the control-plane RPCs that require a real user session and
// are never available to API keys (see intro.json: "Control plane — session-only
// (do NOT expose to keys)"). A key minting keys is privilege escalation, so
// these are blocked client-side before any request is sent.
var sessionOnly = map[string]bool{
	"/rpc/Auth/login":                   true,
	"/rpc/Auth/loginVerify":             true,
	"/rpc/Auth/register":                true,
	"/rpc/Auth/logout":                  true,
	"/rpc/Auth/refresh":                 true,
	"/rpc/Auth/me":                      true,
	"/rpc/Auth/changePassword":          true,
	"/rpc/Auth/deleteAccount":           true,
	"/rpc/Auth/requestPasswordReset":    true,
	"/rpc/Auth/resetPassword":           true,
	"/rpc/Auth/setupTwoFactor":          true,
	"/rpc/Auth/confirmTwoFactor":        true,
	"/rpc/Auth/disableTwoFactor":        true,
	"/rpc/Auth/twoFactorStatus":         true,
	"/rpc/Auth/regenerateRecoveryCodes": true,
	"/rpc/Auth/listSessions":            true,
	"/rpc/Auth/revokeSession":           true,
	"/rpc/Auth/revokeOtherSessions":     true,
	"/rpc/Auth/listTrustedDevices":      true,
	"/rpc/Auth/revokeTrustedDevice":     true,
	"/rpc/Auth/createAPIKey":            true,
	"/rpc/Auth/listAPIKeys":             true,
	"/rpc/Auth/revokeAPIKey":            true,
	"/rpc/Auth/rotateAPIKey":            true,
}

// New validates baseURL and returns a Client using the given options.
func New(baseURL string, opts ...Option) (*Client, error) {
	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("client: parse base url: %w", err)
	}
	if u.Scheme == "" || u.Host == "" {
		return nil, fmt.Errorf("client: base url %q must include scheme and host", baseURL)
	}
	c := &Client{
		baseURL: strings.TrimSuffix(u.String(), "/"),
		http:    &http.Client{},
		headers: make(http.Header),
	}
	for _, opt := range opts {
		opt(c)
	}
	return c, nil
}

// Option configures a Client.
type Option func(*Client)

// WithHTTPClient overrides the underlying HTTP client (useful for timeouts,
// custom transports, etc).
func WithHTTPClient(hc *http.Client) Option {
	return func(c *Client) {
		if hc != nil {
			c.http = hc
		}
	}
}

// WithToken sets a session token used for Authorization headers.
func WithToken(t string) Option {
	return func(c *Client) {
		c.token = t
		c.apiKey = false
	}
}

// WithAPIKey sets a folder-scoped API key used for Authorization headers. API
// keys can only call the key-reachable methods; session-only control-plane RPCs
// (auth, 2FA, session/device management, key management) are rejected client-side.
func WithAPIKey(k string) Option {
	return func(c *Client) {
		c.token = k
		c.apiKey = true
	}
}

// WithHeader adds an extra header to every request.
func WithHeader(k, v string) Option {
	return func(c *Client) {
		c.headers.Add(k, v)
	}
}

// SetToken updates the bearer token on an existing Client.
func (c *Client) SetToken(t string) {
	c.token = t
}

// do performs a POST RPC call: wrap req in the {"args": ...} envelope, POST to
// baseURL+path, unwrap the {"data": ...} response envelope into resp. A non-2xx
// status is returned as an *APIError. Session-only endpoints are rejected up
// front when the client is authenticated with an API key.
func (c *Client) do(ctx context.Context, path string, req, resp any) error {
	if c.apiKey && sessionOnly[path] {
		return &APIError{
			StatusCode: http.StatusForbidden,
			Message:    "this endpoint is not available to API keys",
			Code:       "FORBIDDEN",
		}
	}

	body, err := json.Marshal(struct {
		Args any `json:"args"`
	}{Args: req})
	if err != nil {
		return fmt.Errorf("client: marshal request: %w", err)
	}

	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, c.baseURL+path, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("client: new request: %w", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		httpReq.Header.Set("Authorization", "Bearer "+c.token)
	}
	for k, vs := range c.headers {
		for _, v := range vs {
			httpReq.Header.Add(k, v)
		}
	}

	r, err := c.http.Do(httpReq)
	if err != nil {
		return fmt.Errorf("client: %s: %w", path, err)
	}
	defer r.Body.Close()

	raw, err := io.ReadAll(r.Body)
	if err != nil {
		return fmt.Errorf("client: read response: %w", err)
	}

	if r.StatusCode < 200 || r.StatusCode > 299 {
		msg, code := decodeError(raw)
		return &APIError{
			StatusCode: r.StatusCode,
			Message:    msg,
			Code:       code,
			Body:       string(raw),
		}
	}
	if err := decodeData(raw, resp); err != nil {
		return fmt.Errorf("client: decode response (%d): %w", r.StatusCode, err)
	}
	return nil
}

// decodeData unwraps the {"data": ...} response envelope. If the envelope key is
// absent the whole body is decoded into resp (robust to bare responses).
func decodeData(raw []byte, resp any) error {
	var env struct {
		Data json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(raw, &env); err != nil {
		return err
	}
	if env.Data != nil {
		return json.Unmarshal(env.Data, resp)
	}
	return json.Unmarshal(raw, resp)
}

// decodeError best-effort extracts a human message and code from an error
// response body, trying {"error": {"message", "code"}}, {"error": string},
// then {"message": string}.
func decodeError(raw []byte) (msg, code string) {
	var asMap map[string]json.RawMessage
	if err := json.Unmarshal(raw, &asMap); err != nil {
		return strings.TrimSpace(string(raw)), ""
	}
	if v, ok := asMap["error"]; ok {
		var s string
		if json.Unmarshal(v, &s) == nil {
			return s, ""
		}
		var nested struct {
			Message string `json:"message"`
			Code    string `json:"code"`
		}
		if json.Unmarshal(v, &nested) == nil {
			return nested.Message, nested.Code
		}
	}
	if v, ok := asMap["message"]; ok {
		var s string
		if json.Unmarshal(v, &s) == nil {
			return s, ""
		}
	}
	return strings.TrimSpace(string(raw)), ""
}

// APIError describes a non-2xx RPC response.
type APIError struct {
	StatusCode int
	Message    string
	Code       string
	Body       string
}

func (e *APIError) Error() string {
	if e.Code != "" && e.Message != "" {
		return fmt.Sprintf("mininote: %s (code %s, status %d)", e.Message, e.Code, e.StatusCode)
	}
	if e.Code != "" {
		return fmt.Sprintf("mininote: %s (status %d)", e.Code, e.StatusCode)
	}
	return fmt.Sprintf("mininote: %s (status %d)", e.Message, e.StatusCode)
}
