// Code generated by gen; DO NOT EDIT.

package client

type APIKeyInfo struct {
	ID           *string                `json:"id,omitempty"`
	Name         *string                `json:"name,omitempty"`
	ScopeRoot    *string                `json:"scope_root,omitempty"`
	ScopeFolders []APIKeyScopeFolder    `json:"scope_folders,omitempty"`
	Tier         *string                `json:"tier,omitempty"`
	ScopeMode    *string                `json:"scope_mode,omitempty"`
	Capabilities map[string]any         `json:"capabilities,omitempty"`
	Surfaces     []string               `json:"surfaces,omitempty"`
	TokenPrefix  *string                `json:"token_prefix,omitempty"`
	LastUsedAt   *string                `json:"last_used_at,omitempty"`
	ExpiresAt    *string                `json:"expires_at,omitempty"`
	CreatedAt    *string                `json:"created_at,omitempty"`
	Workspaces   []APIKeyWorkspaceGrant `json:"workspaces,omitempty"`
}

type APIKeyScopeFolder struct {
	ID    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
}

type APIKeyWorkspaceGrant struct {
	WorkspaceID    *string             `json:"workspace_id,omitempty"`
	WorkspaceName  *string             `json:"workspace_name,omitempty"`
	WorkspaceColor *string             `json:"workspace_color,omitempty"`
	FolderTitle    *string             `json:"folder_title,omitempty"`
	Folders        []APIKeyScopeFolder `json:"folders,omitempty"`
}

type AcceptInviteLinkResult struct {
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
}

type ActivityFavoriteParams struct {
	// Page id
	PageID string `json:"page_id"`
}

type ActivityReorderFavoritesParams struct {
	// Ordered page ids
	Ids []string `json:"ids"`
}

type ActivityUnfavoriteParams struct {
	// Page id
	PageID string `json:"page_id"`
}

type ActivityViewParams struct {
	// Page id
	PageID string `json:"page_id"`
}

type Annotation struct {
	ID           *string `json:"id,omitempty"`
	SpaceID      *string `json:"space_id,omitempty"`
	NodeID       *string `json:"node_id,omitempty"`
	OwnerID      *string `json:"owner_id,omitempty"`
	ParentID     *string `json:"parent_id,omitempty"`
	AnchorType   *string `json:"anchor_type,omitempty"`
	AnchorQuote  *string `json:"anchor_quote,omitempty"`
	AnchorPrefix *string `json:"anchor_prefix,omitempty"`
	AnchorSuffix *string `json:"anchor_suffix,omitempty"`
	AnchorRev    *string `json:"anchor_rev,omitempty"`
	Color        *string `json:"color,omitempty"`
	Body         *string `json:"body,omitempty"`
	Resolved     *bool   `json:"resolved,omitempty"`
	CreatedAt    *string `json:"created_at,omitempty"`
	UpdatedAt    *string `json:"updated_at,omitempty"`
	DeletedAt    *string `json:"deleted_at,omitempty"`
}

type AnnotationAddParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Body
	Body string `json:"body"`
	// text quote-selector (default) or block media element
	AnchorType *string `json:"anchor_type,omitempty"`
	// The exact selected text — OR the media src for a block anchor
	AnchorQuote *string `json:"anchor_quote,omitempty"`
	// ~32 chars before the quote
	AnchorPrefix *string `json:"anchor_prefix,omitempty"`
	// ~32 chars after the quote
	AnchorSuffix *string `json:"anchor_suffix,omitempty"`
	// Page revision id at creation (orphan deep-link)
	AnchorRev *string `json:"anchor_rev,omitempty"`
	// pigment red/orange/amber/green/blue/violet (root note)
	Color *string `json:"color,omitempty"`
	// For a threaded reply
	ParentID *string `json:"parent_id,omitempty"`
	// Present when annotating via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationChangesParams struct {
	// RFC3339Nano cursor; empty = full
	Since *string `json:"since,omitempty"`
}

type AnnotationDeleteParams struct {
	// Annotation id
	ID string `json:"id"`
	// Present when deleting via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationDeleted struct {
	ID *string `json:"id,omitempty"`
	Ok *bool   `json:"ok,omitempty"`
}

type AnnotationEditParams struct {
	// Annotation id
	ID string `json:"id"`
	// Body
	Body string `json:"body"`
	// Present when editing via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationFeed struct {
	Annotations []Annotation `json:"annotations,omitempty"`
	Tombstones  []string     `json:"tombstones,omitempty"`
	Cursor      *string      `json:"cursor,omitempty"`
}

type AnnotationGetParams struct {
	// Annotation id
	ID string `json:"id"`
	// Present when reading via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationListParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Present when listing via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationSetResolvedParams struct {
	// Annotation id
	ID string `json:"id"`
	// true to resolve; false to reopen
	Resolved *bool `json:"resolved,omitempty"`
	// Present when resolving via a share (visitor path)
	Token *string `json:"token,omitempty"`
}

type AnnotationThread struct {
	Annotations []AnnotationView `json:"annotations,omitempty"`
}

type AnnotationView struct {
	ID           *string `json:"id,omitempty"`
	NodeID       *string `json:"node_id,omitempty"`
	OwnerID      *string `json:"owner_id,omitempty"`
	Author       *string `json:"author,omitempty"`
	ParentID     *string `json:"parent_id,omitempty"`
	AnchorType   *string `json:"anchor_type,omitempty"`
	AnchorQuote  *string `json:"anchor_quote,omitempty"`
	AnchorPrefix *string `json:"anchor_prefix,omitempty"`
	AnchorSuffix *string `json:"anchor_suffix,omitempty"`
	AnchorRev    *string `json:"anchor_rev,omitempty"`
	Color        *string `json:"color,omitempty"`
	Body         *string `json:"body,omitempty"`
	Resolved     *bool   `json:"resolved,omitempty"`
	CreatedAt    *string `json:"created_at,omitempty"`
	UpdatedAt    *string `json:"updated_at,omitempty"`
}

type BaseModel struct {
}

type CalFeedCreateParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type CalFeedRevokeParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type CalFeedStatusParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type ChangesResult struct {
	Pages      []Page   `json:"pages,omitempty"`
	Tombstones []string `json:"tombstones,omitempty"`
	Cursor     *string  `json:"cursor,omitempty"`
}

type Comment struct {
	ID        *string `json:"id,omitempty"`
	SpaceID   *string `json:"space_id,omitempty"`
	NodeID    *string `json:"node_id,omitempty"`
	OwnerID   *string `json:"owner_id,omitempty"`
	ParentID  *string `json:"parent_id,omitempty"`
	Body      *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
}

type CommentAddParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Body
	Body string `json:"body"`
	// For a threaded reply
	ParentID *string `json:"parent_id,omitempty"`
}

type CommentDeleteParams struct {
	// Comment id
	ID string `json:"id"`
}

type CommentDeleted struct {
	ID *string `json:"id,omitempty"`
	Ok *bool   `json:"ok,omitempty"`
}

type CommentEditParams struct {
	// Comment id
	ID string `json:"id"`
	// Body
	Body string `json:"body"`
}

type CommentListParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type CommentThread struct {
	Comments []CommentView `json:"comments,omitempty"`
}

type CommentView struct {
	ID        *string `json:"id,omitempty"`
	NodeID    *string `json:"node_id,omitempty"`
	OwnerID   *string `json:"owner_id,omitempty"`
	Author    *string `json:"author,omitempty"`
	ParentID  *string `json:"parent_id,omitempty"`
	Body      *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

type CreateAPIKeyResult struct {
	ID  *string `json:"id,omitempty"`
	Key *string `json:"key,omitempty"`
}

type CreateKeyResult struct {
	ID  *string `json:"id,omitempty"`
	Key *string `json:"key,omitempty"`
}

type DashboardSaveParams struct {
	// Dashboard config
	Config map[string]any `json:"config"`
}

type DashboardSetLockedParams struct {
	// true freezes the home (edit hidden); false reopens it
	Locked *bool `json:"locked,omitempty"`
}

type DashboardSnapshot struct {
	Config  map[string]any `json:"config,omitempty"`
	CanEdit *bool          `json:"can_edit,omitempty"`
	Locked  *bool          `json:"locked,omitempty"`
	CanLock *bool          `json:"can_lock,omitempty"`
}

type Event struct {
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	StartAt   *string  `json:"start_at,omitempty"`
	EndAt     *string  `json:"end_at,omitempty"`
	AllDay    *bool    `json:"all_day,omitempty"`
	Tz        *string  `json:"tz,omitempty"`
	Rrule     *string  `json:"rrule,omitempty"`
	Location  *string  `json:"location,omitempty"`
	Color     *string  `json:"color,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
	DeletedAt *string  `json:"deleted_at,omitempty"`
}

type EventChangesParams struct {
	// RFC3339Nano cursor; empty = full
	Since *string `json:"since,omitempty"`
}

type EventDeleteAck struct {
	NodeID *string `json:"node_id,omitempty"`
	Ok     *bool   `json:"ok,omitempty"`
}

type EventDeleteParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type EventFeed struct {
	Events     []Event  `json:"events,omitempty"`
	Tombstones []string `json:"tombstones,omitempty"`
	Cursor     *string  `json:"cursor,omitempty"`
}

type EventGetParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type EventHistoryParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type EventPatchParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Start
	StartAt *string `json:"start_at,omitempty"`
	// End
	EndAt *string `json:"end_at,omitempty"`
	// All day
	AllDay *bool `json:"all_day,omitempty"`
	// Timezone
	Tz *string `json:"tz,omitempty"`
	// Recurrence
	Rrule *string `json:"rrule,omitempty"`
	// Location
	Location *string `json:"location,omitempty"`
	// Color
	Color *string `json:"color,omitempty"`
	// Assignee
	Assignee []string `json:"assignee,omitempty"`
	// Base updated_at
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type EventRestoreParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Revision id
	RevID string `json:"rev_id"`
}

type EventRevision struct {
	ID        *string  `json:"id,omitempty"`
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	StartAt   *string  `json:"start_at,omitempty"`
	EndAt     *string  `json:"end_at,omitempty"`
	AllDay    *bool    `json:"all_day,omitempty"`
	Tz        *string  `json:"tz,omitempty"`
	Rrule     *string  `json:"rrule,omitempty"`
	Location  *string  `json:"location,omitempty"`
	Color     *string  `json:"color,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type EventSetParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// local ISO YYYY-MM-DDTHH:MM (or YYYY-MM-DD all-day)
	StartAt *string `json:"start_at,omitempty"`
	// local ISO; empty = same as start
	EndAt *string `json:"end_at,omitempty"`
	// All day
	AllDay *bool `json:"all_day,omitempty"`
	// IANA zone e.g. America/New_York
	Tz *string `json:"tz,omitempty"`
	// RFC-5545 RRULE string
	Rrule *string `json:"rrule,omitempty"`
	// Location
	Location *string `json:"location,omitempty"`
	// pigment token (red/blue/...); empty = default
	Color *string `json:"color,omitempty"`
	// user subjects assigned (like tickets)
	Assignee []string `json:"assignee,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type ExportPageParams struct {
	// Page id
	PageID string `json:"page_id"`
}

type ExportPrepareParams struct {
	// Root id
	RootID *string `json:"root_id,omitempty"`
}

type ExportPrepared struct {
	Token *string `json:"token,omitempty"`
}

type ExportResult struct {
	Markdown *string `json:"markdown,omitempty"`
}

type ExportedPage struct {
	Markdown *string `json:"markdown,omitempty"`
}

type FeedState struct {
	NodeID *string `json:"node_id,omitempty"`
	Token  *string `json:"token,omitempty"`
}

type Fields struct {
	Owner    *string  `json:"owner,omitempty"`
	Type     []string `json:"type,omitempty"`
	Status   *string  `json:"status,omitempty"`
	Priority *string  `json:"priority,omitempty"`
	Assignee []string `json:"assignee,omitempty"`
	Due      *string  `json:"due,omitempty"`
	Estimate *string  `json:"estimate,omitempty"`
}

type ForkResult struct {
	ID *string `json:"id,omitempty"`
}

type ForkStatus struct {
	IsFork            *bool    `json:"is_fork,omitempty"`
	Active            *bool    `json:"active,omitempty"`
	ForkedAt          *string  `json:"forked_at,omitempty"`
	UpstreamUpdatedAt *string  `json:"upstream_updated_at,omitempty"`
	Behind            *float64 `json:"behind,omitempty"`
}

type Header struct {
	Handle     *string  `json:"handle,omitempty"`
	Bio        *string  `json:"bio,omitempty"`
	Avatar     *string  `json:"avatar,omitempty"`
	AvatarPos  *string  `json:"avatar_pos,omitempty"`
	AvatarZoom *float64 `json:"avatar_zoom,omitempty"`
	Banner     *string  `json:"banner,omitempty"`
	BannerH    *string  `json:"banner_h,omitempty"`
	BannerPos  *string  `json:"banner_pos,omitempty"`
	BannerZoom *float64 `json:"banner_zoom,omitempty"`
	Rss        *bool    `json:"rss,omitempty"`
}

type HistoryListParams struct {
	// Page id
	PageID string `json:"page_id"`
}

type HistoryRestoreParams struct {
	// Page id
	PageID string `json:"page_id"`
	// Revision id
	RevID string `json:"rev_id"`
}

type HistoryRevisionParams struct {
	// Revision id
	RevID string `json:"rev_id"`
}

type Hit struct {
	ID      *string `json:"id,omitempty"`
	Title   *string `json:"title,omitempty"`
	Snippet *string `json:"snippet,omitempty"`
}

type IDsResult struct {
	Ids []string `json:"ids,omitempty"`
}

type ImportFileParam struct {
	// Used for the slug + title fallback
	Name string `json:"name"`
	// Frontmatter still attached
	Content string `json:"content"`
	// Empty for root
	ParentID *string `json:"parent_id,omitempty"`
}

type ImportItemResult struct {
	Name    *string `json:"name,omitempty"`
	Title   *string `json:"title,omitempty"`
	Action  *string `json:"action,omitempty"`
	PageID  *string `json:"page_id,omitempty"`
	Matched *bool   `json:"matched,omitempty"`
}

type ImportResult struct {
	Items []ImportItemResult `json:"items,omitempty"`
}

type Info struct {
	ID        *string      `json:"id,omitempty"`
	Name      *string      `json:"name,omitempty"`
	Kind      *string      `json:"kind,omitempty"`
	Role      *string      `json:"role,omitempty"`
	Color     *string      `json:"color,omitempty"`
	Key       *string      `json:"key,omitempty"`
	CreatedAt *string      `json:"created_at,omitempty"`
	Grant     *MemberGrant `json:"grant,omitempty"`
}

type InviteLinkPreview struct {
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	Role          *string `json:"role,omitempty"`
}

type InviteLinkResult struct {
	Token   *string  `json:"token,omitempty"`
	Url     *string  `json:"url,omitempty"`
	Role    *string  `json:"role,omitempty"`
	MaxUses *float64 `json:"max_uses,omitempty"`
}

type InviteLinkView struct {
	Token     *string  `json:"token,omitempty"`
	Url       *string  `json:"url,omitempty"`
	Role      *string  `json:"role,omitempty"`
	ExpiresAt *string  `json:"expires_at,omitempty"`
	MaxUses   *float64 `json:"max_uses,omitempty"`
	Uses      *float64 `json:"uses,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type InvitesResult struct {
	Invites []PendingInvite `json:"invites,omitempty"`
}

type KeyActivityResult struct {
	Items []Row `json:"items,omitempty"`
}

type KeyInfo struct {
	ID              *string        `json:"id,omitempty"`
	Name            *string        `json:"name,omitempty"`
	Tier            *string        `json:"tier,omitempty"`
	ScopeRoot       *string        `json:"scope_root,omitempty"`
	ScopeFolders    []ScopeFolder  `json:"scope_folders,omitempty"`
	ScopeMode       *string        `json:"scope_mode,omitempty"`
	Access          *string        `json:"access,omitempty"`
	Capabilities    map[string]any `json:"capabilities,omitempty"`
	Surfaces        []string       `json:"surfaces,omitempty"`
	TokenPrefix     *string        `json:"token_prefix,omitempty"`
	LastUsedAt      *string        `json:"last_used_at,omitempty"`
	ExpiresAt       *string        `json:"expires_at,omitempty"`
	CreatedAt       *string        `json:"created_at,omitempty"`
	CreatedBy       *string        `json:"created_by,omitempty"`
	CreatedByHandle *string        `json:"created_by_handle,omitempty"`
	Mine            *bool          `json:"mine,omitempty"`
}

type KeysResult struct {
	Keys []KeyInfo `json:"keys,omitempty"`
}

type LinkedIdentity struct {
	Provider  *string `json:"provider,omitempty"`
	Label     *string `json:"label,omitempty"`
	Email     *string `json:"email,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type ListAPIKeysResult struct {
	Keys []APIKeyInfo `json:"keys,omitempty"`
}

type ListInviteLinksResult struct {
	Links []InviteLinkView `json:"links,omitempty"`
}

type LockAcquireParams struct {
	// Resource key
	Resource string `json:"resource"`
	// Session token
	Token string `json:"token"`
	// Display label
	Label *string `json:"label,omitempty"`
	// Reclaim only (don't grab if free)
	Reclaim *bool `json:"reclaim,omitempty"`
}

type LockReleaseParams struct {
	// Resource key
	Resource string `json:"resource"`
	// Session token
	Token string `json:"token"`
}

type LockResult struct {
	Held             *bool    `json:"held,omitempty"`
	Holder           *string  `json:"holder,omitempty"`
	HeartbeatSeconds *float64 `json:"heartbeat_seconds,omitempty"`
}

type LockStatusInfo struct {
	Locked           *bool    `json:"locked,omitempty"`
	Holder           *string  `json:"holder,omitempty"`
	HeartbeatSeconds *float64 `json:"heartbeat_seconds,omitempty"`
}

type LockStatusParams struct {
	// Resource key
	Resource string `json:"resource"`
}

type LoginResult struct {
	Token             *string `json:"token,omitempty"`
	RefreshToken      *string `json:"refresh_token,omitempty"`
	Subject           *string `json:"subject,omitempty"`
	ExpiresAt         *string `json:"expires_at,omitempty"`
	MfaRequired       *bool   `json:"mfa_required,omitempty"`
	MfaToken          *string `json:"mfa_token,omitempty"`
	TrustToken        *string `json:"trust_token,omitempty"`
	LinkRequired      *bool   `json:"link_required,omitempty"`
	LinkToken         *string `json:"link_token,omitempty"`
	LinkEmail         *string `json:"link_email,omitempty"`
	LinkProvider      *string `json:"link_provider,omitempty"`
	LinkProviderLabel *string `json:"link_provider_label,omitempty"`
	Connected         *bool   `json:"connected,omitempty"`
	SignupRequired    *bool   `json:"signup_required,omitempty"`
	SignupToken       *string `json:"signup_token,omitempty"`
	SuggestedHandle   *string `json:"suggested_handle,omitempty"`
}

type MeCan struct {
	Read   *bool `json:"read,omitempty"`
	Write  *bool `json:"write,omitempty"`
	Manage *bool `json:"manage,omitempty"`
}

type MeResult struct {
	Subject      *string      `json:"subject,omitempty"`
	Handle       *string      `json:"handle,omitempty"`
	Email        *string      `json:"email,omitempty"`
	CreatedAt    *string      `json:"created_at,omitempty"`
	LastSeen     *string      `json:"last_seen,omitempty"`
	PlatformRole *string      `json:"platform_role,omitempty"`
	Workspace    *MeWorkspace `json:"workspace,omitempty"`
	HasPassword  *bool        `json:"has_password,omitempty"`
}

type MeWorkspace struct {
	ID   *string `json:"id,omitempty"`
	Role *string `json:"role,omitempty"`
	Can  *MeCan  `json:"can,omitempty"`
}

type MediaItem struct {
	Sha        *string  `json:"sha,omitempty"`
	Ext        *string  `json:"ext,omitempty"`
	Name       *string  `json:"name,omitempty"`
	Url        *string  `json:"url,omitempty"`
	Thumb      *string  `json:"thumb,omitempty"`
	Width      *float64 `json:"width,omitempty"`
	Height     *float64 `json:"height,omitempty"`
	Bytes      *float64 `json:"bytes,omitempty"`
	UploadedBy *string  `json:"uploaded_by,omitempty"`
	CreatedAt  *string  `json:"created_at,omitempty"`
}

type MemberGrant struct {
	Default *float64       `json:"default,omitempty"`
	Caps    map[string]any `json:"caps,omitempty"`
	Manage  *bool          `json:"manage,omitempty"`
}

type MemberInfo struct {
	Subject *string `json:"subject,omitempty"`
	Handle  *string `json:"handle,omitempty"`
	Role    *string `json:"role,omitempty"`
}

type MembersResult struct {
	Members []MemberInfo `json:"members,omitempty"`
}

type Mine struct {
	HomeID     *string        `json:"home_id,omitempty"`
	Visibility *string        `json:"visibility,omitempty"`
	Rss        *bool          `json:"rss,omitempty"`
	Bio        *string        `json:"bio,omitempty"`
	Avatar     *string        `json:"avatar,omitempty"`
	Width      *string        `json:"width,omitempty"`
	Accent     *string        `json:"accent,omitempty"`
	Link       *string        `json:"link,omitempty"`
	Font       *string        `json:"font,omitempty"`
	Sidebar    *string        `json:"sidebar,omitempty"`
	AvatarPos  *string        `json:"avatar_pos,omitempty"`
	AvatarZoom *float64       `json:"avatar_zoom,omitempty"`
	Banner     *string        `json:"banner,omitempty"`
	BannerH    *string        `json:"banner_h,omitempty"`
	BannerPos  *string        `json:"banner_pos,omitempty"`
	BannerZoom *float64       `json:"banner_zoom,omitempty"`
	Density    *string        `json:"density,omitempty"`
	Blocks     map[string]any `json:"blocks,omitempty"`
}

type MineResult struct {
	Shares []SharedListing `json:"shares,omitempty"`
}

type MyInvitesResult struct {
	Invites []PendingInvite `json:"invites,omitempty"`
}

type MyWorkItem struct {
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	NodeID        *string `json:"node_id,omitempty"`
	Title         *string `json:"title,omitempty"`
	Status        *string `json:"status,omitempty"`
	Priority      *string `json:"priority,omitempty"`
	Due           *string `json:"due,omitempty"`
	TypeName      *string `json:"type_name,omitempty"`
	TypeColor     *string `json:"type_color,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
}

type MyWorkResult struct {
	Items []MyWorkItem `json:"items,omitempty"`
}

type Node struct {
	ID        *string  `json:"id,omitempty"`
	ParentID  *string  `json:"parent_id,omitempty"`
	Kind      *string  `json:"kind,omitempty"`
	AliasID   *string  `json:"alias_id,omitempty"`
	Title     *string  `json:"title,omitempty"`
	Excerpt   *string  `json:"excerpt,omitempty"`
	Templated *bool    `json:"templated,omitempty"`
	Ticket    *Fields  `json:"ticket,omitempty"`
	Event     *Fields  `json:"event,omitempty"`
	Srs       *Fields  `json:"srs,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	Path      *string  `json:"path,omitempty"`
	Num       *float64 `json:"num,omitempty"`
	Width     *string  `json:"width,omitempty"`
	Position  *float64 `json:"position,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}

type NodeTag struct {
	OwnerID *string `json:"owner_id,omitempty"`
	SpaceID *string `json:"space_id,omitempty"`
	NodeID  *string `json:"node_id,omitempty"`
	TagID   *string `json:"tag_id,omitempty"`
	Op      *string `json:"op,omitempty"`
}

type NodeTagOrder struct {
	OwnerID  *string  `json:"owner_id,omitempty"`
	SpaceID  *string  `json:"space_id,omitempty"`
	NodeID   *string  `json:"node_id,omitempty"`
	TagID    *string  `json:"tag_id,omitempty"`
	Position *float64 `json:"position,omitempty"`
}

type NotificationListing struct {
	Items []NotificationView `json:"items,omitempty"`
}

type NotificationView struct {
	ID            *string `json:"id,omitempty"`
	Kind          *string `json:"kind,omitempty"`
	SpaceID       *string `json:"space_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	NodeID        *string `json:"node_id,omitempty"`
	Title         *string `json:"title,omitempty"`
	Actor         *string `json:"actor,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
	ReadAt        *string `json:"read_at,omitempty"`
}

type NotificationsListParams struct {
	// Max rows (default 50)
	Limit *float64 `json:"limit,omitempty"`
}

type NotificationsMarkReadParams struct {
	// Notification ids to mark read
	Ids []string `json:"ids,omitempty"`
	// Mark every unread notification read
	All *bool `json:"all,omitempty"`
}

type OAuthIdentitiesResult struct {
	Identities []LinkedIdentity `json:"identities,omitempty"`
}

type OAuthProvidersResult struct {
	Providers        []ProviderInfo `json:"providers,omitempty"`
	PasswordDisabled *bool          `json:"password_disabled,omitempty"`
}

type OKResult struct {
	Ok *bool `json:"ok,omitempty"`
}

type OauthStartResult struct {
	Url *string `json:"url,omitempty"`
}

type OpInfo struct {
	NodeID *string `json:"node_id,omitempty"`
	TagID  *string `json:"tag_id,omitempty"`
	Op     *string `json:"op,omitempty"`
}

type OrderInfo struct {
	NodeID   *string  `json:"node_id,omitempty"`
	TagID    *string  `json:"tag_id,omitempty"`
	Position *float64 `json:"position,omitempty"`
}

type Page struct {
	ID          *string     `json:"id,omitempty"`
	ParentID    *string     `json:"parent_id,omitempty"`
	OwnerID     *string     `json:"owner_id,omitempty"`
	SpaceID     *string     `json:"space_id,omitempty"`
	Kind        *string     `json:"kind,omitempty"`
	AliasID     *string     `json:"alias_id,omitempty"`
	Title       *string     `json:"title,omitempty"`
	Body        *string     `json:"body,omitempty"`
	Config      *PageConfig `json:"config,omitempty"`
	Slug        *string     `json:"slug,omitempty"`
	PrevSlug    *string     `json:"prev_slug,omitempty"`
	Num         *float64    `json:"num,omitempty"`
	Encrypted   *bool       `json:"encrypted,omitempty"`
	ClientID    *string     `json:"client_id,omitempty"`
	Position    *float64    `json:"position,omitempty"`
	CreatedAt   *string     `json:"created_at,omitempty"`
	UpdatedAt   *string     `json:"updated_at,omitempty"`
	DeletedAt   *string     `json:"deleted_at,omitempty"`
	Undeletable *bool       `json:"undeletable,omitempty"`
}

type PageChangesParams struct {
	// RFC3339Nano updated_at watermark; empty = full pull
	Since *string `json:"since,omitempty"`
}

type PageCloneParams struct {
	// Page id
	ID string `json:"id"`
}

type PageConfig struct {
	Width      *string  `json:"width,omitempty"`
	Visibility *string  `json:"visibility,omitempty"`
	Rss        *bool    `json:"rss,omitempty"`
	Bio        *string  `json:"bio,omitempty"`
	Avatar     *string  `json:"avatar,omitempty"`
	Accent     *string  `json:"accent,omitempty"`
	Link       *string  `json:"link,omitempty"`
	Font       *string  `json:"font,omitempty"`
	Sidebar    *string  `json:"sidebar,omitempty"`
	Banner     *string  `json:"banner,omitempty"`
	BannerH    *string  `json:"banner_h,omitempty"`
	BannerPos  *string  `json:"banner_pos,omitempty"`
	BannerZoom *float64 `json:"banner_zoom,omitempty"`
	AvatarPos  *string  `json:"avatar_pos,omitempty"`
	AvatarZoom *float64 `json:"avatar_zoom,omitempty"`
	Density    *string  `json:"density,omitempty"`
	HideFooter *bool    `json:"hide_footer,omitempty"`
	Dashboard  *string  `json:"dashboard,omitempty"`
}

type PageCreateParams struct {
	// Empty for a root page
	ParentID *string `json:"parent_id,omitempty"`
	// Title
	Title *string `json:"title,omitempty"`
	// Body
	Body *string `json:"body,omitempty"`
	// page or folder
	Kind *string `json:"kind,omitempty"`
	// Target id when kind=alias
	AliasID *string `json:"alias_id,omitempty"`
	// Position
	Position *float64 `json:"position,omitempty"`
	// Optional offline-minted correlation id
	ClientID *string `json:"client_id,omitempty"`
}

type PageDeleteParams struct {
	// Page id
	ID string `json:"id"`
}

type PageExportParams struct {
	// Page id
	ID string `json:"id"`
}

type PageGetParams struct {
	// Page id
	ID string `json:"id"`
}

type PageImportParams struct {
	// Files
	Files []ImportFileParam `json:"files"`
	// replace updates a matched page (history saved); anything else creates a copy
	Mode *string `json:"mode,omitempty"`
	// Compute the create/replace plan without writing
	DryRun *bool `json:"dry_run,omitempty"`
}

type PageListPrefixParams struct {
	// Prefix path to list under; empty = the root
	Path *string `json:"path,omitempty"`
}

type PageMoveToWorkspaceParams struct {
	// The subtree root to move
	ID string `json:"id"`
	// Target workspace id
	TargetWorkspaceID string `json:"target_workspace_id"`
}

type PagePathOfParams struct {
	// Page id
	ID string `json:"id"`
}

type PageRefsParams struct {
	// Page ids
	Ids []string `json:"ids"`
}

type PageResolveKeyParams struct {
	// Jira-style page id KEY-N
	Key string `json:"key"`
}

type PageResolvePathParams struct {
	// Slash slug path to resolve to a node
	Path string `json:"path"`
}

type PageUpdateParams struct {
	// Page id
	ID string `json:"id"`
	// Title
	Title *string `json:"title,omitempty"`
	// Body
	Body *string `json:"body,omitempty"`
	// Position
	Position *float64 `json:"position,omitempty"`
	// Empty string detaches to root
	ParentID *string `json:"parent_id,omitempty"`
	// page or folder or ticket
	Kind *string `json:"kind,omitempty"`
	// Reading width and flags
	Config *PageConfig `json:"config,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type PageUpsertParams struct {
	// Slash-separated slug path; intermediates become folders. e.g. docs/api/auth
	Path string `json:"path"`
	// Display title for the leaf page (slug stays the stable key)
	Title *string `json:"title,omitempty"`
	// Markdown body
	Body *string `json:"body,omitempty"`
}

type PageUsageParams struct {
	// Workspace id (default current space)
	ID *string `json:"id,omitempty"`
}

type PathOfResult struct {
	Path *string `json:"path,omitempty"`
}

type PendingInvite struct {
	ID            *string `json:"id,omitempty"`
	WorkspaceID   *string `json:"workspace_id,omitempty"`
	WorkspaceName *string `json:"workspace_name,omitempty"`
	Role          *string `json:"role,omitempty"`
	InviterHandle *string `json:"inviter_handle,omitempty"`
	InviteeHandle *string `json:"invitee_handle,omitempty"`
}

type PresenceLeaveParams struct {
	// Resource key
	Resource string `json:"resource"`
	// Session token
	Token string `json:"token"`
}

type PresencePingParams struct {
	// Resource key
	Resource string `json:"resource"`
	// Session token
	Token string `json:"token"`
	// Display label
	Label *string `json:"label,omitempty"`
}

type ProfileGetParams struct {
	// Handle
	Handle string `json:"handle"`
}

type ProfilePageData struct {
	Body *string `json:"body,omitempty"`
}

type ProfilePageParams struct {
	// Handle
	Handle string `json:"handle"`
	// Node id
	ID string `json:"id"`
}

type ProfileSaveBlocksParams struct {
	// Config
	Config map[string]any `json:"config,omitempty"`
}

type ProfileSearchParams struct {
	// Handle
	Handle string `json:"handle"`
	// Query
	Q string `json:"q"`
}

type ProfileSetMetaParams struct {
	// Bio
	Bio *string `json:"bio,omitempty"`
	// Avatar URL
	Avatar *string `json:"avatar,omitempty"`
}

type ProfileSetVisibilityParams struct {
	// Public
	Public *bool `json:"public,omitempty"`
}

type ProfileSharesParams struct {
	// Handle
	Handle string `json:"handle"`
}

type ProviderInfo struct {
	Name  *string `json:"name,omitempty"`
	Label *string `json:"label,omitempty"`
}

type QueryResult struct {
	Hits []Hit `json:"hits,omitempty"`
}

type RefInfo struct {
	ID    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Kind  *string `json:"kind,omitempty"`
}

type RefsResult struct {
	Refs []RefInfo `json:"refs,omitempty"`
}

type ReportResult struct {
	Ok *bool `json:"ok,omitempty"`
}

type ResolveKeyResult struct {
	ID *string `json:"id,omitempty"`
}

type Result struct {
	Dash    map[string]any `json:"dash,omitempty"`
	Space   *SharedSpace   `json:"space,omitempty"`
	Header  *Header        `json:"header,omitempty"`
	Tags    *TagState      `json:"tags,omitempty"`
	Private *bool          `json:"private,omitempty"`
}

type RevInfo struct {
	ID        *string `json:"id,omitempty"`
	Title     *string `json:"title,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type RevisionResult struct {
	ID        *string `json:"id,omitempty"`
	Title     *string `json:"title,omitempty"`
	Body      *string `json:"body,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

type RevisionsResult struct {
	Revisions []RevInfo `json:"revisions,omitempty"`
}

type RoleView struct {
	ID    *string      `json:"id,omitempty"`
	Scope *string      `json:"scope,omitempty"`
	Name  *string      `json:"name,omitempty"`
	Grant *MemberGrant `json:"grant,omitempty"`
}

type RolesResult struct {
	Roles []RoleView `json:"roles,omitempty"`
}

type RosterResult struct {
	Names            []string `json:"names,omitempty"`
	Count            *float64 `json:"count,omitempty"`
	HeartbeatSeconds *float64 `json:"heartbeat_seconds,omitempty"`
}

type Row struct {
	Action *string        `json:"action,omitempty"`
	Count  *float64       `json:"count,omitempty"`
	LastAt *string        `json:"last_at,omitempty"`
	Meta   map[string]any `json:"meta,omitempty"`
}

type SRS struct {
	Subject      *string  `json:"subject,omitempty"`
	NodeID       *string  `json:"node_id,omitempty"`
	SpaceID      *string  `json:"space_id,omitempty"`
	Due          *string  `json:"due,omitempty"`
	Ease         *float64 `json:"ease,omitempty"`
	Interval     *float64 `json:"interval,omitempty"`
	Reps         *float64 `json:"reps,omitempty"`
	Lapses       *float64 `json:"lapses,omitempty"`
	LastReviewed *string  `json:"last_reviewed,omitempty"`
	UpdatedAt    *string  `json:"updated_at,omitempty"`
	DeletedAt    *string  `json:"deleted_at,omitempty"`
}

type ScopeFolder struct {
	ID    *string `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
}

type SearchQueryParams struct {
	// Full-text search over your pages
	Query *string `json:"query,omitempty"`
	// Max results
	Limit *float64 `json:"limit,omitempty"`
	// Filter by node kind
	Kinds []string `json:"kinds,omitempty"`
	// Restrict to a folder's subtree
	ScopeRoot *string `json:"scope_root,omitempty"`
}

type SearchResult struct {
	Nodes []SharedNode `json:"nodes,omitempty"`
}

type SetNameResult struct {
	Ok *bool `json:"ok,omitempty"`
}

type SettingsPutParams struct {
	// Freeform UI/e-ink state blob
	Data map[string]any `json:"data"`
}

type SettingsSnapshot struct {
	Data map[string]any `json:"data,omitempty"`
}

type ShareCreateParams struct {
	// Page id
	PageID string `json:"page_id"`
	// Optional; protects the share on create
	Password *string `json:"password,omitempty"`
	// Optional; permit forking on create
	AllowFork *bool `json:"allow_fork,omitempty"`
	// Optional; expose markdown source + tree manifest on create
	AllowRaw *bool `json:"allow_raw,omitempty"`
	// Optional; let logged-in visitors annotate on create
	AllowAnnotations *bool `json:"allow_annotations,omitempty"`
}

type ShareForkInfoParams struct {
	// Fork root page id
	RootID string `json:"root_id"`
}

type ShareForkParams struct {
	// Share token
	Token string `json:"token"`
	// The caller's folder to fork into; empty = root
	ParentID *string `json:"parent_id,omitempty"`
	// Required to fork a password-protected share
	Lease *string `json:"lease,omitempty"`
	// Which workspace to fork into; empty = active
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

type ShareGetParams struct {
	// Share token
	Token string `json:"token"`
	// Lease token from Share/unlock (protected shares)
	Lease *string `json:"lease,omitempty"`
}

type ShareResult struct {
	Shared           *bool   `json:"shared,omitempty"`
	Token            *string `json:"token,omitempty"`
	AllowFork        *bool   `json:"allow_fork,omitempty"`
	AllowRaw         *bool   `json:"allow_raw,omitempty"`
	AllowAnnotations *bool   `json:"allow_annotations,omitempty"`
	AllowRss         *bool   `json:"allow_rss,omitempty"`
	ExportFormats    *string `json:"export_formats,omitempty"`
	Protected        *bool   `json:"protected,omitempty"`
}

type ShareRevokeParams struct {
	// Page id
	PageID string `json:"page_id"`
}

type ShareSetAnnotationsParams struct {
	// Page id
	PageID string `json:"page_id"`
	// Allow annotations
	Allow *bool `json:"allow,omitempty"`
}

type ShareSetExportParams struct {
	// Page id
	PageID string `json:"page_id"`
	// CSV subset of md/zip/epub visitors may download (empty = none)
	Formats *string `json:"formats,omitempty"`
}

type ShareSetForkableParams struct {
	// Page id
	PageID string `json:"page_id"`
	// Allow forking
	Allow *bool `json:"allow,omitempty"`
}

type ShareSetPasswordParams struct {
	// Page id
	PageID string `json:"page_id"`
	// Empty removes protection
	Password *string `json:"password,omitempty"`
}

type ShareSetRSSParams struct {
	// Page id
	PageID string `json:"page_id"`
	// Allow RSS feed
	Allow *bool `json:"allow,omitempty"`
}

type ShareSetRawParams struct {
	// Page id
	PageID string `json:"page_id"`
	// Allow raw
	Allow *bool `json:"allow,omitempty"`
}

type ShareSiteRouteParams struct {
	// Route
	Route string `json:"route"`
}

type ShareStatusParams struct {
	// Page id
	PageID string `json:"page_id"`
}

type ShareUnlockParams struct {
	// Share token
	Token string `json:"token"`
	// Password
	Password string `json:"password"`
}

type SharedListing struct {
	PageID    *string `json:"page_id,omitempty"`
	Token     *string `json:"token,omitempty"`
	AllowFork *bool   `json:"allow_fork,omitempty"`
	Title     *string `json:"title,omitempty"`
	Kind      *string `json:"kind,omitempty"`
}

type SharedNode struct {
	ID        *string     `json:"id,omitempty"`
	ParentID  *string     `json:"parent_id,omitempty"`
	Kind      *string     `json:"kind,omitempty"`
	AliasID   *string     `json:"alias_id,omitempty"`
	Slug      *string     `json:"slug,omitempty"`
	PrevSlug  *string     `json:"prev_slug,omitempty"`
	Num       *float64    `json:"num,omitempty"`
	Title     *string     `json:"title,omitempty"`
	Body      *string     `json:"body,omitempty"`
	Excerpt   *string     `json:"excerpt,omitempty"`
	Config    *PageConfig `json:"config,omitempty"`
	Tint      *string     `json:"tint,omitempty"`
	Status    *string     `json:"status,omitempty"`
	Priority  *string     `json:"priority,omitempty"`
	Due       *string     `json:"due,omitempty"`
	StartAt   *string     `json:"start_at,omitempty"`
	EndAt     *string     `json:"end_at,omitempty"`
	AllDay    *bool       `json:"all_day,omitempty"`
	Tz        *string     `json:"tz,omitempty"`
	Rrule     *string     `json:"rrule,omitempty"`
	Location  *string     `json:"location,omitempty"`
	Position  *float64    `json:"position,omitempty"`
	CreatedAt *string     `json:"created_at,omitempty"`
	UpdatedAt *string     `json:"updated_at,omitempty"`
}

type SharedSpace struct {
	RootID           *string      `json:"root_id,omitempty"`
	AllowFork        *bool        `json:"allow_fork,omitempty"`
	AllowRaw         *bool        `json:"allow_raw,omitempty"`
	AllowRss         *bool        `json:"allow_rss,omitempty"`
	AllowAnnotations *bool        `json:"allow_annotations,omitempty"`
	ExportFormats    *string      `json:"export_formats,omitempty"`
	Key              *string      `json:"key,omitempty"`
	Nodes            []SharedNode `json:"nodes,omitempty"`
	Protected        *bool        `json:"protected,omitempty"`
	RenderMode       *string      `json:"render_mode,omitempty"`
	ShowForkBadge    *bool        `json:"show_fork_badge,omitempty"`
}

type SharesResult struct {
	Shares []SharedListing `json:"shares,omitempty"`
}

type SrsDeleteAck struct {
	NodeID *string `json:"node_id,omitempty"`
	Ok     *bool   `json:"ok,omitempty"`
}

type SrsDeleteParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type SrsGetParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type SrsSetParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// ISO date (next review)
	Due *string `json:"due,omitempty"`
	// SM-2 ease factor
	Ease *float64 `json:"ease,omitempty"`
	// days
	Interval *float64 `json:"interval,omitempty"`
	// Reps
	Reps *float64 `json:"reps,omitempty"`
	// Lapses
	Lapses *float64 `json:"lapses,omitempty"`
	// RFC3339
	LastReviewed *string `json:"last_reviewed,omitempty"`
}

type Tag struct {
	ID       *string  `json:"id,omitempty"`
	OwnerID  *string  `json:"owner_id,omitempty"`
	SpaceID  *string  `json:"space_id,omitempty"`
	Name     *string  `json:"name,omitempty"`
	Color    *string  `json:"color,omitempty"`
	Category *string  `json:"category,omitempty"`
	Position *float64 `json:"position,omitempty"`
}

type TagCatalogResult struct {
	Tags   []Tag       `json:"tags,omitempty"`
	Ops    []OpInfo    `json:"ops,omitempty"`
	Orders []OrderInfo `json:"orders,omitempty"`
}

type TagClearNodeParams struct {
	// Node id
	NodeID *string `json:"node_id,omitempty"`
	// Tag id
	TagID string `json:"tag_id"`
}

type TagCreateParams struct {
	// Tag name
	Name string `json:"name"`
	// default|red|orange|amber|green|blue|violet
	Color *string `json:"color,omitempty"`
	// facet like type; empty = plain label
	Category *string `json:"category,omitempty"`
}

type TagDeleteParams struct {
	// Tag id
	ID string `json:"id"`
}

type TagReorderGlobalParams struct {
	// Tag ids in order
	TagIds []string `json:"tag_ids"`
}

type TagReorderNodeParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Tag ids in order (empty clears the override)
	TagIds []string `json:"tag_ids,omitempty"`
}

type TagSetNodeParams struct {
	// Empty for the global level
	NodeID *string `json:"node_id,omitempty"`
	// Tag id
	TagID string `json:"tag_id"`
	// add or remove
	Op string `json:"op"`
}

type TagSetNodeTagsParams struct {
	// Empty for the global level
	NodeID *string `json:"node_id,omitempty"`
	// Tag ids
	TagIds []string `json:"tag_ids"`
	// add or remove
	Op string `json:"op"`
}

type TagState struct {
	Tags   []Tag          `json:"tags,omitempty"`
	Ops    []NodeTag      `json:"ops,omitempty"`
	Orders []NodeTagOrder `json:"orders,omitempty"`
}

type TagUpdateParams struct {
	// Tag id
	ID string `json:"id"`
	// Tag name
	Name string `json:"name"`
	// Pigment
	Color *string `json:"color,omitempty"`
}

type Template struct {
	ID        *string  `json:"id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	Name      *string  `json:"name,omitempty"`
	Body      *string  `json:"body,omitempty"`
	Meta      *string  `json:"meta,omitempty"`
	Seq       *float64 `json:"seq,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
}

type TemplateCreateParams struct {
	// Template name
	Name string `json:"name"`
	// Body (markdown skeleton)
	Body *string `json:"body,omitempty"`
	// Meta (JSON: ticket defaults etc.)
	Meta *string `json:"meta,omitempty"`
}

type TemplateDeleteParams struct {
	// Template id
	ID string `json:"id"`
}

type TemplateDeleted struct {
	ID *string `json:"id,omitempty"`
	Ok *bool   `json:"ok,omitempty"`
}

type TemplateGetParams struct {
	// Template id
	ID string `json:"id"`
}

type TemplateInstantiateParams struct {
	// Template id
	TemplateID string `json:"template_id"`
	// Parent folder id (empty = root)
	ParentID *string `json:"parent_id,omitempty"`
	// page or ticket (default page)
	Kind *string `json:"kind,omitempty"`
	// Title
	Title *string `json:"title,omitempty"`
	// Field values by name
	Values map[string]any `json:"values,omitempty"`
}

type TemplateList struct {
	Templates []Template `json:"templates,omitempty"`
}

type TemplateUpdateParams struct {
	// Template id
	ID string `json:"id"`
	// Template name
	Name string `json:"name"`
	// Body (markdown skeleton)
	Body *string `json:"body,omitempty"`
	// Meta (JSON: ticket defaults etc.)
	Meta *string `json:"meta,omitempty"`
}

type Ticket struct {
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	Owner     *string  `json:"owner,omitempty"`
	Type      []string `json:"type,omitempty"`
	Status    *string  `json:"status,omitempty"`
	Priority  *string  `json:"priority,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	Due       *string  `json:"due,omitempty"`
	Estimate  *string  `json:"estimate,omitempty"`
	UpdatedAt *string  `json:"updated_at,omitempty"`
	DeletedAt *string  `json:"deleted_at,omitempty"`
}

type TicketChangesParams struct {
	// RFC3339Nano cursor; empty = full
	Since *string `json:"since,omitempty"`
}

type TicketDeleteAck struct {
	NodeID *string `json:"node_id,omitempty"`
	Ok     *bool   `json:"ok,omitempty"`
}

type TicketDeleteParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type TicketFeed struct {
	Tickets    []Ticket `json:"tickets,omitempty"`
	Tombstones []string `json:"tombstones,omitempty"`
	Cursor     *string  `json:"cursor,omitempty"`
}

type TicketGetParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type TicketHistoryParams struct {
	// Node id
	NodeID string `json:"node_id"`
}

type TicketMyWorkParams struct {
	// true = every workspace you belong to; default = current only
	All *bool `json:"all,omitempty"`
}

type TicketPatchParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Owner
	Owner *string `json:"owner,omitempty"`
	// Type
	Type []string `json:"type,omitempty"`
	// Status
	Status *string `json:"status,omitempty"`
	// Priority
	Priority *string `json:"priority,omitempty"`
	// Assignee
	Assignee []string `json:"assignee,omitempty"`
	// Due
	Due *string `json:"due,omitempty"`
	// Estimate
	Estimate *string `json:"estimate,omitempty"`
	// Base updated_at
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type TicketRestoreParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// Revision id
	RevID string `json:"rev_id"`
}

type TicketResult struct {
	Ticket *string  `json:"ticket,omitempty"`
	Url    *string  `json:"url,omitempty"`
	Ttl    *float64 `json:"ttl,omitempty"`
}

type TicketRevision struct {
	ID        *string  `json:"id,omitempty"`
	NodeID    *string  `json:"node_id,omitempty"`
	SpaceID   *string  `json:"space_id,omitempty"`
	OwnerID   *string  `json:"owner_id,omitempty"`
	Owner     *string  `json:"owner,omitempty"`
	Type      []string `json:"type,omitempty"`
	Status    *string  `json:"status,omitempty"`
	Priority  *string  `json:"priority,omitempty"`
	Assignee  []string `json:"assignee,omitempty"`
	Due       *string  `json:"due,omitempty"`
	Estimate  *string  `json:"estimate,omitempty"`
	CreatedAt *string  `json:"created_at,omitempty"`
}

type TicketSetParams struct {
	// Node id
	NodeID string `json:"node_id"`
	// single responsible user id
	Owner *string `json:"owner,omitempty"`
	// tag ids (category type)
	Type []string `json:"type,omitempty"`
	// todo doing or done
	Status *string `json:"status,omitempty"`
	// low med or high
	Priority *string `json:"priority,omitempty"`
	// user ids (a ticket can have many)
	Assignee []string `json:"assignee,omitempty"`
	// ISO date
	Due *string `json:"due,omitempty"`
	// Estimate
	Estimate *string `json:"estimate,omitempty"`
	// Optimistic-concurrency token
	BaseUpdatedAt *string `json:"base_updated_at,omitempty"`
}

type TreeResult struct {
	Pages []Node `json:"pages,omitempty"`
}

type UnlockResult struct {
	Lease     *string `json:"lease,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

type UploadDeleteAck struct {
	Ok *bool `json:"ok,omitempty"`
}

type UploadDeleteManyParams struct {
	// Image shas
	Shas []string `json:"shas"`
}

type UploadDeleteParams struct {
	// Image sha
	Sha string `json:"sha"`
}

type UploadListParams struct {
	// Search (name)
	Q *string `json:"q,omitempty"`
	// Limit
	Limit *float64 `json:"limit,omitempty"`
	// Offset
	Offset *float64 `json:"offset,omitempty"`
}

type UploadListing struct {
	Items []MediaItem `json:"items,omitempty"`
}

type UploadPrepared struct {
	Ticket *string `json:"ticket,omitempty"`
	Url    *string `json:"url,omitempty"`
}

type UploadReportParams struct {
	// Space id
	Space string `json:"space"`
	// Image sha
	Sha string `json:"sha"`
	// Reason
	Reason *string `json:"reason,omitempty"`
}

type UploadSetNameParams struct {
	// Image sha
	Sha string `json:"sha"`
	// Name
	Name *string `json:"name,omitempty"`
}

type UploadStatusInfo struct {
	Enabled  *bool    `json:"enabled,omitempty"`
	MaxBytes *float64 `json:"max_bytes,omitempty"`
	MaxDim   *float64 `json:"max_dim,omitempty"`
}

type UsageKind struct {
	Kind  *string  `json:"kind,omitempty"`
	Count *float64 `json:"count,omitempty"`
}

type UsageResult struct {
	Used      *float64    `json:"used,omitempty"`
	Limit     *float64    `json:"limit,omitempty"`
	Unlimited *bool       `json:"unlimited,omitempty"`
	Folders   *float64    `json:"folders,omitempty"`
	Kinds     []UsageKind `json:"kinds,omitempty"`
}

type WorkspaceAcceptInviteLinkParams struct {
	// Link token
	Token string `json:"token"`
}

type WorkspaceAcceptInviteParams struct {
	// Invite id
	InviteID string `json:"invite_id"`
}

type WorkspaceCancelInviteParams struct {
	// Workspace id
	ID string `json:"id"`
	// Invite id
	InviteID string `json:"invite_id"`
}

type WorkspaceCreateInviteLinkParams struct {
	// Workspace id
	ID string `json:"id"`
	// admin | writer | viewer (default writer)
	Role *string `json:"role,omitempty"`
	// 0 = never
	ExpiresDays *float64 `json:"expires_days,omitempty"`
	// 0 = unlimited
	MaxUses *float64 `json:"max_uses,omitempty"`
}

type WorkspaceCreateKeyParams struct {
	// Workspace id
	ID string `json:"id"`
	// Name
	Name string `json:"name"`
	// read or write (default write)
	Tier *string `json:"tier,omitempty"`
	// Page id of a folder in the workspace; empty = whole workspace
	ScopeRoot *string `json:"scope_root,omitempty"`
	// 0 = never
	ExpiresInDays *float64 `json:"expires_in_days,omitempty"`
	// several folder ids; supersedes scope_root
	ScopeRoots []string `json:"scope_roots,omitempty"`
	// feature to read|write; empty = full access
	Capabilities map[string]any `json:"capabilities,omitempty"`
	// rpc and/or mcp; empty = both
	Surfaces []string `json:"surfaces,omitempty"`
}

type WorkspaceCreateParams struct {
	// Workspace name
	Name string `json:"name"`
}

type WorkspaceDeclineInviteParams struct {
	// Invite id
	InviteID string `json:"invite_id"`
}

type WorkspaceDeleteParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspaceInviteParams struct {
	// Workspace id
	ID string `json:"id"`
	// Must be an existing user
	Identity string `json:"identity"`
	// admin | writer | viewer (default writer)
	Role *string `json:"role,omitempty"`
}

type WorkspaceInvitesParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspaceKeysWithAccessParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspaceLeaveParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspaceListInviteLinksParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspaceListKeysParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspaceListing struct {
	Workspaces []Info  `json:"workspaces,omitempty"`
	Current    *string `json:"current,omitempty"`
}

type WorkspaceMembersParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspacePreviewInviteLinkParams struct {
	// Link token
	Token string `json:"token"`
}

type WorkspaceRemoveMemberParams struct {
	// Workspace id
	ID string `json:"id"`
	// Member subject
	Subject string `json:"subject"`
	// admin | writer | viewer (setRole only)
	Role *string `json:"role,omitempty"`
}

type WorkspaceRenameParams struct {
	// Workspace id
	ID string `json:"id"`
	// New name
	Name string `json:"name"`
}

type WorkspaceRevokeInviteLinkParams struct {
	// Workspace id
	ID string `json:"id"`
	// Link token
	Token string `json:"token"`
}

type WorkspaceRevokeKeyAccessParams struct {
	// Workspace id
	ID string `json:"id"`
	// Key id
	KeyID string `json:"key_id"`
}

type WorkspaceRevokeKeyParams struct {
	// Workspace id
	ID string `json:"id"`
	// Key id
	KeyID string `json:"key_id"`
}

type WorkspaceRoleDeleteParams struct {
	// Workspace id
	ID string `json:"id"`
	// Role id
	RoleID string `json:"role_id"`
}

type WorkspaceRoleUpsertParams struct {
	// Workspace id
	ID string `json:"id"`
	// empty to create
	RoleID *string `json:"role_id,omitempty"`
	// owner or workspace (create only)
	Scope *string `json:"scope,omitempty"`
	// Role name
	Name string `json:"name"`
	// off|read|write
	Default *string `json:"default,omitempty"`
	// feature to read|write
	Caps map[string]any `json:"caps,omitempty"`
	// Can manage the workspace
	Manage *bool `json:"manage,omitempty"`
}

type WorkspaceRolesParams struct {
	// Workspace id
	ID string `json:"id"`
}

type WorkspaceSetColorParams struct {
	// Workspace id
	ID string `json:"id"`
	// red|orange|amber|green|blue|violet; empty = default
	Color *string `json:"color,omitempty"`
}

type WorkspaceSetKeyParams struct {
	// Workspace id
	ID string `json:"id"`
	// Short uppercase prefix for KEY-N page ids
	Key string `json:"key"`
}

type WorkspaceSetRoleParams struct {
	// Workspace id
	ID string `json:"id"`
	// Member subject
	Subject string `json:"subject"`
	// admin | writer | viewer (setRole only)
	Role *string `json:"role,omitempty"`
}
